export const enAk = [
  {
    id: 101,
    image: "/menu/akatsija/meat_set.jpeg",
    title: "Мясная тарелка",
    price: "350",
    category: "Холодные закуски",
    ingredients: "Шейка свиная, балык, грудинка, телятина, 200г",
    menu_number: null,
    price1: null,
    beachPrice: null,
    subCategory: null,
    restaurantMenu: true,
    beachMenu: false,
  },
  {
    id: 201,
    image: "/menu/akatsija/uha.jpeg",
    title: "Уха царская",
    price: "330",
    category: "Первые блюда",
    ingredients:
      "Бульон, белая и красная рыба, картофель, зелень, тосты, икра красная, 410г",
    menu_number: null,
    price1: null,
    beachPrice: null,
    subCategory: null,
    restaurantMenu: true,
    beachMenu: false,
  },
  {
    id: 301,
    image: "/menu/akatsija/pelmeni.jpeg",
    title: "Пельмени домашние",
    price: "220",
    category: "Вторые бдюда",
    ingredients: "200г",
    menu_number: null,
    price1: null,
    beachPrice: null,
    subCategory: null,
    restaurantMenu: true,
    beachMenu: false,
  },
  {
    id: 302,
    image: "/menu/akatsija/shish_kebab.jpeg",
    title: "Шиш кебаб из свинины",
    price: "580",
    category: "Вторые бдюда",
    ingredients: " ",
    menu_number: null,
    price1: null,
    beachPrice: null,
    subCategory: null,

    restaurantMenu: true,
    beachMenu: false,
  },
  {
    id: 401,
    image: "/menu/akatsija/beer_set_sea.jpeg",
    title: "Пивной набор Море",
    price: "490",
    category: "К Пиву",
    ingredients:
      "Мидии в пивном кляре, кольца кальмара к кляре, креветки жареные с чесноком, рыбка мелкая в кляре, соус, 375г",
    menu_number: null,
    price1: null,
    beachPrice: null,
    subCategory: null,
    restaurantMenu: true,
    beachMenu: false,
  },
  {
    id: 402,
    image: "/menu/akatsija/beer_set_meat.jpeg",
    title: "Пивной набор Мясной",
    price: "440",
    category: "К Пиву",
    ingredients:
      "Куриные крылышки-фри, колбаски охотничьи, пельмени фри, сулугуни копченый, аджика, 500г",
    menu_number: null,
    price1: null,
    beachPrice: null,
    subCategory: null,
    restaurantMenu: true,
    beachMenu: false,
  },
];
