export const el = [
  {
    menuNumber: 101,
    title: "Χωριάτικη",
    category: "ΣΑΛΑΤΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 102,
    title: "Σαλάτα Καίσαρα",
    category: "ΣΑΛΑΤΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 103,
    title: "Σπέσιαλ Σαλάτα",
    category: "ΣΑΛΑΤΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 104,
    title: "Τονοσαλατα",
    category: "ΣΑΛΑΤΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 105,
    title: "Φρουτοσαλάτα",
    category: "ΣΑΛΑΤΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 201,
    title: "Hamburger",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients: "Με ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 202,
    title: "Cheeseburger",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients: "Με ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 203,
    title: "Cheese & Bacon",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients: "Με ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 204,
    title: "Chicken burger",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients: "Με ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 205,
    title: "Egg & bacon burger",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients:
      "Με φρέσκια κρέμα τυριού, ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 206,
    title: "Cheese chicken burger",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients:
      "Με καραμελωμένα κρεμμύδια και ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 301,
    title: "Cheesburger + potatoes",
    category: "ΜΕΡΙΔΕΣ ΜΠΕΡΓΚΕΡ",
    ingredients: "Με ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 302,
    title: "Cheese & Bacon  + potatoes",
    category: "ΜΕΡΙΔΕΣ ΜΠΕΡΓΚΕΡ",
    ingredients: "Με ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 303,
    title: "Chicken burger + potatoes",
    category: "ΜΕΡΙΔΕΣ ΜΠΕΡΓΚΕΡ",
    ingredients: "Με ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 304,
    title: "Egg & bacon + potatoes",
    category: "ΜΕΡΙΔΕΣ ΜΠΕΡΓΚΕΡ",
    ingredients:
      "Με φρέσκια κρέμα τυριού, ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 305,
    title: "Cheese chicken  + potatoes",
    category: "ΜΕΡΙΔΕΣ ΜΠΕΡΓΚΕΡ",
    ingredients:
      "Με καραμελωμένα κρεμμύδια και ντομάτα, μαρούλι, αγγούρι, μαγιονέζα, κέτσαπ",
  },
  {
    menuNumber: 401,
    title: "Τοστ με γαλοπούλα και τυρί Τσέδαρ",
    category: "CLUB SANDWICHES",
    ingredients: "",
  },
  {
    menuNumber: 402,
    title: "Club Sandwich",
    category: "CLUB SANDWICHES",
    ingredients: "",
  },
  {
    menuNumber: 403,
    title: "Chicken club sandwich ",
    category: "CLUB SANDWICHES",
    ingredients: "",
  },
  {
    menuNumber: 404,
    title: " Μερίδα γύρο χοιρινό με πίτα & τζατζικι ",
    category: "CLUB SANDWICHES",
    ingredients: "",
  },
  {
    menuNumber: 405,
    title: "Μερίδα γύρο κοτόπουλο με πίτα και τζατζικι",
    category: "CLUB SANDWICHES",
    ingredients: "",
  },
  {
    menuNumber: 406,
    title: "Focaccia Vegeterian (360γρ)",
    category: "CLUB SANDWICHES",
    ingredients: "Με τηγανητές πατάτες και σάλτσα κοκτέιλ",
  },
  {
    menuNumber: 407,
    title: "Focaccia με μοτσαρελα (360γρ)",
    category: "CLUB SANDWICHES",
    ingredients: "Με τηγανητές πατάτες και σάλτσα κοκτέιλ",
  },
  {
    menuNumber: 408,
    title: "Focaccia με γύρο κοτοπουλο (360γρ)",
    category: "CLUB SANDWICHES",
    ingredients: "Με τηγανητές πατάτες και σάλτσα κοκτέιλ",
  },
  {
    menuNumber: 409,
    title: "Focaccia με γύρο χοιρινο (360γρ)",
    category: "CLUB SANDWICHES",
    ingredients: "Με τηγανητές πατάτες και σάλτσα κοκτέιλ",
  },
  {
    menuNumber: 410,
    title: "Focaccia με φιλέτο κοτοπουλο (360γρ)",
    category: "CLUB SANDWICHES",
    ingredients: "Με τηγανητές πατάτες και σάλτσα κοκτέιλ",
  },
  {
    menuNumber: 411,
    title: "Focaccia αλλαντικων (360γρ)",
    category: "CLUB SANDWICHES",
    ingredients: "Με τηγανητές πατάτες και σάλτσα κοκτέιλ",
  },
  {
    menuNumber: 412,
    title: "Focaccia με 4 τυρια (360γρ)",
    category: "CLUB SANDWICHES",
    ingredients: "Με τηγανητές πατάτες και σάλτσα κοκτέιλ",
  },
  {
    menuNumber: 413,
    title: "Τηγανιτές πατάτες",
    category: "CLUB SANDWICHES",
    ingredients: "",
  },
  {
    menuNumber: 414,
    title: "Τηγανιτές πατάτες με μπέικον",
    category: "CLUB SANDWICHES",
    ingredients:
      "Με μπέικον, τριμμένη παρμεζάνα, σάλτσα τσέντερ και φρέσκια κρέμα τυριού",
  },
  {
    menuNumber: 501,
    title: "Chocolate pancake",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients: "Με μπανάνα και τριμμένα μπισκότα",
  },
  {
    menuNumber: 502,
    title: "Pancake with honey and yogurt",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients: "Με μέλι, γιαούρτι και ψιλοκομμένα καρύδια",
  },
  {
    menuNumber: 503,
    title: "Breakfast pancake",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients:
      "Με ζαμπόν και τυρί, διπλό μπέικον, αυγά και σάλτσα φρέσκιας κρέμας τυριού",
  },
  {
    menuNumber: 504,
    title: "Waffle chocolate",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients: "Με ψιλοκομμένα καρύδια, βανίλια και παγωτό σοκολάτα",
  },
  {
    menuNumber: 505,
    title: "Waffle OREO",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients: "Με πραλίνα, τριμμένα μπισκότα Oreo και 2 μπάλες παγωτό Oreo",
  },
  {
    menuNumber: 506,
    title: "Waffle with fruits",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients:
      "Με φρέσκα εποχιακά φρούτα και 2 μπάλες σορμπέ φράουλας και μάνγκο",
  },
  {
    menuNumber: 507,
    title: "Chocolate souffle",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients: "Με παγωτό βανίλια",
  },
  {
    menuNumber: 508,
    title: "Chocolate Brownies",
    category: "ΕΠΙΔΟΡΠΙΑ",
    ingredients: "Με καρύδια, σιρόπι σοκολάτας και παγωτό βανίλια",
  },
  {
    menuNumber: 601,
    title: "Buena ferrera",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Μια τέλεια αρμονία τραγανού μπισκότου και σοκολάτας γάλακτος",
  },
  {
    menuNumber: 602,
    title: "Capricciosa",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Aπίθανη γεύση σοκολάτας με πουράκια τύπου caprice",
  },
  {
    menuNumber: 603,
    title: "Οreo",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Λευκή σοκολάτα με OREO μπισκότο τριμμένο",
  },
  {
    menuNumber: 604,
    title: "Alato",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients:
      "Πλούσια γεύση σοκολάτας γάλακτος πασπαλισμένη με θαλασσινό αλάτι.",
  },
  {
    menuNumber: 605,
    title: "Viennua",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients:
      "Αυθεντική συνταγή αρωματικής σοκολάτας με κακάο 40% και σαντιγί, όπως ακριβώς στη Βιέννη",
  },
  {
    menuNumber: 606,
    title: "Classica",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients:
      "Κλασική γεύση σοκολάτας από ποικιλίες κακάο τροπικής Αφρικής.",
  },
  {
    menuNumber: 607,
    title: "Sugar free",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Η άλλη εκδοχή κλασικής σοκολάτας χωρίς ζάχαρη, με στέβια",
  },
  {
    menuNumber: 608,
    title: "Bitter aztec",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Μπίτερ σκούρη σοκολάτα με εκρηκτική γεύση και άρωμα",
  },
  {
    menuNumber: 609,
    title: "Fragola",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Σοκολάτα  με γεύση φράουλας  και αρώματα βανίλιας ",
  },
  {
    menuNumber: 610,
    title: "Banana",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Σοκολάτα με γεύση μπανάνα",
  },
  {
    menuNumber: 611,
    title: "Coconut",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Σοκολάτα με γεύση από γάλα καρύδας",
  },
  {
    menuNumber: 612,
    title: "Cafelatta",
    category: "ΣΟΚΟΛΑΤΕΣ",
    ingredients: "Σοκολάτα με υπέροχη γεύση φουντουκιού καφέ και αφρόγαλο",
  },
  {
    menuNumber: 701,
    title: "Ελληνικός καφές",
    category: "Καφές",
    ingredients: "",
  },
  { menuNumber: 702, title: "Φραπέ", category: "Καφές", ingredients: "" },
  {
    menuNumber: 703,
    title: "Φραπέ με παγωτο",
    category: "Καφές",
    ingredients: "",
  },
  { menuNumber: 704, title: "Espresso", category: "Καφές", ingredients: "" },
  {
    menuNumber: 705,
    title: "Cappucinno",
    category: "Καφές",
    ingredients: "",
  },
  {
    menuNumber: 706,
    title: "Freddo cappucinno",
    category: "Καφές",
    ingredients: "",
  },
  {
    menuNumber: 707,
    title: "Freddo espresso",
    category: "Καφές",
    ingredients: "",
  },
  {
    menuNumber: 708,
    title: "Κρύα σοκολάτα",
    category: "Καφές",
    ingredients: "",
  },
  {
    menuNumber: 709,
    title: "Ζεστή σοκολάτα",
    category: "Καφές",
    ingredients: "",
  },
  {
    menuNumber: 710,
    title: "Μιλκσέικ",
    category: "Καφές",
    ingredients: "Βανίλια-σοκολάτα, μπανάνα, φράουλα",
  },
  {
    menuNumber: 711,
    title: "Ζεστό τσάι",
    category: "Καφές",
    ingredients: "Πράσινο, μαύρο",
  },
  {
    menuNumber: 712,
    title: "Μοκατσίνο",
    category: "Καφές",
    ingredients: "",
  },
  {
    menuNumber: 801,
    title: "Πορτοκάλι",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  { menuNumber: 802, title: "Μπανάνα", category: "ΧΥΜΟΙ", ingredients: "" },
  { menuNumber: 803, title: "Κεράσι", category: "ΧΥΜΟΙ", ingredients: "" },
  {
    menuNumber: 804,
    title: "Ροδάκινο",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  { menuNumber: 805, title: "Ανανάς", category: "ΧΥΜΟΙ", ingredients: "" },
  { menuNumber: 806, title: "Μήλο", category: "ΧΥΜΟΙ", ingredients: "" },
  {
    menuNumber: 807,
    title: "Κρανμπερι",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  {
    menuNumber: 808,
    title: "Φυσικός χυμός πορτοκαλι",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  {
    menuNumber: 809,
    title: "Σπιτική λεμονάδα",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  {
    menuNumber: 810,
    title: "Φυσικός χυμός πορτοκάλι με γκρειπφρουτ",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  {
    menuNumber: 811,
    title: "Φυσικός χυμός πορτοκάλι με λεμονι",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  {
    menuNumber: 812,
    title: "Κρύο τσαι",
    category: "ΧΥΜΟΙ",
    ingredients: "Πράσινο, λεμόνι, ροδάκινο",
  },
  {
    menuNumber: 813,
    title: "Γρανιτα",
    category: "ΧΥΜΟΙ",
    ingredients: "",
  },
  {
    menuNumber: 901,
    title: "Βίκος κόλα",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  {
    menuNumber: 902,
    title: "Βίκος πορτοκαλαδα ",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  {
    menuNumber: 903,
    title: "Βίκος λεμοναδα",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  {
    menuNumber: 904,
    title: "Βίκος γκαζοζα",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  {
    menuNumber: 905,
    title: "Βίκος Τονικ",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  {
    menuNumber: 906,
    title: "Βίκος σοδα",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  {
    menuNumber: 907,
    title: "Βίκος σοδα με γκρειπφρουτ",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  {
    menuNumber: 909,
    title: "Red bull 355ml",
    category: "ΑΝΑΨΥΚΤΙΚΑ",
    ingredients: "",
  },
  { menuNumber: 1001, title: "Amstel", category: "ΜΠΥΡΕΣ", ingredients: "" },
  {
    menuNumber: 1002,
    title: "Amstel dark",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1003,
    title: "Amstel radler",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1004,
    title: "Amstel free",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1005,
    title: "Heineken",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  { menuNumber: 1006, title: "Mythos", category: "ΜΠΥΡΕΣ", ingredients: "" },
  {
    menuNumber: 1007,
    title: "Stella Artois",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  { menuNumber: 1008, title: "Sol", category: "ΜΠΥΡΕΣ", ingredients: "" },

  { menuNumber: 1009, title: "Fisher", category: "ΜΠΥΡΕΣ", ingredients: "" },
  {
    menuNumber: 1010,
    title: "MC farland",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1011,
    title: "Krusovice",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1012,
    title: "Erdinger",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1013,
    title: "Μηλοκλέφτης Μήλο",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1014,
    title: "Μηλοκλέφτης Κεράσι",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1015,
    title: "Βαρελίσια μπίρα 300μλ",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1016,
    title: "Βαρελίσια μπίρα 500μλ",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1017,
    title: "Ούζο Πλωμαρίου 200μλ",
    category: "ΜΠΥΡΕΣ",
    ingredients: "",
  },
  {
    menuNumber: 1101,
    title: "Mojito",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1102,
    title: "Mojito strawberry",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1103,
    title: "Mojito blue",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1104,
    title: "Mojito free",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1105,
    title: "Caipirinha",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1106,
    title: "Cosmopolitan",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1107,
    title: "Cuba libre",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1108,
    title: "Daquiri",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1109,
    title: "Daquiri strawberry",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1110,
    title: "Pina colada",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1111,
    title: "Sex on the beach",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1112,
    title: "Tequila sunrise",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1113,
    title: "Watermelon",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1114,
    title: "Blue lagoon",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1115,
    title: "Margarita",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1116,
    title: "Blue hawaian",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1117,
    title: "Aperol Spritz",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1118,
    title: "Long island",
    category: "ΚΟΚΤΕΙΛΣ",
    ingredients: "",
  },
  {
    menuNumber: 1201,
    title: "Μοσχοφίλερο Ξηρός Λευκός Οίνος   ",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "187μλ",
  },
  {
    menuNumber: 1202,
    title: "Μοσχοφίλερο Ξηρός Λευκός Οίνος",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "750μλ",
  },
  {
    menuNumber: 1203,
    title: "Καραμέλο Ημίγλυκος Λευκός Οίνος",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "187μλ",
  },
  {
    menuNumber: 1204,
    title: "Καραμέλο Ημίγλυκος Λευκός Οίνος",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "750μλ",
  },
  {
    menuNumber: 1205,
    title: "Καραμέλο Ημίγλυκος Ερυθρός Οίνος",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "187μλ",
  },
  {
    menuNumber: 1206,
    title: "Καραμέλο Ημίξηρος Ερυθρός Οίνος",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "750μλ",
  },
  {
    menuNumber: 1207,
    title: "Καραμέλο Ροζέ Οίνος",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "187μλ",
  },
  {
    menuNumber: 1208,
    title: "Καραμέλο Ροζέ Οίνος",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "750μλ",
  },
  {
    menuNumber: 1209,
    title: "Σαγκρία Λευκού Οίνου",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "187μλ",
  },
  {
    menuNumber: 1210,
    title: "Σαγκρία Ερυθρού Οίνου",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "187μλ",
  },
  {
    menuNumber: 1211,
    title: "Asti martini champagne",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "200μλ",
  },
  {
    menuNumber: 1212,
    title: "Asti martini champagne",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "750μλ",
  },
  {
    menuNumber: 1213,
    title: "Моеt champagne",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "750μλ",
  },
  {
    menuNumber: 1214,
    title:
      "Whisky simple (Dewars, Johnnie, Ballantines, Haig,Famos, J&B, Cutty Sark, Grants)",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1215,
    title:
      "Whisky simple (Dewars, Johnnie, Ballantines, Haig,Famos, J&B, Cutty Sark, Grants)",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "700μλ",
  },
  {
    menuNumber: 1216,
    title:
      "Whisky special (Jack Daniels, Dimple, Chivas, Cardu, Johnnie Black)",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1217,
    title:
      "Whisky special (Jack Daniels, Dimple, Chivas, Cardu, Johnnie Black)",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "700μλ",
  },
  {
    menuNumber: 1218,
    title: "Vodka (Absolut, Stolichnaya, Belvedere, North, Ursus)",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1219,
    title: "Jin Gordons",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1220,
    title: "Hendricks",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1221,
    title: "Bombay",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1222,
    title: "Tanquerey",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1223,
    title: "Bacardi",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1224,
    title: "Metaxa 3*",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1225,
    title: "Metaxa 5*",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1226,
    title: "Metaxa 7*",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1227,
    title: "Tequila Cuervo yellow",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1228,
    title: "Tequila Cuervo white",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1229,
    title: "Martini (Bianco, Rosso, Rossato, Dry)",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1230,
    title: "Havana club (White-Black)",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1231,
    title: "Campari",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1232,
    title: "Malibu",
    category: "ΚΡΑΣΙΑ-ΠΟΤΑ",
    ingredients: "60μλ",
  },
  {
    menuNumber: 1301,
    title: "Smoothie  01",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Φράουλα, ροδάκινο, μπανάνα",
  },
  {
    menuNumber: 1302,
    title: "Smoothie  02",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Φράουλα, μάνγκο, πεπόνι",
  },
  {
    menuNumber: 1303,
    title: "Smoothie  03",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Αχλάδι, μάνγκο, ανανάς",
  },
  {
    menuNumber: 1304,
    title: "Smoothie  04",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Βατόμουρο, βατόμουρο σκούρο, μπανάνα",
  },
  {
    menuNumber: 1305,
    title: "Smoothie  05",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Φρούτο του πάθους, ροδάκινο, μάνγκο",
  },
  {
    menuNumber: 1306,
    title: "Smoothie  06",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Βατόμουρο, μάνγκο, μήλο, βατόμουρο",
  },
  {
    menuNumber: 1307,
    title: "Smoothie  07",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Λεμόνι, καρότο, μήλο, σπανάκι, τζίντζερ",
  },
  {
    menuNumber: 1308,
    title: "Smoothie  08",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Αβοκάντο, λαχανίδα, ξύσμα λεμονιού, μπανάνα",
  },
  {
    menuNumber: 1309,
    title: "Smoothie  09",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Ντράγκον φρούτ, λεμόνι, μπανάνα, μάνγκο",
  },
  {
    menuNumber: 1310,
    title: "Smoothie  10",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Παγωτό, ανανάς, μάνγκο, μπανάνα",
  },
  {
    menuNumber: 1311,
    title: "Smoothie 11",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Μπισκότο, βέγκαν κρέμα",
  },
  {
    menuNumber: 1312,
    title: "Smoothie 12",
    category: "Smoothies",
    subCategory: null,
    ingredients: "Παγωτό, μπανάνα, φράουλα",
  },
  {
    menuNumber: 207,
    title: "Burger with giros pork",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients:
      "Με ψωμί μπριός, ντομάτα, κρεμμύδι, πράσινη σαλάτα, κέτσαπ, μουστάρδα και χοιρινό γύρο με πατάτες",
  },
  {
    menuNumber: 208,
    title: "Burger with giros chicken",
    category: "ΧΑΜΠΟΥΡΓΚΕΡ",
    ingredients:
      "Με ψωμί μπριός, ντομάτα, κρεμμύδι, πράσινη σαλάτα, κέτσαπ, μουστάρδα και κοτόπουλο γύρο με πατάτες",
  },
  {
    menuNumber: 415,
    title: "Σάντουιτς κλαμπ με χοιρινό γύρο",
    category: "CLUB SANDWICHES",
    ingredients: "Με πίτα, τζατζίκι, ντομάτα, κρεμμύδι, πράσινη σαλάτα",
  },
  {
    menuNumber: 416,
    title: "Σάντουιτς κλαμπ με κοτόπουλο γύρο",
    category: "CLUB SANDWICHES",
    ingredients: "Με πίτα, τζατζίκι, ντομάτα, κρεμμύδι, πράσινη σαλάτα",
  },
];
