export const en = [
  {
    id: 101,
    image: "/menu/just/greek.png",
    title: "Greek salad",
    price: "8.5",
    category: "Salads",
    ingredients: " ",
  },
  {
    id: 102,
    image: "/menu/just/photo.jpg",
    title: "Caesar salad",
    price: "9.5",
    category: "Salads",
    ingredients: " ",
  },
  {
    id: 103,
    image: "/menu/just/photo.jpg",
    title: "Special salad",
    price: "9.5",
    category: "Salads",
    ingredients: " ",
  },
  {
    id: 104,
    image: "/menu/just/photo.jpg",
    title: "Tuna salad",
    price: "9.5",
    category: "Salads",
    ingredients: " ",
  },
  {
    id: 105,
    image: "/menu/just/photo.jpg",
    title: "Fruit salad",
    price: "9.5",
    category: "Salads",
    ingredients: " ",
  },
  {
    id: 201,
    image: "/menu/just/photo.jpg",
    title: "Hamburger",
    price: "5",
    category: "Hamburgers",
    ingredients: "With tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 202,
    image: "/menu/just/photo.jpg",
    title: "Cheeseburger",
    price: "6",
    category: "Hamburgers",
    ingredients: "With tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 203,
    image: "/menu/just/photo.jpg",
    title: "Cheese & Bacon",
    price: "6,5",
    category: "Hamburgers",
    ingredients: "With tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 204,
    image: "/menu/just/photo.jpg",
    title: "Chicken burger",
    price: "6,5",
    category: "Hamburgers",
    ingredients: "With tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 205,
    image: "/menu/just/photo.jpg",
    title: "Egg & bacon burger",
    price: "6,5",
    category: "Hamburgers",
    ingredients:
      "With cream cheese, tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 206,
    image: "/menu/just/photo.jpg",
    title: "Cheese chicken burger",
    price: "6,5",
    category: "Hamburgers",
    ingredients:
      "With caramelized onion and tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 301,
    image: "/menu/just/photo.jpg",
    title: "Cheesburger + potatoes",
    price: "9",
    category: "Hamburger set",
    ingredients: "With tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 302,
    image: "/menu/just/photo.jpg",
    title: "Cheese & Bacon  + potatoes",
    price: "9,5",
    category: "Hamburger set",
    ingredients: "With tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 303,
    image: "/menu/just/photo.jpg",
    title: "Chicken burger + potatoes",
    price: "9,5",
    category: "Hamburger set",
    ingredients: "With tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 304,
    image: "/menu/just/photo.jpg",
    title: "Egg & bacon + potatoes",
    price: "10",
    category: "Hamburger set",
    ingredients:
      "With cream cheese, tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 305,
    image: "/menu/just/photo.jpg",
    title: "Cheese chicken  + potatoes",
    price: "9,5",
    category: "Hamburger set",
    ingredients:
      "With caramelized onion and tomatoe, lettuce, cucumber, mayonnaise, ketchup",
  },
  {
    id: 401,
    image: "/menu/just/photo.jpg",
    title: "Toast turkey & cheddar cheese",
    price: "4",
    category: "Sandwiches",
    ingredients: "",
  },
  {
    id: 402,
    image: "/menu/just/photo.jpg",
    title: "Club sandwich",
    price: "8,5",
    category: "Sandwiches",
    ingredients: "",
  },
  {
    id: 403,
    image: "/menu/just/photo.jpg",
    title: "Chicken club sandwich",
    price: "9",
    category: "Sandwiches",
    ingredients: "",
  },
  {
    id: 404,
    image: "/menu/just/photo.jpg",
    title: "Giros portion with pita & tzatziki",
    price: "10",
    category: "Sandwiches",
    ingredients: "",
  },
  {
    id: 405,
    image: "/menu/just/photo.jpg",
    title: "Chicken giros portion with pita",
    price: "10",
    category: "Sandwiches",
    ingredients: "",
  },
  {
    id: 406,
    image: "/menu/just/photo.jpg",
    title: "Focaccia vegeterian (360gr)",
    price: "9",
    category: "Sandwiches",
    ingredients: "With country fries & cocktaile sauce",
  },
  {
    id: 407,
    image: "/menu/just/photo.jpg",
    title: "Focaccia mozarella (360gr)",
    price: "9",
    category: "Sandwiches",
    ingredients: "With country fries & cocktaile sauce",
  },
  {
    id: 408,
    image: "/menu/just/photo.jpg",
    title: "Focaccias chicken giros (360gr)",
    price: "9",
    category: "Sandwiches",
    ingredients: "With country fries & cocktaile sauce",
  },
  {
    id: 409,
    image: "/menu/just/photo.jpg",
    title: "Focaccias pork giros (360gr)",
    price: "9",
    category: "Sandwiches",
    ingredients: "With country fries & cocktaile sauce",
  },
  {
    id: 410,
    image: "/menu/just/photo.jpg",
    title: "Focaccias chicken fillet (360gr)",
    price: "9",
    category: "Sandwiches",
    ingredients: "With country fries & cocktaile sauce",
  },
  {
    id: 411,
    image: "/menu/just/photo.jpg",
    title: "Focaccias gold cuts (360gr)",
    price: "9",
    category: "Sandwiches",
    ingredients: "With country fries & cocktaile sauce",
  },
  {
    id: 412,
    image: "/menu/just/photo.jpg",
    title: "Focaccias 4 cheeses (360gr)",
    price: "9",
    category: "Sandwiches",
    ingredients: "With country fries & cocktaile sauce",
  },
  {
    id: 413,
    image: "/menu/just/photo.jpg",
    title: "French fries",
    price: "5",
    category: "Sandwiches",
    ingredients: "",
  },
  {
    id: 414,
    image: "/menu/just/photo.jpg",
    title: "French fries",
    price: "7,5",
    category: "Sandwiches",
    ingredients:
      "With bacon, trimmed parmesan, cheddar sauce & cream cheese sauce",
  },
  {
    id: 501,
    image: "/menu/just/photo.jpg",
    title: "Chocolate pancake",
    price: "10",
    category: "Sweets",
    ingredients: "With banana & trimmed biscuit",
  },
  {
    id: 502,
    image: "/menu/just/photo.jpg",
    title: "Pancake",
    price: "10",
    category: "Sweets",
    ingredients: "With honey, yoghurt & trimmed walnuts",
  },
  {
    id: 503,
    image: "/menu/just/photo.jpg",
    title: "Pancake",
    price: "10",
    category: "Sweets",
    ingredients: "With hum & chesse, double bacon, egg & cream chesse sauce",
  },
  {
    id: 504,
    image: "/menu/just/photo.jpg",
    title: "Waffle chocolate",
    price: "12",
    category: "Sweets",
    ingredients: "With trimmed nuts, vanilla & chocolate ice cream",
  },
  {
    id: 505,
    image: "/menu/just/photo.jpg",
    title: "Waffle OREO",
    price: "12",
    category: "Sweets",
    ingredients:
      "With praline, trimmed OREO biscuit & 2 balls coocies OREO ice cream",
  },
  {
    id: 506,
    image: "/menu/just/photo.jpg",
    title: "Waffle chocolate",
    price: "12",
    category: "Sweets",
    ingredients:
      "With fresh season fruits & 2 balls of fruity ice cream STRAWBERRY & MANGO SORBE",
  },
  {
    id: 507,
    image: "/menu/just/photo.jpg",
    title: "Chocolate souffle",
    price: "8",
    category: "Sweets",
    ingredients: "With vanilla ice cream",
  },
  {
    id: 508,
    image: "/menu/just/photo.jpg",
    title: "Chocolate Brownies",
    price: "8",
    category: "Sweets",
    ingredients: "With walnuts, chocolate sirop & vanilla ice cream",
  },
  {
    id: 601,
    image: "/menu/just/buena_ferrera.jpg",
    title: "Buena ferrera",
    price: "6",
    category: "Blendissimo",
    ingredients: "A perfect harmony of crispy cookie and milk chocolate",
  },
  {
    id: 602,
    image: "/menu/just/capricciosa.jpg",
    title: "Capricciosa",
    price: "6",
    category: "Blendissimo",
    ingredients: "Incredible chocolate flavor with caprice-type pies.",
  },
  {
    id: 603,
    image: "/menu/just/oreo.jpg",
    title: "Oreo",
    price: "6",
    category: "Blendissimo",
    ingredients: "White chocolate with grated OREO cookie.",
  },
  {
    id: 604,
    image: "/menu/just/alato.jpg",
    title: "Alato",
    price: "6",
    category: "Blendissimo",
    ingredients: "Rich milk chocolate flavor sprinkled with sea salt.",
  },
  {
    id: 605,
    image: "/menu/just/viennua.jpg",
    title: "Viennua",
    price: "6",
    category: "Blendissimo",
    ingredients:
      "Authentic aromatic chocolate recipe with 40% cocoa and whipped cream, just like in Vienna",
  },
  {
    id: 606,
    image: "/menu/just/classica.jpg",
    title: "Classica",
    price: "6",
    category: "Blendissimo",
    ingredients:
      "Classic chocolate flavor from cocoa varieties tropical Africa.",
  },
  {
    id: 607,
    image: "/menu/just/sugar_free.jpg",
    title: "Sugar free",
    price: "6",
    category: "Blendissimo",
    ingredients:
      "The other version of classic chocolate without sugar, with stevia.",
  },
  {
    id: 608,
    image: "/menu/just/bitter_aztec.jpg",
    title: "Bitter aztec",
    price: "6",
    category: "Blendissimo",
    ingredients: "Dark chocolate bitters with an explosive taste and aroma",
  },
  {
    id: 609,
    image: "/menu/just/fragola.jpg",
    title: "Fragola",
    price: "6",
    category: "Blendissimo",
    ingredients: "Chocolate with strawberry flavor and vanilla aromas",
  },
  {
    id: 610,
    image: "/menu/just/banana.jpg",
    title: "Banana",
    price: "6",
    category: "Blendissimo",
    ingredients: "Banana flavored chocolate",
  },
  {
    id: 611,
    image: "/menu/just/coconut.jpg",
    title: " Coconut ",
    price: "6",
    category: "Blendissimo",
    ingredients: "Coconut milk flavored chocolate",
  },
  {
    id: 612,
    image: "/menu/just/cafelatta.jpg",
    title: "Cafelatta",
    price: "6",
    category: "Blendissimo",
    ingredients:
      "Chocolate with a wonderful hazelnut coffee flavor and foamed milk.",
  },
  {
    id: 701,
    image: "/menu/just/photo.jpg",
    title: "Greek coffee",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 702,
    image: "/menu/just/photo.jpg",
    title: "Frappe",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 703,
    image: "/menu/just/photo.jpg",
    title: "Frappe ice cream",
    price: "7",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 704,
    image: "/menu/just/photo.jpg",
    title: "Espresso",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 705,
    image: "/menu/just/photo.jpg",
    title: "Cappucinno",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 706,
    image: "/menu/just/photo.jpg",
    title: "Freddo cappucinno",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 707,
    image: "/menu/just/photo.jpg",
    title: "Freddo espresso",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 708,
    image: "/menu/just/photo.jpg",
    title: "Chocolate cold",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 709,
    image: "/menu/just/photo.jpg",
    title: "Chocolate hot",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 710,
    image: "/menu/just/photo.jpg",
    title: "Milk shake",
    price: "6",
    category: "Coffees",
    ingredients: "Vanilla-chocolate, banana, strawberry",
  },
  {
    id: 711,
    image: "/menu/just/photo.jpg",
    title: "Hot tea",
    price: "6",
    category: "Coffees",
    ingredients: "Green, Black",
  },
  {
    id: 712,
    image: "/menu/just/photo.jpg",
    title: "Mocachino",
    price: "6",
    category: "Coffees",
    ingredients: "",
  },
  {
    id: 801,
    image: "/menu/just/photo.jpg",
    title: "Orange",
    price: "6",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 802,
    image: "/menu/just/photo.jpg",
    title: "Banana",
    price: "6",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 803,
    image: "/menu/just/photo.jpg",
    title: "Cherry",
    price: "6",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 804,
    image: "/menu/just/photo.jpg",
    title: "Peach",
    price: "6",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 805,
    image: "/menu/just/photo.jpg",
    title: "Pineapple",
    price: "6",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 806,
    image: "/menu/just/photo.jpg",
    title: "Apple",
    price: "6",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 807,
    image: "/menu/just/photo.jpg",
    title: "Granberry",
    price: "6",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 808,
    image: "/menu/just/photo.jpg",
    title: "Fresh Orange juice",
    price: "6,5",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 809,
    image: "/menu/just/photo.jpg",
    title: "Homemade lemonade",
    price: "6,5",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 810,
    image: "/menu/just/photo.jpg",
    title: "Fresh orange with grapefruit",
    price: "6,5",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 811,
    image: "/menu/just/photo.jpg",
    title: "Fresh orange with lemon",
    price: "6,5",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 812,
    image: "/menu/just/photo.jpg",
    title: "Ice tea",
    price: "6,5",
    category: "Juices",
    ingredients: "Green, Lemon, Peach",
  },
  {
    id: 813,
    image: "/menu/just/photo.jpg",
    title: "Granita juice",
    price: "6,5",
    category: "Juices",
    ingredients: "",
  },
  {
    id: 901,
    image: "/menu/just/coca_cola.jpg",
    title: "Coca cola",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 902,
    image: "/menu/just/fanta.jpg",
    title: "Fanta",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 903,
    image: "/menu/just/photo.jpg",
    title: "Lemonade",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 904,
    image: "/menu/just/sprite.jpg",
    title: "Sprite",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 905,
    image: "/menu/just/photo.jpg",
    title: "Tonik",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 906,
    image: "/menu/just/photo.jpg",
    title: "Soda",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 907,
    image: "/menu/just/photo.jpg",
    title: "Pink soda",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 909,
    image: "/menu/just/photo.jpg",
    title: "Red Bull 355ml",
    price: "6",
    category: "Refreshments",
    ingredients: "",
  },
  {
    id: 1001,
    image: "/menu/just/beer_amstel.jpg",
    title: "Amstel",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1002,
    image: "/menu/just/photo.jpg",
    title: "Amstel dark",
    price: "7",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1003,
    image: "/menu/just/photo.jpg",
    title: "Amstel radler",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1004,
    image: "/menu/just/photo.jpg",
    title: "Amstel free",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1005,
    image: "/menu/just/beer_heineken.jpg",
    title: "Heineken",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1006,
    image: "/menu/just/beer_mythos.jpg",
    title: "Mythos",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1007,
    image: "/menu/just/photo.jpg",
    title: "Stella Artois",
    price: "7",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1008,
    image: "/menu/just/photo.jpg",
    title: "Sol",
    price: "7",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1009,
    image: "/menu/just/photo.jpg",
    title: "Fisher",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1010,
    image: "/menu/just/photo.jpg",
    title: "MC farland",
    price: "8",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1011,
    image: "/menu/just/photo.jpg",
    title: "Krusovice",
    price: "6,5",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1012,
    image: "/menu/just/photo.jpg",
    title: "Erdinger",
    price: "7",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1013,
    image: "/menu/just/photo.jpg",
    title: "Milokleftis apple",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1014,
    image: "/menu/just/photo.jpg",
    title: "Milokleftis cherry",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1015,
    image: "/menu/just/beer_draft_small.jpg",
    title: "Draft beer 300ml",
    price: "6",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1016,
    image: "/menu/just/beer_draft.jpg",
    title: "Draft beer 500ml",
    price: "6,5",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1017,
    image: "/menu/just/plomari_ouzo_200ml.jpg",
    title: "Ouzo Plomari 200ml",
    price: "9,5",
    category: "Beer",
    ingredients: "",
  },
  {
    id: 1101,
    image: "/menu/just/mojito.jpg",
    title: "Mojito",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1102,
    image: "/menu/just/coctailes.jpg",
    title: "Mojito strawberry",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1103,
    image: "/menu/just/coctailes.jpg",
    title: "Mojito blue",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1104,
    image: "/menu/just/coctailes.jpg",
    title: "Mojito free",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1105,
    image: "/menu/just/coctailes.jpg",
    title: "Caipirinha",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1106,
    image: "/menu/just/coctailes.jpg",
    title: "Cosmopolitan",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1107,
    image: "/menu/just/coctailes.jpg",
    title: "Cuba libre",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1108,
    image: "/menu/just/coctailes.jpg",
    title: "Daquiri",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1109,
    image: "/menu/just/coctailes.jpg",
    title: "Daquiri strawberry",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1110,
    image: "/menu/just/coctailes.jpg",
    title: "Pina colada",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1111,
    image: "/menu/just/coctailes.jpg",
    title: "Sex on the beach",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1112,
    image: "/menu/just/coctailes.jpg",
    title: "Tequila sunrise",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1113,
    image: "/menu/just/coctailes.jpg",
    title: "Watermelon",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1114,
    image: "/menu/just/coctailes.jpg",
    title: "Blue lagoon",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1115,
    image: "/menu/just/coctailes.jpg",
    title: "Margarita",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1116,
    image: "/menu/just/coctailes.jpg",
    title: "Blue hawaian",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1117,
    image: "/menu/just/coctailes.jpg",
    title: "Aperol Spritz",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1118,
    image: "/menu/just/coctailes.jpg",
    title: "Long island",
    price: "9,5",
    category: "Coocktailes",
    ingredients: "",
  },
  {
    id: 1201,
    image: "/menu/just/photo.jpg",
    title: "Mosxofilero dry white wine",
    price: "6",
    category: "Wines-Jin-Rum",
    ingredients: "187ml",
  },
  {
    id: 1202,
    image: "/menu/just/photo.jpg",
    title: "Mosxofilero dry white wine",
    price: "30",
    category: "Wines-Jin-Rum",
    ingredients: "750ml",
  },
  {
    id: 1203,
    image: "/menu/just/photo.jpg",
    title: "Caramelo semi sweet white wine",
    price: "6",
    category: "Wines-Jin-Rum",
    ingredients: "187ml",
  },
  {
    id: 1204,
    image: "/menu/just/photo.jpg",
    title: "Caramelo semi sweet white wine",
    price: "30",
    category: "Wines-Jin-Rum",
    ingredients: "750ml",
  },
  {
    id: 1205,
    image: "/menu/just/photo.jpg",
    title: "Caramelo semi sweet red wine",
    price: "6",
    category: "Wines-Jin-Rum",
    ingredients: "187ml",
  },
  {
    id: 1206,
    image: "/menu/just/photo.jpg",
    title: "Caramelo semi sweet red wine",
    price: "30",
    category: "Wines-Jin-Rum",
    ingredients: "750ml",
  },
  {
    id: 1207,
    image: "/menu/just/photo.jpg",
    title: "Caramelo rose wine",
    price: "6",
    category: "Wines-Jin-Rum",
    ingredients: "187ml",
  },
  {
    id: 1208,
    image: "/menu/just/photo.jpg",
    title: "Caramelo rose wine",
    price: "30",
    category: "Wines-Jin-Rum",
    ingredients: "750ml",
  },
  {
    id: 1209,
    image: "/menu/just/photo.jpg",
    title: "Sangria white wine",
    price: "6",
    category: "Wines-Jin-Rum",
    ingredients: "187ml",
  },
  {
    id: 1210,
    image: "/menu/just/photo.jpg",
    title: "Sangria red wine",
    price: "6",
    category: "Wines-Jin-Rum",
    ingredients: "187ml",
  },
  {
    id: 1211,
    image: "/menu/just/photo.jpg",
    title: "Asti martini champagne",
    price: "12",
    category: "Wines-Jin-Rum",
    ingredients: "200ml",
  },
  {
    id: 1212,
    image: "/menu/just/photo.jpg",
    title: "Asti martini champagne",
    price: "60",
    category: "Wines-Jin-Rum",
    ingredients: "750ml",
  },
  {
    id: 1213,
    image: "/menu/just/photo.jpg",
    title: "Моеt champagne",
    price: "160",
    category: "Wines-Jin-Rum",
    ingredients: "750ml",
  },
  {
    id: 1214,
    image: "/menu/just/photo.jpg",
    title:
      "Whisky simple (Dewars, Johnnie, Ballantines, Haig,Famos, J&B, Cutty Sark, Grants)",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1215,
    image: "/menu/just/photo.jpg",
    title:
      "Whisky simple (Dewars, Johnnie, Ballantines, Haig,Famos, J&B, Cutty Sark, Grants)",
    price: "80",
    category: "Wines-Jin-Rum",
    ingredients: "700ml",
  },
  {
    id: 1216,
    image: "/menu/just/photo.jpg",
    title:
      "Whisky special (Jack Daniels, Dimple, Chivas, Cardu, Johnnie Black)",
    price: "8,5",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1217,
    image: "/menu/just/photo.jpg",
    title:
      "Whisky special (Jack Daniels, Dimple, Chivas, Cardu, Johnnie Black)",
    price: "95",
    category: "Wines-Jin-Rum",
    ingredients: "700ml",
  },
  {
    id: 1218,
    image: "/menu/just/photo.jpg",
    title: "Vodka (Absolut, Stolichnaya, Belvedere, North, Ursus)",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1219,
    image: "/menu/just/photo.jpg",
    title: "Jin Gordons",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1220,
    image: "/menu/just/photo.jpg",
    title: "Hendricks",
    price: "10",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1221,
    image: "/menu/just/photo.jpg",
    title: "Bombay",
    price: "10",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1222,
    image: "/menu/just/photo.jpg",
    title: "Tanquerey",
    price: "9",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1223,
    image: "/menu/just/photo.jpg",
    title: "Bacardi",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1224,
    image: "/menu/just/photo.jpg",
    title: "Metaxa 3*",
    price: "7",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1225,
    image: "/menu/just/photo.jpg",
    title: "Metaxa 5*",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1226,
    image: "/menu/just/photo.jpg",
    title: "Metaxa 7*",
    price: "9",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1227,
    image: "/menu/just/photo.jpg",
    title: "Tequila Cuervo yellow",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1228,
    image: "/menu/just/photo.jpg",
    title: "Tequila Cuervo white",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1229,
    image: "/menu/just/photo.jpg",
    title: "Martini (Bianco, Rosso, Rossato, Dry)",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1230,
    image: "/menu/just/photo.jpg",
    title: "Havana club (White-Black)",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1231,
    image: "/menu/just/photo.jpg",
    title: "Campari",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
  {
    id: 1232,
    image: "/menu/just/photo.jpg",
    title: "Malibu",
    price: "8",
    category: "Wines-Jin-Rum",
    ingredients: "60ml",
  },
];
