export const ro = [
  {
    menuNumber: 101,
    title: "Salată Grecească",
    category: "Salate",
    ingredients: "",
  },
  {
    menuNumber: 102,
    title: "Salată Caesar",
    category: "Salate",
    ingredients: "",
  },
  {
    menuNumber: 103,
    title: "Salată Specială",
    category: "Salate",
    ingredients: "",
  },
  {
    menuNumber: 104,
    title: "Salată de ton",
    category: "Salate",
    ingredients: "",
  },
  {
    menuNumber: 105,
    title: "Salată de fructe",
    category: "Salate",
    ingredients: "",
  },
  {
    menuNumber: 201,
    title: "Hamburger",
    category: "Hamburgers",
    ingredients: "Cu roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 202,
    title: "Cheeseburger",
    category: "Hamburgers",
    ingredients: "Cu roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 203,
    title: "Brânză și bacon",
    category: "Hamburgers",
    ingredients: "Cu roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 204,
    title: "Burger de pui",
    category: "Hamburgers",
    ingredients: "Cu roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 205,
    title: "Hamburger cu ou și bacon",
    category: "Hamburgers",
    ingredients:
      "Cu cremă proaspătă de brânză, roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 206,
    title: "Hamburger cu brânză și pui",
    category: "Hamburgers",
    ingredients:
      "Cu ceapă caramelizată și roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 301,
    title: "Cheeseburger + Cartofi prăjiți",
    category: "Meniu Hamburgers",
    ingredients: "Cu roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 302,
    title: "Brânză și bacon + Cartofi prăjiți",
    category: "Meniu Hamburgers",
    ingredients: "Cu roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 303,
    title: "Burger de pui + Cartofi prăjiți",
    category: "Meniu Hamburgers",
    ingredients: "Cu roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 304,
    title: "Ou și bacon + Cartofi prăjiți",
    category: "Meniu Hamburgers",
    ingredients:
      "Cu cremă proaspătă de brânză, roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 305,
    title: "Brânză și pui + Cartofi prăjiți",
    category: "Meniu Hamburgers",
    ingredients:
      "Cu ceapă caramelizată și roșii, salată, castraveți, maioneză, ketchup",
  },
  {
    menuNumber: 401,
    title: "Sandwich cu curcan și brânză Cheddar",
    category: "Sandvișuri",
    ingredients: "",
  },
  {
    menuNumber: 402,
    title: "Club sandwich",
    category: "Sandvișuri",
    ingredients: "",
  },
  {
    menuNumber: 403,
    title: "Sandviș cu pui",
    category: "Sandvișuri",
    ingredients: "",
  },
  {
    menuNumber: 404,
    title: "Porție de ćevapčići cu pâine pita și sos tzatziki",
    category: "Sandvișuri",
    ingredients: "",
  },
  {
    menuNumber: 405,
    title: "Porție de pui cu pâine pita",
    category: "Sandvișuri",
    ingredients: "",
  },
  {
    menuNumber: 406,
    title: "Focaccia vegetariană (360g)",
    category: "Sandvișuri",
    ingredients: "Cu cartofi prăjiți și sos cocktail",
  },
  {
    menuNumber: 407,
    title: "Focaccia cu mozzarella (360g)",
    category: "Sandvișuri",
    ingredients: "Cu cartofi prăjiți și sos cocktail",
  },
  {
    menuNumber: 408,
    title: "Focaccia cu ćevapčići de pui (360g)",
    category: "Sandvișuri",
    ingredients: "Cu cartofi prăjiți și sos cocktail",
  },
  {
    menuNumber: 409,
    title: "Focaccia cu ćevapčići de porc (360g)",
    category: "Sandvișuri",
    ingredients: "Cu cartofi prăjiți și sos cocktail",
  },
  {
    menuNumber: 410,
    title: "Focaccia cu file de pui (360g)",
    category: "Sandvișuri",
    ingredients: "Cu cartofi prăjiți și sos cocktail",
  },
  {
    menuNumber: 411,
    title: "Focaccia cu paste aurii (360g)",
    category: "Sandvișuri",
    ingredients: "Cu cartofi prăjiți și sos cocktail",
  },
  {
    menuNumber: 412,
    title: "Focaccia cu 4 feluri de brânză (360g)",
    category: "Sandvișuri",
    ingredients: "Cu cartofi prăjiți și sos cocktail",
  },
  {
    menuNumber: 413,
    title: "Cartofi prăjiți",
    category: "Sandvișuri",
    ingredients: "",
  },
  {
    menuNumber: 414,
    title: "Cartofi prăjiți",
    category: "Sandvișuri",
    ingredients:
      "Cu bacon, parmezan ras, sos cheddar și cremă proaspătă de brânză",
  },
  {
    menuNumber: 501,
    title: "Clătite cu ciocolată",
    category: "Deserturi",
    ingredients: "Cu banană și biscuiți mărunțiți",
  },
  {
    menuNumber: 502,
    title: "Clătite",
    category: "Deserturi",
    ingredients: "Cu miere, iaurt și nuci tocate mărunt",
  },
  {
    menuNumber: 503,
    title: "Clătite",
    category: "Deserturi",
    ingredients:
      "Cu șuncă și brânză, bacon dublu, ouă și sos de cremă proaspătă de brânză",
  },
  {
    menuNumber: 504,
    title: "Vafe de ciocolată",
    category: "Deserturi",
    ingredients: "Cu nuci tocate mărunt, vanilie și înghețată de ciocolată",
  },
  {
    menuNumber: 505,
    title: "Vafe Oreo",
    category: "Deserturi",
    ingredients:
      "Cu pralină, biscuiți Oreo mărunțiți și 2 bile de înghețată Oreo",
  },
  {
    menuNumber: 506,
    title: "Vafe de ciocolată",
    category: "Deserturi",
    ingredients:
      "Cu fructe proaspete de sezon și 2 bile de sorbet de căpșuni și mango",
  },
  {
    menuNumber: 507,
    title: "Soufflé de ciocolată",
    category: "Deserturi",
    ingredients: "Cu înghețată de vanilie",
  },
  {
    menuNumber: 508,
    title: "Brownie de ciocolată",
    category: "Deserturi",
    ingredients: "Cu nuci, sirop de ciocolată și înghețată de vanilie",
  },
  {
    menuNumber: 601,
    title: "Buena Ferrera",
    category: "Chocolate",
    ingredients: "Armonie perfectă de biscuit crocant și lapte de ciocolată",
  },
  {
    menuNumber: 602,
    title: "Capricciosa",
    category: "Chocolate",
    ingredients: "Gust incredibil de ciocolată",
  },
  {
    menuNumber: 603,
    title: "Oreo",
    category: "Chocolate",
    ingredients: "Ciocolată albă cu biscuiți Oreo mărunțiți",
  },
  {
    menuNumber: 604,
    title: "Salt",
    category: "Chocolate",
    ingredients:
      "Gust bogat de lapte de ciocolată, cu un strop de sare de mare",
  },
  {
    menuNumber: 605,
    title: "Viena",
    category: "Chocolate",
    ingredients:
      "Rețetă autentică aromatică de ciocolată cu 40% cacao și cremă de lapte, exact ca în Viena",
  },
  {
    menuNumber: 606,
    title: "Clasic",
    category: "Chocolate",
    ingredients:
      "Gust clasic de ciocolată din soiuri tropicale de cacao din Africa",
  },
  {
    menuNumber: 607,
    title: "Fără zahăr",
    category: "Chocolate",
    ingredients: "O altă versiune a ciocolatei clasice fără zahăr, cu stevia",
  },
  {
    menuNumber: 608,
    title: "Amărui Aztec",
    category: "Chocolate",
    ingredients: "Ciocolată amară cu un gust intens și aromă",
  },
  {
    menuNumber: 609,
    title: "Căpșuni",
    category: "Chocolate",
    ingredients: "Ciocolată cu gust de căpșuni și vanilie",
  },
  {
    menuNumber: 610,
    title: "Banana",
    category: "Chocolate",
    ingredients: "Ciocolată cu gust de banană",
  },
  {
    menuNumber: 611,
    title: "Cocos",
    category: "Chocolate",
    ingredients: "Ciocolată cu gust de lapte de cocos",
  },
  {
    menuNumber: 612,
    title: "Cafelată",
    category: "Chocolate",
    ingredients: "Ciocolată cu un gust minunat de cafea-avelă și lapte spumos",
  },
  {
    menuNumber: 701,
    title: "Cafea grecească",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 702,
    title: "Frapé",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 703,
    title: "Frapé cu cuburi de gheață",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 704,
    title: "Espresso",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 705,
    title: "Cappuccino",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 706,
    title: "Cappuccino rece",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 707,
    title: "Espresso rece",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 708,
    title: "Ciocolată rece",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 709,
    title: "Ciocolată caldă",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 710,
    title: "Milkshake",
    category: "Cafea",
    ingredients: "Vanilie-ciocolată, banană, căpșuni",
  },
  {
    menuNumber: 711,
    title: "Ceai cald",
    category: "Cafea",
    ingredients: "Verde, negru",
  },
  {
    menuNumber: 712,
    title: "Mochaccino",
    category: "Cafea",
    ingredients: "",
  },
  {
    menuNumber: 801,
    title: "Portocală",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 802,
    title: "Banană",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 803,
    title: "Cireșe",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 804,
    title: "Piersică",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 805,
    title: "Ananas",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 806,
    title: "Măr",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 807,
    title: "Zmeură",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 808,
    title: "Suc proaspăt de portocale",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 809,
    title: "Limonadă casnică",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 810,
    title: "Portocală proaspătă cu grapefruit",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 811,
    title: "Portocală proaspătă cu lămâie",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 812,
    title: "Ayran",
    category: "Sucuri",
    ingredients: "Verde, lămâie, piersică",
  },
  {
    menuNumber: 813,
    title: "Suc Granita",
    category: "Sucuri",
    ingredients: "",
  },
  {
    menuNumber: 901,
    title: "Coca Cola",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 902,
    title: "Fanta",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 903,
    title: "Limonadă",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 904,
    title: "Sprite",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 905,
    title: "Apă tonică",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 906,
    title: "Sodă",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 907,
    title: "Rodachin",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 909,
    title: "Red Bull 355ml",
    category: "Băuturi răcoritoare",
    ingredients: "",
  },
  {
    menuNumber: 1001,
    title: "Amstel",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1002,
    title: "Amstel Dark",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1003,
    title: "Amstel Radler",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1004,
    title: "Amstel Non-Alcoholic",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1005,
    title: "Heineken",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1006,
    title: "Mythos",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1007,
    title: "Stella Artois",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1008,
    title: "Sol",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1009,
    title: "Fischer",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1010,
    title: "McFarland",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1011,
    title: "Krusovice",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1012,
    title: "Erdinger",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1013,
    title: "Apple Thief Apple",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1014,
    title: "Apple Thief Cherry",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1015,
    title: "Draft beer 300ml",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1016,
    title: "Draft beer 500ml",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1017,
    title: "Ouzo of Plomari 200ml",
    category: "Bere",
    ingredients: "",
  },
  {
    menuNumber: 1101,
    title: "Mojito",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1102,
    title: "Mojito with strawberries",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1103,
    title: "Blue Mojito",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1104,
    title: "Non-alcoholic Mojito",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1105,
    title: "Caipirinha",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1106,
    title: "Cosmopolitan",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1107,
    title: "Cuba Libre",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1108,
    title: "Daiquiri",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1109,
    title: "Strawberry Daiquiri",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1110,
    title: "Piña Colada",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1111,
    title: "Sex on the Beach",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1112,
    title: "Tequila Sunrise",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1113,
    title: "Watermelon",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1114,
    title: "Blue Lagoon",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1115,
    title: "Margarita",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1116,
    title: "Blue Hawaiian",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1117,
    title: "Aperol Spritz",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1118,
    title: "Long Island",
    category: "Cocktails",
    ingredients: "",
  },
  {
    menuNumber: 1201,
    title: "Moschofilero Dry White Wine",
    category: "Wines-Gin-Rum",
    ingredients: "187ml",
  },
  {
    menuNumber: 1202,
    title: "Moschofilero Dry White Wine",
    category: "Wines-Gin-Rum",
    ingredients: "750ml",
  },
  {
    menuNumber: 1203,
    title: "Caramelo Semi-Sweet White Wine",
    category: "Wines-Gin-Rum",
    ingredients: "187ml",
  },
  {
    menuNumber: 1204,
    title: "Caramelo Semi-Sweet White Wine",
    category: "Wines-Gin-Rum",
    ingredients: "750ml",
  },
  {
    menuNumber: 1205,
    title: "Caramelo Semi-Sweet Red Wine",
    category: "Wines-Gin-Rum",
    ingredients: "187ml",
  },
  {
    menuNumber: 1206,
    title: "Caramelo Semi-Dry Red Wine",
    category: "Wines-Gin-Rum",
    ingredients: "750ml",
  },
  {
    menuNumber: 1207,
    title: "Caramelo Rosé Wine",
    category: "Wines-Gin-Rum",
    ingredients: "187ml",
  },
  {
    menuNumber: 1208,
    title: "Caramelo Rosé Wine",
    category: "Wines-Gin-Rum",
    ingredients: "750ml",
  },
  {
    menuNumber: 1209,
    title: "White Wine Sangria",
    category: "Wines-Gin-Rum",
    ingredients: "187ml",
  },
  {
    menuNumber: 1210,
    title: "Red Wine Sangria",
    category: "Wines-Gin-Rum",
    ingredients: "187ml",
  },
  {
    menuNumber: 1211,
    title: "Sparkling Wine Asti Martini",
    category: "Wines-Gin-Rum",
    ingredients: "200ml",
  },
  {
    menuNumber: 1212,
    title: "Sparkling Wine Asti Martini",
    category: "Wines-Gin-Rum",
    ingredients: "750ml",
  },
  {
    menuNumber: 1213,
    title: "Sparkling Wine Moët",
    category: "Wines-Gin-Rum",
    ingredients: "750ml",
  },
  {
    menuNumber: 1214,
    title:
      "Plain Whisky (Dewar's, Johnnie Walker, Ballantine's, Haig, Famous Grouse, J&B, Cutty Sark, Grant's)",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1215,
    title:
      "Plain Whisky (Dewar's, Johnnie Walker, Ballantine's, Haig, Famous Grouse, J&B, Cutty Sark, Grant's)",
    category: "Wines-Gin-Rum",
    ingredients: "700ml",
  },
  {
    menuNumber: 1216,
    title:
      "Special Whisky (Jack Daniel's, Dimple, Chivas, Cardhu, Johnnie Walker Black)",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1217,
    title:
      "Special Whisky (Jack Daniel's, Dimple, Chivas, Cardhu, Johnnie Walker Black)",
    category: "Wines-Gin-Rum",
    ingredients: "700ml",
  },
  {
    menuNumber: 1218,
    title: "Vodka (Absolut, Stolichnaya, Belvedere, Norr, Ursus)",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1219,
    title: "Gin Gordon's",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1220,
    title: "Hendricks",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1221,
    title: "Bombay",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1222,
    title: "Tanqueray",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1223,
    title: "Bacardi",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1224,
    title: "Metaxa 3*",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1225,
    title: "Metaxa 5*",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1226,
    title: "Metaxa 7*",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1227,
    title: "Tequila Cuervo Gold",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1228,
    title: "Tequila Cuervo Silver",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1229,
    title: "Martini (Bianco, Rosso, Rosato, Dry)",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1230,
    title: "Havana Club (White-Black)",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1231,
    title: "Campari",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1232,
    title: "Malibu",
    category: "Wines-Gin-Rum",
    ingredients: "60ml",
  },
  {
    menuNumber: 1301,
    title: "Smoothie 01",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Strawberry, peach, banana",
  },
  {
    menuNumber: 1302,
    title: "Smoothie 02",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Strawberry, mango, melon",
  },
  {
    menuNumber: 1303,
    title: "Smoothie 03",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Pear, mango, pineapple",
  },
  {
    menuNumber: 1304,
    title: "Smoothie 04",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Raspberry, dark raspberry, banana",
  },
  {
    menuNumber: 1305,
    title: "Smoothie 05",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Passion fruit, peach, mango",
  },
  {
    menuNumber: 1306,
    title: "Smoothie 06",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Raspberry, mango, apple, raspberry",
  },
  {
    menuNumber: 1307,
    title: "Smoothie 07",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Lemon, carrot, apple, spinach, ginger",
  },
  {
    menuNumber: 1308,
    title: "Smoothie 08",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Avocado, lettuce, lemon zest, banana",
  },
  {
    menuNumber: 1309,
    title: "Smoothie 09",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Dragon fruit, lemon, banana, mango",
  },
  {
    menuNumber: 1310,
    title: "Smoothie 10",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Ice cream, pineapple, mango, banana",
  },
  {
    menuNumber: 1311,
    title: "Smoothie 11",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Biscuit, vegan cream",
  },
  {
    menuNumber: 1312,
    title: "Smoothie 12",
    category: "Smoothie",
    subCategory: null,
    ingredients: "Ice cream, banana, strawberry",
  },
  {
    menuNumber: 207,
    title: "Burger cu carne de porc giros",
    category: "Hamburgers",
    ingredients:
      "Cu pâine brioche, roșii, ceapă, salată verde, ketchup, muștar și carne de porc giros cu cartofi",
  },
  {
    menuNumber: 208,
    title: "Burger cu pui giros",
    category: "Hamburgers",
    ingredients:
      "Cu pâine brioche, roșii, ceapă, salată verde, ketchup, muștar și pui giros cu cartofi",
  },
  {
    menuNumber: 415,
    title: "Club sandwich cu carne de porc giros",
    category: "Sandvișuri",
    ingredients: "Cu pită, tzatziki, roșii, ceapă, salată verde",
  },
  {
    menuNumber: 416,
    title: "Club sandwich cu pui giros",
    category: "Sandvișuri",
    ingredients: "Cu pită, tzatziki, roșii, ceapă, salată verde",
  },
];
