export const ru = [
  {
    menuNumber: 101,
    title: "Греческий салат",
    category: "Салаты",
    ingredients: "",
  },
  {
    menuNumber: 102,
    title: "Салат Цезарь",
    category: "Салаты",
    ingredients: "",
  },
  {
    menuNumber: 103,
    title: "Специальный салат",
    category: "Салаты",
    ingredients: "",
  },
  {
    menuNumber: 104,
    title: "Салат с тунцом",
    category: "Салаты",
    ingredients: "",
  },
  {
    menuNumber: 105,
    title: "Фруктовый салат",
    category: "Салаты",
    ingredients: "",
  },
  {
    menuNumber: 201,
    title: "Гамбургер",
    category: "Гамбургеры",
    ingredients: "С помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 202,
    title: "Чизбургер",
    category: "Гамбургеры",
    ingredients: "С помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 203,
    title: "Гамбургер с сыром и беконом",
    category: "Гамбургеры",
    ingredients: "С помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 204,
    title: "Куриный бургер",
    category: "Гамбургеры",
    ingredients: "С помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 205,
    title: "Гамбургер с яйцом и беконом",
    category: "Гамбургеры",
    ingredients:
      "Со свежим сливочным сыром, помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 206,
    title: "Гамбургер с сыром и курицей",
    category: "Гамбургеры",
    ingredients:
      "С карамелизированным луком и помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 301,
    title: "Чизбургер + Картофель фри",
    category: "Гамбургер-меню",
    ingredients: "С помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 302,
    title: "Гамбургер с сыром и беконом + Картофель фри",
    category: "Гамбургер-меню",
    ingredients: "С помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 303,
    title: "Куриный бургер + Картофель фри",
    category: "Гамбургер-меню",
    ingredients: "С помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 304,
    title: "Гамбургер с яйцом и беконом + Картофель фри",
    category: "Гамбургер-меню",
    ingredients:
      "Со свежим сливочным сыром, помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 305,
    title: "Гамбургер с сыром и курицей + Картофель фри",
    category: "Гамбургер-меню",
    ingredients:
      "С карамелизированным луком и помидорами, салатом, огурцами, майонезом, кетчупом",
  },
  {
    menuNumber: 401,
    title: "Сэндвич с индейкой и сыром чеддер",
    category: "Сэндвичи",
    ingredients: "",
  },
  {
    menuNumber: 402,
    title: "Клубный сэндвич",
    category: "Сэндвичи",
    ingredients: "",
  },
  {
    menuNumber: 403,
    title: "Куриный сэндвич",
    category: "Сэндвичи",
    ingredients: "",
  },
  {
    menuNumber: 404,
    title: "Порция чева́пчичи с питой и соусом дзадзики",
    category: "Сэндвичи",
    ingredients: "",
  },
  {
    menuNumber: 405,
    title: "Порция курицы с питой",
    category: "Сэндвичи",
    ingredients: "",
  },
  {
    menuNumber: 406,
    title: "Вегетарианская фокачча (360г)",
    category: "Сэндвичи",
    ingredients: "С жареным картофелем и коктейльным соусом",
  },
  {
    menuNumber: 407,
    title: "Фокачча с моцареллой (360г)",
    category: "Сэндвичи",
    ingredients: "С жареным картофелем и коктейльным соусом",
  },
  {
    menuNumber: 408,
    title: "Фокачча с куриными чева́пчичи (360г)",
    category: "Сэндвичи",
    ingredients: "С жареным картофелем и коктейльным соусом",
  },
  {
    menuNumber: 409,
    title: "Фокачча с свиными чева́пчичи (360г)",
    category: "Сэндвичи",
    ingredients: "С жареным картофелем и коктейльным соусом",
  },
  {
    menuNumber: 410,
    title: "Фокачча с куриным филе (360г)",
    category: "Сэндвичи",
    ingredients: "С жареным картофелем и коктейльным соусом",
  },
  {
    menuNumber: 411,
    title: "Фокачча золотые кусочки (360г)",
    category: "Сэндвичи",
    ingredients: "С жареным картофелем и коктейльным соусом",
  },
  {
    menuNumber: 412,
    title: "Фокачча с четырьмя видами сыра (360г)",
    category: "Сэндвичи",
    ingredients: "С жареным картофелем и коктейльным соусом",
  },
  {
    menuNumber: 413,
    title: "Жареный картофель",
    category: "Сэндвичи",
    ingredients: "",
  },
  {
    menuNumber: 414,
    title: "Жареный картофель +",
    category: "Сэндвичи",
    ingredients:
      "С беконом, тертым пармезаном, чеддерным соусом и свежим сливочным сыром",
  },
  {
    menuNumber: 501,
    title: "Шоколадные блинчики",
    category: "Десерты",
    ingredients: "С бананом и измельченными печеньями",
  },
  {
    menuNumber: 502,
    title: "Блинчики",
    category: "Десерты",
    ingredients: "С медом, йогуртом и мелко нарезанными орехами",
  },
  {
    menuNumber: 503,
    title: "Блинчики",
    category: "Десерты",
    ingredients:
      "С ветчиной и сыром, двойным беконом, яйцами и соусом из свежего сливочного сыра",
  },
  {
    menuNumber: 504,
    title: "Шоколадные вафли",
    category: "Десерты",
    ingredients: "С мелко нарезанными орехами, ванилью и шоколадным мороженым",
  },
  {
    menuNumber: 505,
    title: "Вафли Oreo",
    category: "Десерты",
    ingredients:
      "С пралине, измельченными печеньями Oreo и 2 шариками мороженого Oreo",
  },
  {
    menuNumber: 506,
    title: "Шоколадные вафли",
    category: "Десерты",
    ingredients:
      "С свежими сезонными фруктами и 2 шариками сорбета клубники и манго",
  },
  {
    menuNumber: 507,
    title: "Шоколадный суфле",
    category: "Десерты",
    ingredients: "С ванильным мороженым",
  },
  {
    menuNumber: 508,
    title: "Шоколадное брауни",
    category: "Десерты",
    ingredients: "С орехами, шоколадным сиропом и ванильным мороженым",
  },
  {
    menuNumber: 601,
    title: "Buena Ferrera",
    category: "Блендиссимо",
    ingredients: "Идеальное сочетание хрустящего печенья и шоколадного молока",
  },
  {
    menuNumber: 602,
    title: "Capricciosa",
    category: "Блендиссимо",
    ingredients: "Невероятный вкус шоколада",
  },
  {
    menuNumber: 603,
    title: "Oreo",
    category: "Блендиссимо",
    ingredients: "Белый шоколад с измельченными печеньями Oreo",
  },
  {
    menuNumber: 604,
    title: "Salt",
    category: "Блендиссимо",
    ingredients: "Насыщенный вкус шоколадного молока с присыпкой морской соли",
  },
  {
    menuNumber: 605,
    title: "Вена",
    category: "Блендиссимо",
    ingredients:
      "Аутентичный ароматный рецепт шоколада с 40% какао и сливочным кремом, как в Вене",
  },
  {
    menuNumber: 606,
    title: "Классика",
    category: "Блендиссимо",
    ingredients:
      "Классический вкус шоколада из тропических Африканских сортов какао",
  },
  {
    menuNumber: 607,
    title: "Без сахара",
    category: "Блендиссимо",
    ingredients: "Вариант классического шоколада без сахара, со стевией",
  },
  {
    menuNumber: 608,
    title: "Горький Ацтек",
    category: "Блендиссимо",
    ingredients: "Горький шоколад с интенсивным вкусом и ароматом",
  },
  {
    menuNumber: 609,
    title: "Клубника",
    category: "Блендиссимо",
    ingredients: "Шоколад со вкусом клубники и ванили",
  },
  {
    menuNumber: 610,
    title: "Банан",
    category: "Блендиссимо",
    ingredients: "Шоколад со вкусом банана",
  },
  {
    menuNumber: 611,
    title: "Кокос",
    category: "Блендиссимо",
    ingredients: "Шоколад со вкусом кокосового молока",
  },
  {
    menuNumber: 612,
    title: "Cafelata",
    category: "Блендиссимо",
    ingredients:
      "Шоколад с чудесным мягким вкусом кофе-фундука и вспененным молоком",
  },
  {
    menuNumber: 701,
    title: "Греческий кофе",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 702,
    title: "Фраппе",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 703,
    title: "Фраппе с мороженым",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 704,
    title: "Эспрессо",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 705,
    title: "Капучино",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 706,
    title: "Холодный капучино",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 707,
    title: "Холодный эспрессо",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 708,
    title: "Холодный шоколад",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 709,
    title: "Горячий шоколад",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 710,
    title: "Молочный коктейль",
    category: "Кофе",
    ingredients: "Ваниль-шоколад, банан, клубника",
  },
  {
    menuNumber: 711,
    title: "Горячий чай",
    category: "Кофе",
    ingredients: "Зеленый, черный",
  },
  {
    menuNumber: 712,
    title: "Моккачино",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 801,
    title: "Апельсин",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 802,
    title: "Банан",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 803,
    title: "Вишня",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 804,
    title: "Персик",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 805,
    title: "Ананас",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 806,
    title: "Яблоко",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 807,
    title: "Малина",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 808,
    title: "Свежевыжатый сок апельсина",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 809,
    title: "Домашний лимонад",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 810,
    title: " Свежевыжатый сок апельсина с грейпфрутом",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 811,
    title: " Свежевыжатый сок апельсина с лимоном",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 812,
    title: "Холодный чай",
    category: "Соки",
    ingredients: "Зеленый, лимон, персик",
  },
  {
    menuNumber: 813,
    title: "Гранита",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 901,
    title: "Кока-Кола",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 902,
    title: "Фанта",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 903,
    title: "Лимонад",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 904,
    title: "Спрайт",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 905,
    title: "Тоник",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 906,
    title: "Сода",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 907,
    title: "Пинк Грейпфрут Сода",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 909,
    title: "Red Bull 355мл",
    category: "Безалкогольные напитки",
    ingredients: "",
  },
  {
    menuNumber: 1001,
    title: "Amstel",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1002,
    title: "Amstel Dark",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1003,
    title: "Amstel Radler",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1004,
    title: "Amstel Безалкогольное",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1005,
    title: "Heineken",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1006,
    title: "Mythos",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1007,
    title: "Stella Artois",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1008,
    title: "Sol",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1009,
    title: "Fischer",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1010,
    title: "McFarland",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1011,
    title: "Krusovice",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1012,
    title: "Erdinger",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1013,
    title: "Яблочный милоклефтис",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1014,
    title: "Вишнеый милоклефтис",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1015,
    title: "Пиво на разлив 300мл",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1016,
    title: "Пиво на разлив 500мл",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1017,
    title: "Оузо из Пломари 200мл",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1101,
    title: "Мохито",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1102,
    title: "Мохито с клубникой",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1103,
    title: "Голубой Мохито",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1104,
    title: "Безалкогольный Мохито",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1105,
    title: "Кайпиринья",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1106,
    title: "Космополитан",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1107,
    title: "Куба Либре",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1108,
    title: "Дайкири",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1109,
    title: "Клубничный Дайкири",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1110,
    title: "Пина Колада",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1111,
    title: "Секс на пляже",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1112,
    title: "Текила Санрайз",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1113,
    title: "Арбузный",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1114,
    title: "Голубая Лагуна",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1115,
    title: "Маргарита",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1116,
    title: "Голубой Гавайец",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1117,
    title: "Апероль Шприц",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1118,
    title: "Лонг Айленд",
    category: "Коктейли",
    ingredients: "",
  },
  {
    menuNumber: 1201,
    title: "Мосхофилеро Сухое Белое Вино",
    category: "Вина-Джин-Ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1202,
    title: "Мосхофилеро Сухое Белое Вино",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1203,
    title: "Карамело Полусладкое Белое Вино",
    category: "Вина-Джин-Ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1204,
    title: "Карамело Полусладкое Белое Вино",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1205,
    title: "Карамело Полусладкое Красное Вино",
    category: "Вина-Джин-Ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1206,
    title: "Карамело Полусладкое Красное Вино",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1207,
    title: "Карамело Розовое Вино",
    category: "Вина-Джин-Ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1208,
    title: "Карамело Розовое Вино",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1209,
    title: "Сангрия из Белого Вина",
    category: "Вина-Джин-Ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1210,
    title: "Сангрия из Красного Вина",
    category: "Вина-Джин-Ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1211,
    title: "Шампанское Асти Мартини",
    category: "Вина-Джин-Ром",
    ingredients: "200мл",
  },
  {
    menuNumber: 1212,
    title: "Шампанские Вино Асти Мартини",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1213,
    title: "Шампанское Moet",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1214,
    title:
      "Виски (Dewar's, Johnnie Walker, Ballantine's, Haig, Famous Grouse, J&B, Cutty Sark, Grant's)",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1215,
    title:
      "Виски (Dewar's, Johnnie Walker, Ballantine's, Haig, Famous Grouse, J&B, Cutty Sark, Grant's)",
    category: "Вина-Джин-Ром",
    ingredients: "700мл",
  },
  {
    menuNumber: 1216,
    title:
      "Специальный виски (Jack Daniel's, Dimple, Chivas, Cardhu, Johnnie Walker Black)",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1217,
    title:
      "Специальный виски (Jack Daniel's, Dimple, Chivas, Cardhu, Johnnie Walker Black)",
    category: "Вина-Джин-Ром",
    ingredients: "700мл",
  },
  {
    menuNumber: 1218,
    title: "Водка (Absolut, Stolichnaya, Belvedere, Norr, Ursus)",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1219,
    title: "Джин Gordon's",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1220,
    title: "Hendricks",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1221,
    title: "Bombay",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1222,
    title: "Tanqueray",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1223,
    title: "Bacardi",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1224,
    title: "Metaxa 3*",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1225,
    title: "Metaxa 5*",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1226,
    title: "Metaxa 7*",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1227,
    title: "Текила Cuervo Yellow",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1228,
    title: "Текила Cuervo White",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1229,
    title: "Мартини (Бьянко, Россо, Розато, Сухое)",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1230,
    title: "Havana Club (Белый-Черный)",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1231,
    title: "Кампари",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1232,
    title: "Малибу",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1301,
    title: "Смузи 01",
    category: "Смузи",
    subCategory: null,
    ingredients: "Клубника, персик, банан",
  },
  {
    menuNumber: 1302,
    title: "Смузи 02",
    category: "Смузи",
    subCategory: null,
    ingredients: "Клубника, манго, дыня",
  },
  {
    menuNumber: 1303,
    title: "Смузи 03",
    category: "Смузи",
    subCategory: null,
    ingredients: "Груша, манго, ананас",
  },
  {
    menuNumber: 1304,
    title: "Смузи 04",
    category: "Смузи",
    subCategory: null,
    ingredients: "Малина, темная малина, банан",
  },
  {
    menuNumber: 1305,
    title: "Смузи 05",
    category: "Смузи",
    subCategory: null,
    ingredients: "Маракуйя, персик, манго",
  },
  {
    menuNumber: 1306,
    title: "Смузи 06",
    category: "Смузи",
    subCategory: null,
    ingredients: "Малина, манго, яблоко, малина",
  },
  {
    menuNumber: 1307,
    title: "Смузи 07",
    category: "Смузи",
    subCategory: null,
    ingredients: "Лимон, морковь, яблоко, шпинат, имбирь",
  },
  {
    menuNumber: 1308,
    title: "Смузи 08",
    category: "Смузи",
    subCategory: null,
    ingredients: "Авокадо, салат, лимонная цедра, банан",
  },
  {
    menuNumber: 1309,
    title: "Смузи 09",
    category: "Смузи",
    subCategory: null,
    ingredients: "Драконий фрукт, лимон, банан, манго",
  },
  {
    menuNumber: 1310,
    title: "Смузи 10",
    category: "Смузи",
    subCategory: null,
    ingredients: "Мороженое, ананас, манго, банан",
  },
  {
    menuNumber: 1311,
    title: "Смузи 11",
    category: "Смузи",
    subCategory: null,
    ingredients: "Печенье, веганский крем",
  },
  {
    menuNumber: 1312,
    title: "Смузи 12",
    category: "Смузи",
    subCategory: null,
    ingredients: "Мороженое, банан, клубника",
  },
];
