export const ua = [
  {
    menuNumber: 101,
    title: "Грецький салат",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 102,
    title: "Салат Цезар",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 103,
    title: "Особливий салат",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 104,
    title: "Салат з тунцем",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 105,
    title: "Фруктовий салат",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 201,
    title: "Гамбургер",
    category: "Гамбургери",
    ingredients: "З помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 202,
    title: "Чізбургер",
    category: "Гамбургери",
    ingredients: "З помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 203,
    title: "Сир і бекон",
    category: "Гамбургери",
    ingredients: "З помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 204,
    title: "Курячий гамбургер",
    category: "Гамбургери",
    ingredients: "З помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 205,
    title: "Гамбургер з яйцем і беконом",
    category: "Гамбургери",
    ingredients:
      "З вершковим сиром, помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 206,
    title: "Гамбургер з сиром і куркою",
    category: "Гамбургери",
    ingredients:
      "З карамелізованою цибулею і помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 301,
    title: "Чізбургер + картопля",
    category: "Гамбургер-меню",
    ingredients: "З помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 302,
    title: "Сир і бекон + картопля",
    category: "Гамбургер-меню",
    ingredients: "З помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 303,
    title: "Курячий гамбургер + картопля",
    category: "Гамбургер-меню",
    ingredients: "З помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 304,
    title: "Яйце і бекон + картопля",
    category: "Гамбургер-меню",
    ingredients:
      "З вершковим сиром, помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 305,
    title: "Сир і курка + картопля",
    category: "Гамбургер-меню",
    ingredients:
      "З карамелізованою цибулею і помідором, зеленою салатою, огірками, майонезом, кетчупом",
  },
  {
    menuNumber: 401,
    title: "Тост з індичкою і чеддером",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 402,
    title: "Клубний сендвіч",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 403,
    title: "Сендвіч з куркою",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 404,
    title: "Порція чевапчичів з лавашем і соусом цацики",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 405,
    title: "Порція курки з лавашем",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 406,
    title: "Вегетаріанська фокача (360г)",
    category: "Сендвічі",
    ingredients: "З картоплею фрі та коктейльним соусом",
  },
  {
    menuNumber: 407,
    title: "Фокача з моцарелою (360г)",
    category: "Сендвічі",
    ingredients: "З картоплею фрі та коктейльним соусом",
  },
  {
    menuNumber: 408,
    title: "Фокача з курячими чевапчичами (360г)",
    category: "Сендвічі",
    ingredients: "З картоплею фрі та коктейльним соусом",
  },
  {
    menuNumber: 409,
    title: "Фокача зі свинячими чевапчичами (360г)",
    category: "Сендвічі",
    ingredients: "З картоплею фрі та коктейльним соусом",
  },
  {
    menuNumber: 410,
    title: "Фокача з курячим філе (360г)",
    category: "Сендвічі",
    ingredients: "З картоплею фрі та коктейльним соусом",
  },
  {
    menuNumber: 411,
    title: "Фокача з золотими смужками (360г)",
    category: "Сендвічі",
    ingredients: "З картоплею фрі та коктейльним соусом",
  },
  {
    menuNumber: 412,
    title: "Фокача з 4 видами сиру (360г)",
    category: "Сендвічі",
    ingredients: "З картоплею фрі та коктейльним соусом",
  },
  {
    menuNumber: 413,
    title: "Картопля фрі",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 414,
    title: "Картопля фрі з беконом",
    category: "Сендвічі",
    ingredients:
      "З беконом, тертим пармезаном, соусом з чеддером і вершковим сиром",
  },
  {
    menuNumber: 501,
    title: "Шоколадні млинці",
    category: "Десерти",
    ingredients: "З бананом і тертим печивом",
  },
  {
    menuNumber: 502,
    title: "Млинці з медом і йогуртом",
    category: "Десерти",
    ingredients: "З медом, йогуртом і тертими горіхами",
  },
  {
    menuNumber: 503,
    title: "Млинці на сніданок",
    category: "Десерти",
    ingredients: "З шинкою і сиром, подвійним яйцем і соусом з вершковим сиром",
  },
  {
    menuNumber: 504,
    title: "Шоколадні вафлі",
    category: "Десерти",
    ingredients: "З тертими горіхами, ваніллю і шоколадним морозивом",
  },
  {
    menuNumber: 505,
    title: "OREO вафлі",
    category: "Десерти",
    ingredients: "З праліне, тертим печивом OREO і 2 кульками морозива OREO",
  },
  {
    menuNumber: 506,
    title: "Шоколадні вафлі",
    category: "Десерти",
    ingredients:
      "З свіжими сезонними фруктами і 2 кульками ягідного та мангового сорбету",
  },
  {
    menuNumber: 507,
    title: "Шоколадний суфле",
    category: "Десерти",
    ingredients: "З ванільним морозивом",
  },
  {
    menuNumber: 508,
    title: "Шоколадні брауні",
    category: "Десерти",
    ingredients: "З горіхами, шоколадним сиропом і ванільним морозивом",
  },
  {
    menuNumber: 601,
    title: "Буена феррера",
    category: "Шоколад",
    ingredients: "Ідеальна гармонія хрусткого печива і молочного шоколаду",
  },
  {
    menuNumber: 602,
    title: "Капричіоза",
    category: "Шоколад",
    ingredients: "Неймовірний шоколадний аромат",
  },
  {
    menuNumber: 603,
    title: "Орео",
    category: "Шоколад",
    ingredients: "Біла шоколадка з тертим печивом ОREO",
  },
  {
    menuNumber: 604,
    title: "Алато",
    category: "Шоколад",
    ingredients: "Насичений смак молочного шоколаду з морською сіллю",
  },
  {
    menuNumber: 605,
    title: "Віденський",
    category: "Шоколад",
    ingredients:
      "Справжній ароматний шоколадний рецепт з 40% какао і вершками, як у Відні",
  },
  {
    menuNumber: 606,
    title: "Класика",
    category: "Шоколад",
    ingredients: "Класичний смак шоколаду з тропічних сортів какао з Африки",
  },
  {
    menuNumber: 607,
    title: "Без цукру",
    category: "Шоколад",
    ingredients: "Інша версія класичного шоколаду без цукру, зі стевією",
  },
  {
    menuNumber: 608,
    title: "Гіркий ацтек",
    category: "Шоколад",
    ingredients: "Темний шоколад з насиченим смаком і ароматом",
  },
  {
    menuNumber: 609,
    title: "Фрагола",
    category: "Шоколад",
    ingredients: "Шоколад з полуничним і ванільним смаком",
  },
  {
    menuNumber: 610,
    title: "Банан",
    category: "Шоколад",
    ingredients: "Шоколад з банановим смаком",
  },
  {
    menuNumber: 611,
    title: "Кокос",
    category: "Шоколад",
    ingredients: "Шоколад з кокосовим молоком",
  },
  {
    menuNumber: 612,
    title: "Кафелатта",
    category: "Шоколад",
    ingredients: "Шоколад з чудовим смаком кави з фундуком і пінним молоком",
  },
  {
    menuNumber: 701,
    title: "Грецька кава",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 702,
    title: "Фрапе",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 703,
    title: "Фрапе з морозивом",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 704,
    title: "Еспресо",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 705,
    title: "Капучино",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 706,
    title: "Фредо капучино",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 707,
    title: "Фредо еспресо",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 708,
    title: "Холодний шоколад",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 709,
    title: "Гарячий шоколад",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 710,
    title: "Мілкшейк",
    category: "Кава",
    ingredients: "Ваніль-шоколад, банан, полуниця",
  },
  {
    menuNumber: 711,
    title: "Гарячий чай",
    category: "Кава",
    ingredients: "Зелений, чорний",
  },
  {
    menuNumber: 712,
    title: "Мокачіно",
    category: "Кава",
    ingredients: "",
  },
  {
    menuNumber: 801,
    title: "Апельсин",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 802,
    title: "Банан",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 803,
    title: "Вишня",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 804,
    title: "Персик",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 805,
    title: "Ананас",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 806,
    title: "Яблуко",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 807,
    title: "Журавлина",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 808,
    title: "Свіжовичавлений апельсин",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 809,
    title: "Домашній лимонад",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 810,
    title: "Свіжий апельсин з грейпфрутом",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 811,
    image: "/menu/just/photo.jpg",
    title: "Свіжий апельсин з лимоном",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 812,
    title: "Холодний чай",
    category: "Соки",
    ingredients: "Зелений, лимон, персик",
  },
  {
    menuNumber: 813,
    title: "Граніта сік",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 901,
    title: "Кока-кола",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 902,
    title: "Фанта",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 903,
    title: "Лимонад",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 904,
    title: "Спрайт",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 905,
    title: "Тонік",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 906,
    title: "Сода",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 907,
    title: "Рожева сода",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 909,
    title: "Ред Булл 355 мл",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 1001,
    title: "Амстел",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1002,
    title: "Амстел темне",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1003,
    title: "Амстел радлер",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1004,
    title: "Амстел фрі",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1005,
    title: "Хайнекен",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1006,
    title: "Міфос",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1007,
    title: "Стелла Артуа",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1008,
    title: "Сол",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1009,
    title: "Фішер",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1010,
    title: "МС Фарланд",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1011,
    title: "Крушовіце",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1012,
    title: "Ердінгер",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1013,
    title: "Сидр яблуко",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1014,
    image: "/menu/just/photo.jpg",
    title: "Сидр вишня",
    price: "6",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1015,
    image: "/menu/just/beer_draft_small.jpg",
    title: "Розливне пиво 300мл",
    price: "6",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1016,
    image: "/menu/just/beer_draft.jpg",
    title: "Розливне пиво 500мл",
    price: "6,5",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1017,
    image: "/menu/just/plomari_ouzo_200ml.jpg",
    title: "Узо Пломарі 200мл",
    price: "9,5",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1101,
    image: "/menu/just/mojito.jpg",
    title: "Мохіто",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1102,
    image: "/menu/just/coctailes.jpg",
    title: "Полуничний мохіто",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1103,
    image: "/menu/just/coctailes.jpg",
    title: "Синій мохіто",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1104,
    image: "/menu/just/coctailes.jpg",
    title: "Безалкогольний мохіто",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1105,
    image: "/menu/just/coctailes.jpg",
    title: "Кайпірінья",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1106,
    image: "/menu/just/coctailes.jpg",
    title: "Космополітен",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1107,
    image: "/menu/just/coctailes.jpg",
    title: "Куба лібре",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1108,
    image: "/menu/just/coctailes.jpg",
    title: "Дайкірі",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1109,
    image: "/menu/just/coctailes.jpg",
    title: "Полуничний дайкірі",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1110,
    image: "/menu/just/coctailes.jpg",
    title: "Піна колада",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1111,
    image: "/menu/just/coctailes.jpg",
    title: "Секс на пляжі",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1112,
    image: "/menu/just/coctailes.jpg",
    title: "Текіла санрайз",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1113,
    image: "/menu/just/coctailes.jpg",
    title: "Кавун",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1114,
    image: "/menu/just/coctailes.jpg",
    title: "Блакитна лагуна",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1115,
    image: "/menu/just/coctailes.jpg",
    title: "Маргарита",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1116,
    image: "/menu/just/coctailes.jpg",
    title: "Блакитний гаваєць",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1117,
    image: "/menu/just/coctailes.jpg",
    title: "Апероль шприц",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1118,
    image: "/menu/just/coctailes.jpg",
    title: "Лонг айленд",
    price: "9,5",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1201,
    image: "/menu/just/photo.jpg",
    title: "Москсофілеро сухе біле вино",
    price: "6",
    category: "Вина-джин-ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1202,
    image: "/menu/just/photo.jpg",
    title: "Москсофілеро сухе біле вино",
    price: "30",
    category: "Вина-джин-ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1203,
    image: "/menu/just/photo.jpg",
    title: "Карамельне напівсолодке біле вино",
    price: "6",
    category: "Вина-джин-ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1204,
    image: "/menu/just/photo.jpg",
    title: "Карамельне напівсолодке біле вино",
    price: "30",
    category: "Вина-джин-ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1205,
    image: "/menu/just/photo.jpg",
    title: "Карамельне напівсолодке червоне вино",
    price: "6",
    category: "Вина-джин-ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1206,
    image: "/menu/just/photo.jpg",
    title: "Карамельне напівсолодке червоне вино",
    price: "30",
    category: "Вина-джин-ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1207,
    image: "/menu/just/photo.jpg",
    title: "Карамельне рожеве вино",
    price: "6",
    category: "Вина-джин-ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1208,
    image: "/menu/just/photo.jpg",
    title: "Карамельне рожеве вино",
    price: "30",
    category: "Вина-джин-ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1209,
    image: "/menu/just/photo.jpg",
    title: "Сангрія біле вино",
    price: "6",
    category: "Вина-джин-ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1210,
    image: "/menu/just/photo.jpg",
    title: "Сангрія червоне вино",
    price: "6",
    category: "Вина-Джин-Ром",
    ingredients: "187мл",
  },
  {
    menuNumber: 1211,
    image: "/menu/just/photo.jpg",
    title: "Асті мартіні шампанське",
    price: "12",
    category: "Вина-Джин-Ром",
    ingredients: "200мл",
  },
  {
    menuNumber: 1212,
    image: "/menu/just/photo.jpg",
    title: "Асті мартіні шампанське",
    price: "60",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1213,
    image: "/menu/just/photo.jpg",
    title: "Моет шампанське",
    price: "160",
    category: "Вина-Джин-Ром",
    ingredients: "750мл",
  },
  {
    menuNumber: 1214,
    image: "/menu/just/photo.jpg",
    title:
      "Віскі просте (Dewars, Johnnie, Ballantines, Haig, Famos, J&B, Cutty Sark, Grants)",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1215,
    image: "/menu/just/photo.jpg",
    title:
      "Віскі просте (Dewars, Johnnie, Ballantines, Haig, Famos, J&B, Cutty Sark, Grants)",
    price: "80",
    category: "Вина-Джин-Ром",
    ingredients: "700мл",
  },
  {
    menuNumber: 1216,
    image: "/menu/just/photo.jpg",
    title:
      "Віскі спеціальне (Jack Daniels, Dimple, Chivas, Cardu, Johnnie Black)",
    price: "8,5",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1217,
    image: "/menu/just/photo.jpg",
    title:
      "Віскі спеціальне (Jack Daniels, Dimple, Chivas, Cardu, Johnnie Black)",
    price: "95",
    category: "Вина-Джин-Ром",
    ingredients: "700мл",
  },
  {
    menuNumber: 1218,
    image: "/menu/just/photo.jpg",
    title: "Горілка (Absolut, Stolichnaya, Belvedere, North, Ursus)",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1219,
    image: "/menu/just/photo.jpg",
    title: "Джин Gordons",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1220,
    image: "/menu/just/photo.jpg",
    title: "Hendricks",
    price: "10",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1221,
    image: "/menu/just/photo.jpg",
    title: "Bombay",
    price: "10",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1222,
    image: "/menu/just/photo.jpg",
    title: "Tanquerey",
    price: "9",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1223,
    image: "/menu/just/photo.jpg",
    title: "Bacardi",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1224,
    image: "/menu/just/photo.jpg",
    title: "Metaxa 3*",
    price: "7",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1225,
    image: "/menu/just/photo.jpg",
    title: "Metaxa 5*",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1226,
    image: "/menu/just/photo.jpg",
    title: "Metaxa 7*",
    price: "9",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1227,
    image: "/menu/just/photo.jpg",
    title: "Текіла Cuervo жовта",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1228,
    image: "/menu/just/photo.jpg",
    title: "Текіла Cuervo біла",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1229,
    image: "/menu/just/photo.jpg",
    title: "Martini (Bianco, Rosso, Rossato, Dry)",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1230,
    image: "/menu/just/photo.jpg",
    title: "Havana club (Білий-Чорний)",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1231,
    image: "/menu/just/photo.jpg",
    title: "Campari",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 1232,
    image: "/menu/just/photo.jpg",
    title: "Malibu",
    price: "8",
    category: "Вина-Джин-Ром",
    ingredients: "60мл",
  },
  {
    menuNumber: 207,
    title: "Бургер зі свининою гірос",
    category: "Гамбургери",
    ingredients:
      "З булкою бріош, помідором, цибулею, зеленою салатом, кетчупом, гірчицею та свининою гірос з картоплею",
  },
  {
    menuNumber: 208,
    title: "Бургер з куркою гірос",
    category: "Гамбургери",
    ingredients:
      "З булкою бріош, помідором, цибулею, зеленою салатом, кетчупом, гірчицею та куркою гірос з картоплею",
  },
  {
    menuNumber: 415,
    title: "Клаб сендвіч зі свининою гірос",
    category: "Сендвічі",
    ingredients: "З пітою, дзадзікі, помідором, цибулею, зеленою салатом",
  },
  {
    menuNumber: 416,
    title: "Клаб сендвіч з куркою гірос",
    category: "Сендвічі",
    ingredients: "З пітою, дзадзікі, помідором, цибулею, зеленою салатом",
  },
];
