export const ua = [
  {
    menuNumber: 101,
    title: "Grčka salata",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 102,
    title: "Cezar salata",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 103,
    title: "Posebna salata",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 104,
    title: "Tunjevina salata",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 105,
    title: "Voćna salata",
    category: "Салати",
    ingredients: " ",
  },
  {
    menuNumber: 201,
    title: "Hamburger",
    category: "Гамбургери",
    ingredients:
      "Sa paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 202,
    title: "Čizburger",
    category: "Гамбургери",
    ingredients:
      "Sa paradajzom, zelenom zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 203,
    title: "Sir i slanina",
    category: "Гамбургери",
    ingredients:
      "Sa paradajzom, zelenom zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 204,
    title: "Pileći hamburger",
    category: "Гамбургери",
    ingredients:
      "Sa paradajzom, zelenom zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 205,
    title: "Hamburger sa jajima i slaninom",
    category: "Гамбургери",
    ingredients:
      "Sa krem sirom, paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 206,
    title: "Hamburger sa sirom i piletinom",
    category: "Гамбургери",
    ingredients:
      "Sa karamelizovanim lukom i paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 301,
    title: "Čizburger + krompir",
    category: "Гамбургер-меню",
    ingredients:
      "Sa paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 302,
    title: "Sir i slanina + krompir",
    category: "Гамбургер-меню",
    ingredients:
      "Sa paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 303,
    title: "Pileći hamburger + krompir",
    category: "Гамбургер-меню",
    ingredients:
      "Sa paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 304,
    title: "Jaja i slanina + krompir",
    category: "Гамбургер-меню",
    ingredients:
      "Sa krem sirom, paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 305,
    title: "Sir i piletina + krompir",
    category: "Гамбургер-меню",
    ingredients:
      "Sa karamelizovanim lukom i paradajzom, zelenom salatom, krastavcima, majonezom, kečapom",
  },
  {
    menuNumber: 401,
    title: "Tost sa ćuretinom i čedar sirom",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 402,
    title: "Klub sendvič",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 403,
    title: "Sendvič sa piletinom",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 404,
    title: "Porcija ćevapa sa pitom i tzatziki sosom",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 405,
    title: "Porcija piletine sa pitom",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 406,
    title: "Vegetarijanski fokača (360g)",
    category: "Сендвічі",
    ingredients: "Sa pomfritom i kokteil sosom",
  },
  {
    menuNumber: 407,
    title: "Fokača sa mozzarellom (360g)",
    category: "Сендвічі",
    ingredients: "Sa pomfritom i kokteil sosom",
  },
  {
    menuNumber: 408,
    title: "Fokača sa ćevapima od piletine (360g)",
    category: "Сендвічі",
    ingredients: "Sa pomfritom i kokteil sosom",
  },
  {
    menuNumber: 409,
    title: "Fokača sa ćevapima od svinjetine (360g)",
    category: "Сендвічі",
    ingredients: "Sa pomfritom i kokteil sosom",
  },
  {
    menuNumber: 410,
    title: "Fokača sa pilećim fileom (360g)",
    category: "Сендвічі",
    ingredients: "Sa pomfritom i kokteil sosom",
  },
  {
    menuNumber: 411,
    title: "Fokača sa zlatnim rezancima (360g)",
    category: "Сендвічі",
    ingredients: "Sa pomfritom i kokteil sosom",
  },
  {
    menuNumber: 412,
    title: "Fokača sa 4 vrste sira (360g)",
    category: "Сендвічі",
    ingredients: "Sa pomfritom i kokteil sosom",
  },
  {
    menuNumber: 413,
    title: "Pomfrit",
    category: "Сендвічі",
    ingredients: "",
  },
  {
    menuNumber: 414,
    title: "Pomfrit sa slaninom",
    category: "Сендвічі",
    ingredients:
      "Sa slaninom, rendanim parmezan sirom, sosom od čedara i kremskim sirom",
  },
  {
    menuNumber: 501,
    title: "Čokoladni palačinke",
    category: "Десерти",
    ingredients: "Sa bananom i rendanim keksom",
  },
  {
    menuNumber: 502,
    title: "Palačinke sa medom i jogurtom",
    category: "Десерти",
    ingredients: "Sa medom, jogurtom i rendanim orasima",
  },
  {
    menuNumber: 503,
    title: "Palačinke za doručak",
    category: "Десерти",
    ingredients:
      "Sa šunkom i sirom, dvostrukom duplom, jajima i sosom od kremskog sira",
  },
  {
    menuNumber: 504,
    title: "Čokoladne vajfle",
    category: "Десерти",
    ingredients: "Sa rendanim orasima, Vanilom i čokoladnim sladoledom",
  },
  {
    menuNumber: 505,
    title: "OREO vajfle",
    category: "Десерти",
    ingredients: "Sa pralineom, rendanim OREO keksom i 2 kugle OREO sladoleda",
  },
  {
    menuNumber: 506,
    title: "Čokoladne vajfle",
    category: "Десерти",
    ingredients:
      "Sa svežim sezonskim voćem i 2 kugle jagodastog i mango sorbeta",
  },
  {
    menuNumber: 507,
    title: "Čokoladni sufle",
    category: "Десерти",
    ingredients: "Sa vanila sladoledom",
  },
  {
    menuNumber: 508,
    title: "Čokoladni browniji",
    category: "Десерти",
    ingredients: "Sa orasima, čokoladnim sirupom i vanila sladoledom",
  },
  {
    menuNumber: 601,
    title: "Buena ferrera",
    category: "Шоколад",
    ingredients: "Savršena harmonija hrskavog keksa i mlečne čokolade",
  },
  {
    menuNumber: 602,
    title: "Capricciosa",
    category: "Шоколад",
    ingredients: "Neverovatna čokoladna aroma",
  },
  {
    menuNumber: 603,
    title: "Oreo",
    category: "Шоколад",
    ingredients: "Bela čokolada sa rendanim OREO keksom",
  },
  {
    menuNumber: 604,
    title: "Alato",
    category: "Шоколад",
    ingredients: "Bogat ukus mlečne čokolade posut morskom solju",
  },
  {
    menuNumber: 605,
    title: "Viennua",
    category: "Шоколад",
    ingredients:
      "Autentičan aromatični čokoladni recept sa 40% kakaa i šlagom, baš kao u Beču",
  },
  {
    menuNumber: 606,
    title: "Classica",
    category: "Шоколад",
    ingredients: "Klasičan ukus čokolade od tropskih kakao sorti iz Afrike",
  },
  {
    menuNumber: 607,
    title: "Bez šećera",
    category: "Шоколад",
    ingredients: "Druga verzija klasične čokolade bez šećera, sa stevijom",
  },
  {
    menuNumber: 608,
    title: "Bitter aztec",
    category: "Шоколад",
    ingredients: "Tamna čokolada sa snažnim ukusom i aromom",
  },
  {
    menuNumber: 609,
    title: "Fragola",
    category: "Шоколад",
    ingredients: "Čokolada sa ukusom jagode i vanile",
  },
  {
    menuNumber: 610,
    title: "Banana",
    category: "Шоколад",
    ingredients: "Čokolada sa ukusom banane",
  },
  {
    menuNumber: 611,
    title: "Kokos",
    category: "Шоколад",
    ingredients: "Čokolada sa ukusom kokosovog mleka",
  },
  {
    menuNumber: 612,
    title: "Cafelatta",
    category: "Шоколад",
    ingredients: "Čokolada sa divnim ukusom Кофе sa lešnikom i penastim mlekom",
  },
  {
    menuNumber: 701,
    title: "Grčka kafa",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 702,
    title: "Frape",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 703,
    title: "Frape sa sladoledom",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 704,
    title: "Espreso",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 705,
    title: "Kapućino",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 706,
    title: "Fredo kapućino",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 707,
    title: "Fredo espreso",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 708,
    title: "Hladna čokolada",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 709,
    title: "Topla čokolada",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 710,
    title: "Milkšejk",
    category: "Кофе",
    ingredients: "Vanila-čokolada, banana, jagoda",
  },
  {
    menuNumber: 711,
    title: "Topli čaj",
    category: "Кофе",
    ingredients: "Zeleni, crni",
  },
  {
    menuNumber: 712,
    title: "Mokaćino",
    category: "Кофе",
    ingredients: "",
  },
  {
    menuNumber: 801,
    title: "Pomorandža",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 802,
    title: "Banana",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 803,
    title: "Trešnja",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 804,
    title: "Breskva",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 805,
    title: "Ananas",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 806,
    title: "Jabuka",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 807,
    title: "Brusnica",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 808,
    title: "Sveže ceđena pomorandža",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 809,
    title: "Domaća limunada",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 810,
    title: "Sveža pomorandža sa grejpfrutom",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 811,
    image: "/menu/just/photo.jpg",
    title: "Sveža pomorandža sa limunom",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 812,
    title: "Ledeni čaj",
    category: "Соки",
    ingredients: "Zeleni, limun, breskva",
  },
  {
    menuNumber: 813,
    title: "Granita sok",
    category: "Соки",
    ingredients: "",
  },
  {
    menuNumber: 901,
    title: "Koka-kola",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 902,
    title: "Fanta",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 903,
    title: "Limonada",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 904,
    title: "Sprite",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 905,
    title: "Tonik",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 906,
    title: "Soda",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 907,
    title: "Ružičasta soda",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 909,
    title: "Red Bull 355ml",
    category: "Напої",
    ingredients: "",
  },
  {
    menuNumber: 1001,
    title: "Amstel",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1002,
    title: "Amstel tamno",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1003,
    title: "Amstel radler",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1004,
    title: "Amstel free",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1005,
    title: "Heineken",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1006,
    title: "Mythos",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1007,
    title: "Stella Artois",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1008,
    title: "Sol",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1009,
    title: "Fisher",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1010,
    title: "MC farland",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1011,
    title: "Krusovice",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1012,
    title: "Erdinger",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1013,
    title: "Milokleftis jabuka",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1014,
    title: "Milokleftis višnja",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1015,
    title: "Točeno Пиво 300ml",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1016,
    title: "Točeno Пиво 500ml",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1017,
    title: "Ouzo Plomari 200ml",
    category: "Пиво",
    ingredients: "",
  },
  {
    menuNumber: 1101,
    title: "Mojto",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1102,
    title: "Mojto sa jagodama",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1103,
    title: "Plavi mojto",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1104,
    title: "Mojto bez alkohola",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1105,
    title: "Kaipirinja",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1106,
    title: "Kozmopoliten",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1107,
    title: "Kuba libre",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1108,
    title: "Dakviri",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1109,
    title: "Dakviri sa jagodama",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1110,
    title: "Pina kolada",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1111,
    title: "Seks na plaži",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1112,
    title: "Tekila izlazak",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1113,
    title: "Lubenica",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1114,
    title: "Plava laguna",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1115,
    title: "Margarita",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1116,
    title: "Plavi havajski",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1117,
    title: "Aperol Spritz",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1118,
    title: "Long island",
    category: "Коктейлі",
    ingredients: "",
  },
  {
    menuNumber: 1201,
    title: "Mosxofilero suvo belo vino",
    category: "Вино-Джин-Ром",
    ingredients: "187ml",
  },
  {
    menuNumber: 1202,
    title: "Mosxofilero suvo belo vino",
    category: "Вино-Джин-Ром",
    ingredients: "750ml",
  },
  {
    menuNumber: 1203,
    title: "Caramelo polусlatко belo vino",
    category: "Вино-Джин-Ром",
    ingredients: "187ml",
  },
  {
    menuNumber: 1204,
    title: "Caramelo polусlatко belo vino",
    category: "Вино-Джин-Ром",
    ingredients: "750ml",
  },
  {
    menuNumber: 1205,
    title: "Caramelo polусlatко crveno vino",
    category: "Вино-Джин-Ром",
    ingredients: "187ml",
  },
  {
    menuNumber: 1206,
    title: "Karamelo polusuvi crveni vino",
    category: "Вино-Джин-Ром",
    ingredients: "750ml",
  },
  {
    menuNumber: 1207,
    title: "Karamelo roze vino",
    category: "Вино-Джин-Ром",
    ingredients: "187ml",
  },
  {
    menuNumber: 1208,
    title: "Karamelo roze vino",
    category: "Вино-Джин-Ром",
    ingredients: "750ml",
  },
  {
    menuNumber: 1209,
    title: "Sangrija belo vino",
    category: "Вино-Джин-Ром",
    ingredients: "187ml",
  },
  {
    menuNumber: 1210,
    title: "Sangrija crveno vino",
    category: "Вино-Джин-Ром",
    ingredients: "187ml",
  },
  {
    menuNumber: 1211,
    title: "Asti martini šampanjac",
    category: "Вино-Джин-Ром",
    ingredients: "200ml",
  },
  {
    menuNumber: 1212,
    title: "Asti martini šampanjac",
    category: "Вино-Джин-Ром",
    ingredients: "750ml",
  },
  {
    menuNumber: 1213,
    title: "Moet šampanjac",
    category: "Вино-Джин-Ром",
    ingredients: "750ml",
  },
  {
    menuNumber: 1214,
    title:
      "Viski običan (Djus, Džoni, Balantins, Hajg, Famos, J&B, Kati Sark, Grants)",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1215,
    title:
      "Viski običan (Djus, Džoni, Balantins, Hajg, Famos, J&B, Kati Sark, Grants)",
    category: "Вино-Джин-Ром",
    ingredients: "700ml",
  },
  {
    menuNumber: 1216,
    title: "Viski specijalni (Džek Denijels, Dimple, Čivas, Kardu, Džoni Blek)",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1217,
    title: "Viski specijalni (Džek Denijels, Dimple, Čivas, Kardu, Džoni Blek)",
    category: "Вино-Джин-Ром",
    ingredients: "700ml",
  },
  {
    menuNumber: 1218,
    title: "Votka (Absolut, Stoličnaja, Belveder, Nort, Ursus)",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1219,
    title: "Džin Gordons",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1220,
    title: "Hendriks",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1221,
    title: "Bombaj",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1222,
    title: "Tankeraj",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1223,
    title: "Bakardi",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1224,
    title: "Metaxa 3*",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1225,
    title: "Metaxa 5*",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1226,
    title: "Metaxa 7*",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1227,
    title: "Tekila Kuerbo žuta",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1228,
    title: "Tekila Kuerbo bela",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1229,
    title: "Martini (Bijanko, Roso, Rosato, Drjaj)",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1230,
    title: "Havana klub (Belo-Crno)",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1231,
    title: "Kampari",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1232,
    title: "Malibu",
    category: "Вино-Джин-Ром",
    ingredients: "60ml",
  },
  {
    menuNumber: 1301,
    title: "Смузі 01",
    category: "Смузі",
    subCategory: null,
    ingredients: "Jagoda, breskva, banana",
  },
  {
    menuNumber: 1302,
    title: "Смузі 02",
    category: "Смузі",
    subCategory: null,
    ingredients: "Jagoda, mango, dinja",
  },
  {
    menuNumber: 1303,
    title: "Смузі 03",
    category: "Смузі",
    subCategory: null,
    ingredients: "Kruška, mango, ananas",
  },
  {
    menuNumber: 1304,
    title: "Смузі 04",
    category: "Смузі",
    subCategory: null,
    ingredients: "Borovnica, kupina, banana",
  },
  {
    menuNumber: 1305,
    title: "Смузі 05",
    category: "Смузі",
    subCategory: null,
    ingredients: "Strastveno voće, breskva, mango",
  },
  {
    menuNumber: 1306,
    title: "Смузі 06",
    category: "Смузі",
    subCategory: null,
    ingredients: "Malina, mango, jabuka, borovnica",
  },
  {
    menuNumber: 1307,
    title: "Смузі 07",
    category: "Смузі",
    subCategory: null,
    ingredients: "Limun, šargarepa, jabuka, spanać, đumbir",
  },
  {
    menuNumber: 1308,
    title: "Смузі 08",
    category: "Смузі",
    subCategory: null,
    ingredients: "Avokado, kelj, ceder limuna, banana",
  },
  {
    menuNumber: 1309,
    title: "Смузі 09",
    category: "Смузі",
    subCategory: null,
    ingredients: "Pitahaja, limun, banana, mango",
  },
  {
    menuNumber: 1310,
    title: "Смузі 10",
    category: "Смузі",
    subCategory: null,
    ingredients: "Sladoled, ananas, mango, banana",
  },
  {
    menuNumber: 1311,
    title: "Смузі 11",
    category: "Смузі",
    subCategory: null,
    ingredients: "Biskvit, vegan krema",
  },
  {
    menuNumber: 1312,
    title: "Смузі 12",
    category: "Смузі",
    subCategory: null,
    ingredients: "Sladoled, banana, jagoda",
  },
  {
    menuNumber: 207,
    title: "Burger sa giros svinjetinom",
    category: "Гамбургери",
    ingredients:
      "Sa brioš hlebom, paradajzom, lukom, zelenom zelenom salatom, kečapom, senfom i giros svinjetinom sa krompirom",
  },
  {
    menuNumber: 208,
    title: "Burger sa giros piletinom",
    category: "Гамбургери",
    ingredients:
      "Sa brioš hlebom, paradajzom, lukom, zelenom zelenom salatom, kečapom, senfom i giros piletinom sa krompirom",
  },
  {
    menuNumber: 415,
    title: "Klub sendvič sa giros svinjetinom",
    category: "Сендвічі",
    ingredients:
      "Sa pita hlebom, cacakijem, paradajzom, lukom, zelenom zelenom salatom",
  },
  {
    menuNumber: 416,
    title: "Klub sendvič sa giros piletinom",
    category: "Сендвічі",
    ingredients:
      "Sa pita hlebom, cacakijem, paradajzom, lukom, zelenom zelenom salatom",
  },
];
