export const menuArazo = {
  en: [
    {
      id: 10,
      image: "/menu/potatos_fried.jpg",
      title: "Fried potatos",
      price: "4",
      category: "Apettizer",
      ingredients: " ",
      sorting: "01",
    },
    {
      id: 11,
      image: "/menu/crispy_zucchini.jpg",
      title: "Crispy Zucchini",
      price: "4,5",
      category: "Apettizer",
      ingredients: "with tzatziki",
      sorting: "01",
    },
    {
      id: 12,
      image: "/menu/photo.jpg",
      title: "Cheese donuts",
      price: "5",
      category: "Apettizer",
      ingredients: "with honey",
      sorting: "01",
    },
    {
      id: 13,
      image: "/menu/fried_feta.jpg",
      title: "Fried Feta",
      price: "5",
      category: "Apettizer",
      ingredients: "with sweet chilly or honey",
      sorting: "01",
    },
    {
      id: 14,
      image: "/menu/photo.jpg",
      title: "Roasted Feta",
      price: "5",
      category: "Apettizer",
      ingredients: "on rack with tomatoes",
      sorting: "01",
    },
    {
      id: 15,
      image: "/menu/hallumi_cheese.jpg",
      title: "Hallumi cheese",
      price: "5,5",
      category: "Apettizer",
      ingredients: "with strawberry jam",
      sorting: "01",
    },
    {
      id: 16,
      image: "/menu/roasted_eggplant.jpg",
      title: "Roasted Eggplant",
      price: "5,6",
      category: "Apettizer",
      ingredients: "with grated tomatoes and feta",
      sorting: "01",
    },
    {
      id: 17,
      image: "/menu/photo.jpg",
      title: "Hot Pepper",
      price: "9",
      category: "Apettizer",
      ingredients: "on the grill",
      sorting: "01",
    },
    {
      id: 18,
      image: "/menu/photo.jpg",
      title: "Smoked Mackerel",
      price: "7",
      category: "Apettizer",
      ingredients: "on the grill with lemon and oil",
      sorting: "01",
    },
    {
      id: 19,
      image: "/menu/photo.jpg",
      title: "Anchovies",
      price: "6",
      category: "Apettizer",
      ingredients: "with olives",
      sorting: "01",
    },
    {
      id: 20,
      image: "/menu/tzatziki.jpg",
      title: "Tzatziki",
      price: "4,5",
      category: "Homemade salads/Salves",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 21,
      image: "/menu/russian_salad.jpg",
      title: "Russian",
      price: "4,5",
      category: "Homemade salads/Salves",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 22,
      image: "/menu/photo.jpg",
      title: "Cheese spicy cream",
      price: "4,5",
      category: "Homemade salads/Salves",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 23,
      image: "/menu/photo.jpg",
      title: "Hungarian",
      price: "4,5",
      category: "Homemade salads/Salves",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 24,
      image: "/menu/photo.jpg",
      title: "Paprika",
      price: "4,5",
      category: "Homemade salads/Salves",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 25,
      image: "/menu/photo.jpg",
      title: "Chicken",
      price: "4,5",
      category: "Homemade salads/Salves",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 26,
      image: "/menu/photo.jpg",
      title: "Crab",
      price: "4,5",
      category: "Homemade salads/Salves",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 30,
      image: "/menu/salad_ara_zo.jpg",
      title: "Αρα...ζω",
      price: "7,9",
      category: "Fresh salads",
      ingredients:
        "with spinach, lettuce, bacon, mushrooms, balsamic cream and falagani cheese",
      sorting: "03",
    },
    {
      id: 31,
      image: "/menu/cretan_salad.jpg",
      title: "Cretan Salad",
      price: "7,9",
      category: "Fresh salads",
      ingredients:
        "with grated tomatoes, apple vinegar, bruschetta, tomatoes, Krimato and Greek Feta",
      sorting: "03",
    },
    {
      id: 32,
      image: "/menu/photo.jpg",
      title: "Green salad",
      price: "7,7",
      category: "Fresh salads",
      ingredients:
        "with baby spinach, rocket, dried grapes, arange beetroof and cheese cream",
      sorting: "03",
    },
    {
      id: 33,
      image: "/menu/cesar_salad.jpg",
      title: "Cesar salad",
      price: "7,9",
      category: "Fresh salads",
      ingredients:
        "with greell chicken, parmesan, crouton, bacon, dressing with lemon and maonnaise",
      sorting: "03",
    },
    {
      id: 34,
      image: "/menu/photo.jpg",
      title: "Vegan salad",
      price: "7,7",
      category: "Fresh salads",
      ingredients:
        "with variety of lettuce, quinoa, mango, cherry tomatoes, caramelized walnuts and vinaigrette with pomergranate",
      sorting: "03",
    },
    {
      id: 35,
      image: "/menu/photo.jpg",
      title: "Greek salad",
      price: "7,9",
      category: "Fresh salads",
      ingredients:
        "with tomatoes, cucumber, onion, red and green paper, fete parsley, olives, extra virgin oil and capers",
      sorting: "03",
    },
    {
      id: 36,
      image: "/menu/photo.jpg",
      title: "Aggourotomata",
      price: "4,9",
      category: "Fresh salads",
      ingredients: "with tomatoes, cucumber, onion and oil",
      sorting: "03",
    },
    {
      id: 37,
      image: "/menu/salad_seasonal.jpg",
      title: "Seasonal Greens",
      price: "4,7",
      category: "Fresh salads",
      ingredients: " ",
      sorting: "03",
    },
    {
      id: 40,
      image: "/menu/photo.jpg",
      title: "Mushrooms",
      price: "5,9",
      category: "In Our Pan",
      ingredients: "in pans",
      sorting: "04",
    },
    {
      id: 41,
      image: "/menu/shrimp_spaghetti.jpg",
      title: "Shrimp spaghetti",
      price: "19,4",
      category: "In Our Pan",
      ingredients: "with fresh cream of tomatoes",
      sorting: "04",
    },
    {
      id: 50,
      image: "/menu/kebab_handmade.jpg",
      title: "Handmade kebab",
      price: "10",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 51,
      image: "/menu/saslik.jpg",
      title: "Handmade Saslik",
      price: "11,9",
      category: "In Our Embers",
      ingredients: "(kontosouvli) with chicken or pork",
      sorting: "05",
    },
    {
      id: 52,
      image: "/menu/photo.jpg",
      title: "Aromatic kebab",
      price: "7,6",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 53,
      image: "/menu/photo.jpg",
      title: "Fresh baked meatballs",
      price: "7,9",
      category: "In Our Embers",
      ingredients: "grilled with spearmint",
      sorting: "05",
    },
    {
      id: 54,
      image: "/menu/photo.jpg",
      title: "Traditional sausage",
      price: "7,9",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 55,
      image: "/menu/grill_pancetta.jpg",
      title: "Grill panchetta",
      price: "7,9",
      category: "In Our Embers",
      ingredients: "with lemon and mustard",
      sorting: "05",
    },
    {
      id: 56,
      image: "/menu/greek_souvlaki.jpg",
      title: "Greek souvlaki",
      price: "7,9",
      category: "In Our Embers",
      ingredients: "pork or chicken (skewer)",
      sorting: "05",
    },
    {
      id: 57,
      image: "/menu/photo.jpg",
      title: "Steak on the grill",
      price: "13,4",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 58,
      image: "/menu/photo.jpg",
      title: "Spare Ribs",
      price: "11,30",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 59,
      image: "/menu/lamb_ribs.jpg",
      title: "Lamb Ribs",
      price: "16,9",
      category: "In Our Embers",
      ingredients: "with lemon and oregano",
      sorting: "05",
    },
    {
      id: 591,
      image: "/menu/photo.jpg",
      title: "Chicken nuts or Chicken fillet",
      price: "8,6",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 592,
      image: "/menu/Burger.jpg",
      title: "Burger",
      price: "10",
      category: "In Our Embers",
      ingredients:
        "beef meat, iceberg, tomato, bbq saice, cheddar and fried fries",
      sorting: "05",
    },
    {
      id: 593,
      image: "/menu/photo.jpg",
      title: "T-Bone",
      price: "27",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 594,
      image: "/menu/photo.jpg",
      title: "French Ribeye",
      price: "29,3",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 595,
      image: "/menu/photo.jpg",
      title: "Bavette",
      price: "26",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 596,
      image: "/menu/photo.jpg",
      title: "Beef Steak",
      price: "18,9",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 597,
      image: "/menu/photo.jpg",
      title: "Ribeye Steak",
      price: "22,3",
      category: "In Our Embers",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 60,
      image: "/menu/fried_squid.jpg",
      title: "Fried squid",
      price: "8,2",
      category: "Seafood",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 61,
      image: "/menu/grilled_octopus.jpg",
      title: "Grilled Octopus",
      price: "13,8",
      category: "Seafood",
      ingredients: "with apple vinegar",
      sorting: "06",
    },
    {
      id: 62,
      image: "/menu/photo.jpg",
      title: "Fresh squid",
      price: "19",
      category: "Seafood",
      ingredients: "on the grill",
      sorting: "06",
    },
    {
      id: 63,
      image: "/menu/photo.jpg",
      title: "Mussels",
      price: "9",
      category: "Seafood",
      ingredients: "in the wapor",
      sorting: "06",
    },
    {
      id: 64,
      image: "/menu/photo.jpg",
      title: "Mussels Fried",
      price: "9",
      category: "Seafood",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 65,
      image: "/menu/photo.jpg",
      title: "Mussels",
      price: "9",
      category: "Seafood",
      ingredients: "in the pan with tomato sauce and peppers",
      sorting: "06",
    },
    {
      id: 66,
      image: "/menu/Shrimps.jpg",
      title: "Shrimps",
      price: "19,2",
      category: "Seafood",
      ingredients: "in the pan with tomato sauce and peppers",
      sorting: "06",
    },
    {
      id: 67,
      image: "/menu/shrimps_fried.jpg",
      title: "Shrimps Grill/Fried",
      price: "19",
      category: "Seafood",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 68,
      image: "/menu/anchovies_fried.jpg",
      title: "Fresh fried anchovies",
      price: "12",
      category: "Seafood",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 69,
      image: "/menu/koutsomoures.jpg",
      title: "Koutsomoures",
      price: "15",
      category: "Seafood",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 70,
      image: "/menu/exquiste_meat.jpg",
      title: "Exquiste meat variety for 2 people",
      price: "18",
      category: "Exquiste meat",
      ingredients:
        "1 pc (souvlaki pork, souvlaki chicken soutzoukaki, sausage, meatball) 2pc pancetta",
      sorting: "07",
    },
    {
      id: 71,
      image: "/menu/exquiste_meat.jpg",
      title: "Exquiste meat variety for 4 people",
      price: "34",
      category: "Exquiste meat",
      ingredients:
        "2 pc (souvlaki pork, souvlaki chicken soutzoukaki, sausage, meatball) 4pc pancetta",
      sorting: "07",
    },
    {
      id: 80,
      image: "/menu/coca_cola.jpg",
      title: "Coca cola",
      price: "2",
      category: "Refreshments",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 81,
      image: "/menu/coca_cola_zero.jpg",
      title: "Coca cola zero",
      price: "2",
      category: "Refreshments",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 82,
      image: "/menu/fanta.jpg",
      title: "Fanta",
      price: "2",
      category: "Refreshments",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 83,
      image: "/menu/sprite.jpg",
      title: "Sprite",
      price: "2",
      category: "Refreshments",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 84,
      image: "/menu/fanta_lemon.jpg",
      title: "Fanta Lemon",
      price: "2",
      category: "Refreshments",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 85,
      image: "/menu/sparkling_juices.jpg",
      title: "Sparkling water Juices",
      price: "2",
      category: "Refreshments",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 86,
      image: "/menu/water_1l.jpg",
      title: "Water 1,0L",
      price: "1,5",
      category: "Refreshments",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 90,
      image: "/menu/beer_mythos.jpg",
      title: "Mythos",
      price: "4",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 91,
      image: "/menu/beer_fix.jpg",
      title: "Fix Hellas",
      price: "4",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 92,
      image: "/menu/beer_fix_dark.jpg",
      title: "Fix Dark",
      price: "4",
      category: "Beers",
      ingredients: "",
      vsorting: "09",
    },
    {
      id: 93,
      image: "/menu/beer_fix_0.jpg",
      title: "Fix free alcochol",
      price: "4",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 94,
      image: "/menu/beer_kaiser.jpg",
      title: "Kaiser",
      price: "4,5",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 95,
      image: "/menu/beer_carlsberg.jpg",
      title: "Carlsberg",
      price: "4,5",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 96,
      image: "/menu/beer_mythos_radler.jpg",
      title: "Mythos Radler",
      price: "4",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 97,
      image: "/menu/beer_nimfi.jpg",
      title: "Nimfi",
      price: "4,5",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 98,
      image: "/menu/beer_draft.jpg",
      title: "Draft 400ml",
      price: "5",
      category: "Beers",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 100,
      image: "/menu/retsina_45rounds.jpg",
      title: "45 Rounds",
      price: "5",
      category: "Retsina",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 101,
      image: "/menu/retsina_georgiadi.jpg",
      title: "Georgiadi",
      price: "4",
      category: "Retsina",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 102,
      image: "/menu/retsina_malamatina.jpg",
      title: "Malamatina",
      price: "4",
      category: "Retsina",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 103,
      image: "/menu/retsina_kexribari.jpg",
      title: "Kexribari",
      price: "6,5",
      category: "Retsina",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 104,
      image: "/menu/retsina_vasiliki.jpg",
      title: "Vasiliki",
      price: "5",
      category: "Retsina",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 110,
      image: "/menu/draft_wines.jpg",
      title: "Draft wines of Chalkidiki",
      price: "6",
      category: "Our Wines",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 111,
      image: "/menu/glass_wine.jpg",
      title: "Glass Wine",
      price: "5,5",
      category: "Our Wines",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 112,
      image: "/menu/bottles_wine.jpg",
      title: "Bottles",
      price: "20",
      category: "Our Wines",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 120,
      image: "/menu/ouzo.jpg",
      title: "Ouzo",
      price: "8",
      category: "Ouzo/Tsipouro",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 121,
      image: "/menu/tsipouro_with_anice.jpg",
      title: "Tsipouro with anise",
      price: "9",
      category: "Ouzo/Tsipouro",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 122,
      image: "/menu/tsipouro_without_anise.jpg",
      title: "Tsipouro without anise",
      price: "9",
      category: "Ouzo/Tsipouro",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 123,
      image: "/menu/draft_tsipouro_with_anise.jpg",
      title: "Draft tsipouro with anise",
      price: "7",
      category: "Ouzo/Tsipouro",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 124,
      image: "/menu/draft_tsipouro_without_anise.jpg",
      title: "Draft tsipouro without anise",
      price: "7",
      category: "Ouzo/Tsipouro",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 130,
      image: "/menu/konstantara_sauvignon_blanc.jpg",
      title: "Konstantaras Estate Sauvignon Blanc",
      price: "30",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 131,
      image: "/menu/konstantara_malagouzia.jpg",
      title: "Konstantaras Estate Malagouzia",
      price: "30",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 132,
      image: "/menu/marmaromenos_vasilias.jpg",
      title: "Marmaromenos Vasilias",
      price: "20",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 133,
      image: "/menu/photo.jpg",
      title: "Livadioti Estate Malagouzia",
      price: "25",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 134,
      image: "/menu/photo.jpg",
      title: "Livadioti Estate White Dry",
      price: "25",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 135,
      image: "/menu/photo.jpg",
      title: "Iatridi Estate Ampelourgos Assyrtiko",
      price: "27",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 136,
      image: "/menu/photo.jpg",
      title: "Iatridi Estate White Wine",
      price: "25",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 137,
      image: "/menu/photo.jpg",
      title: "Konstantaras Estate Viognier Assyrtiko",
      price: "27",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 138,
      image: "/menu/photo.jpg",
      title: "Ktima Livadioti ( semi sweet )",
      price: "25",
      category: "Wine list",
      subCategory: "Dry White Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 140,
      image: "/menu/konstantara_merlot.jpg",
      title: "Konstantaras Estate Merlot",
      price: "25",
      category: "Wine list",
      subCategory: "Dry Red Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 141,
      image: "/menu/iatridi_estate_syrah.jpg",
      title: "Iatridi Estate Syrah - Mavrotragano",
      price: "32",
      category: "Wine list",
      subCategory: "Dry Red Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 150,
      image: "/menu/miraval.jpg",
      title: "Miraval",
      price: "28",
      category: "Wine list",
      subCategory: "Rose Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 151,
      image: "/menu/photo.jpg",
      title: "Iatridi Estate",
      price: "28",
      category: "Wine list",
      subCategory: "Rose Wines",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 152,
      image: "/menu/barafaka_roze.jpg",
      title: "Barafaka Estate Roze  ( semi sweet )",
      price: "25",
      category: "Wine list",
      subCategory: "Rose Wines",
      ingredients: "",
      sorting: "12",
    },
  ],
  el: [
    {
      id: 10,
      image: "/menu/potatos_fried.jpg",
      title: "Τηγανητές πατάτες",
      price: "4",
      category: "Ορεκτικό",
      ingredients: " ",
      sorting: "01",
    },
    {
      id: 11,
      image: "/menu/crispy_zucchini.jpg",
      title: "Τραγανό κολοκυθάκι",
      price: "4,5",
      category: "Ορεκτικό",
      ingredients: "με τζατζίκι",
      sorting: "01",
    },
    {
      id: 12,
      image: "/menu/photo.jpg",
      title: "Τηγανίτες τυριού",
      price: "5",
      category: "Ορεκτικό",
      ingredients: "με μέλι",
      sorting: "01",
    },
    {
      id: 13,
      image: "/menu/fried_feta.jpg",
      title: "Τηγανητή φέτα",
      price: "5",
      category: "Ορεκτικό",
      ingredients: "με γλυκό τσίλι ή μέλι",
      sorting: "01",
    },
    {
      id: 14,
      image: "/menu/photo.jpg",
      title: "Ψητή φέτα ",
      price: "5",
      category: "Ορεκτικό",
      ingredients: "στη σχάρα με ντομάτες",
      sorting: "01",
    },
    {
      id: 15,
      image: "/menu/hallumi_cheese.jpg",
      title: "Χαλούμι",
      price: "5,5",
      category: "Ορεκτικό",
      ingredients: "με μαρμελάδα φράουλα",
      sorting: "01",
    },
    {
      id: 16,
      image: "/menu/roasted_eggplant.jpg",
      title: "Ψητή μελιτζάνα",
      price: "5,6",
      category: "Ορεκτικό",
      ingredients: "με τριμμένες ντομάτες και φέτα",
      sorting: "01",
    },
    {
      id: 17,
      image: "/menu/photo.jpg",
      title: "Πιπεριά Φλωρίνης",
      price: "9",
      category: "Ορεκτικό",
      ingredients: "σχάρας",
      sorting: "01",
    },
    {
      id: 18,
      image: "/menu/photo.jpg",
      title: "Καπνιστό σκουμπρί",
      price: "7",
      category: "Ορεκτικό",
      ingredients: "σχάρας με λεμόνι και λάδι",
      sorting: "01",
    },
    {
      id: 19,
      image: "/menu/photo.jpg",
      title: "Αντζούγιες",
      price: "6",
      category: "Ορεκτικό",
      ingredients: "με ελιές",
      sorting: "01",
    },
    {
      id: 20,
      image: "/menu/tzatziki.jpg",
      title: "Τζατζίκι",
      price: "4,5",
      category: "Σπιτικές σαλάτες/Σάλτσες",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 21,
      image: "/menu/russian_salad.jpg",
      title: "Ρώσικη",
      price: "4,5",
      category: "Σπιτικές σαλάτες/Σάλτσες",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 22,
      image: "/menu/photo.jpg",
      title: "Κρεμώδης σάλτσα τυριού με πιπέρι",
      price: "4,5",
      category: "Σπιτικές σαλάτες/Σάλτσες",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 23,
      image: "/menu/photo.jpg",
      title: "Ουγγρέζικη",
      price: "4,5",
      category: "Σπιτικές σαλάτες/Σάλτσες",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 24,
      image: "/menu/photo.jpg",
      title: "Παπρικά",
      price: "4,5",
      category: "Σπιτικές σαλάτες/Σάλτσες",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 25,
      image: "/menu/photo.jpg",
      title: "Κοτόπουλο",
      price: "4,5",
      category: "Σπιτικές σαλάτες/Σάλτσες",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 26,
      image: "/menu/photo.jpg",
      title: "Καβούρι",
      price: "4,5",
      category: "Σπιτικές σαλάτες/Σάλτσες",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 30,
      image: "/menu/salad_ara_zo.jpg",
      title: "Αρα...ζω",
      price: "7,9",
      category: "Φρέσκες σαλάτες",
      ingredients:
        "με σπανάκι, λάχανο, μπέικον, μανιτάρια, βαλσαμική κρέμα και τυρί φαλαγκάνι",
      sorting: "03",
    },
    {
      id: 31,
      image: "/menu/cretan_salad.jpg",
      title: "Κρητική Σαλάτα",
      price: "7,9",
      category: "Φρέσκες σαλάτες",
      ingredients:
        "με τριμμένες ντομάτες, μηλόξυδο, κριθαρότο, ντοματίνια, κρητικά παξιμάδια και Κρητική φέτα",
      sorting: "03",
    },
    {
      id: 32,
      image: "/menu/photo.jpg",
      title: "Πράσινη σαλάτα",
      price: "7,7",
      category: "Φρέσκες σαλάτες",
      ingredients:
        "με μπέιμπι σπανάκι, ρόκα, σταφίδες, αρακά και κρεμώδες τυρί",
      sorting: "03",
    },
    {
      id: 33,
      image: "/menu/cesar_salad.jpg",
      title: "Σαλάτα Καίσαρα",
      price: "7,9",
      category: "Φρέσκες σαλάτες",
      ingredients:
        "με κοτόπουλο σχάρας, παρμεζάνα, κρουτόν, μπέικον, δροσερή σάλτσα λεμονιού και μαγιονέζας",
      sorting: "03",
    },
    {
      id: 34,
      image: "/menu/photo.jpg",
      title: "Vegan σαλάτα",
      price: "7,7",
      category: "Φρέσκες σαλάτες",
      ingredients:
        "με ποικιλία από λάχανα, κινόα, μάνγκο, ντοματίνια, καραμελωμένα καρύδια και βινεγκρέτ με ρόδι",
      sorting: "03",
    },
    {
      id: 35,
      image: "/menu/photo.jpg",
      title: "Ελληνική σαλάτα",
      price: "7,9",
      category: "Φρέσκες σαλάτες",
      ingredients:
        "με ντομάτες, αγγούρι, κρεμμύδι, κόκκινη και πράσινη πιπεριά, φέτα, μαϊντανό, ελιές, εξαιρετικό παρθένο ελαιόλαδο και κάπαρη",
      sorting: "03",
    },
    {
      id: 36,
      image: "/menu/photo.jpg",
      title: "Αγγουροντομάτα",
      price: "4,9",
      category: "Φρέσκες σαλάτες",
      ingredients: "με ντομάτες, αγγούρι, κρεμμύδι και λάδι",
      sorting: "03",
    },
    {
      id: 37,
      image: "/menu/salad_seasonal.jpg",
      title: "Εποχιακά χόρτα",
      price: "4,7",
      category: "Φρέσκες σαλάτες",
      ingredients: " ",
      sorting: "03",
    },
    {
      id: 40,
      image: "/menu/photo.jpg",
      title: "Μανιτάρια",
      price: "5,9",
      category: "Στο τηγάνι μας",
      ingredients: "σε τηγάνι",
      sorting: "04",
    },
    {
      id: 41,
      image: "/menu/shrimp_spaghetti.jpg",
      title: "Σπαγγέτι με γαρίδες",
      price: "19,4",
      category: "Στο τηγάνι μας",
      ingredients: "με φρέσκια κρεμώδη σάλτσα ντομάτας",
      sorting: "04",
    },
    {
      id: 50,
      image: "/menu/kebab_handmade.jpg",
      title: "Χειροποίητο κεμπάπ",
      price: "10",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 51,
      image: "/menu/saslik.jpg",
      title: "Χειροποίητο Σασλίκι",
      price: "11,9",
      category: "Στα κάρβουνά μας",
      ingredients: "(κοντοσούβλι) με κοτόπουλο ή χοιρινό",
      sorting: "05",
    },
    {
      id: 52,
      image: "/menu/photo.jpg",
      title: "Αρωματικό κεμπάπ",
      price: "7,6",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 53,
      image: "/menu/photo.jpg",
      title: "Φρεσκοψημένα κεφτεδάκια",
      price: "7,9",
      category: "Στα κάρβουνά μας",
      ingredients: "σχάρας με δυόσμο",
      sorting: "05",
    },
    {
      id: 54,
      image: "/menu/photo.jpg",
      title: "Παραδοσιακό λουκάνικο",
      price: "7,9",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 55,
      image: "/menu/grill_pancetta.jpg",
      title: "Πανσέτα σχάρας",
      price: "7,9",
      category: "Στα κάρβουνά μας",
      ingredients: "με λεμόνι και μουστάρδα",
      sorting: "05",
    },
    {
      id: 56,
      image: "/menu/greek_souvlaki.jpg",
      title: "Ελληνικό σουβλάκι",
      price: "7,9",
      category: "Στα κάρβουνά μας",
      ingredients: "χοιρινό ή κοτόπουλο (ξύλο)",
      sorting: "05",
    },
    {
      id: 57,
      image: "/menu/photo.jpg",
      title: "Μπριζόλα στη σχάρα",
      price: "13,4",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 58,
      image: "/menu/photo.jpg",
      title: "Χοιρινά παϊδάκια",
      price: "11,30",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 59,
      image: "/menu/lamb_ribs.jpg",
      title: "Παϊδάκια αρνιού",
      price: "16,9",
      category: "Στα κάρβουνά μας",
      ingredients: "με λεμόνι και ρίγανη",
      sorting: "05",
    },
    {
      id: 591,
      image: "/menu/photo.jpg",
      title: "Φιλέτο κοτόπουλου ή κοτομπουκιές",
      price: "8,6",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 592,
      image: "/menu/Burger.jpg",
      title: "Μπέργκερ",
      price: "10",
      category: "Στα κάρβουνά μας",
      ingredients:
        "μοσχαρίσιο κρέας, αισβεργία, ντομάτα, μπάρμπεκιου σάλτσα, τσένταρ και τηγανητές πατάτες",
      sorting: "05",
    },
    {
      id: 593,
      image: "/menu/photo.jpg",
      title: "Τι-Μπον",
      price: "27",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 594,
      image: "/menu/photo.jpg",
      title: "Γαλλικό ριμπάι",
      price: "29,3",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 595,
      image: "/menu/photo.jpg",
      title: "Μπαβέτ",
      price: "26",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 596,
      image: "/menu/photo.jpg",
      title: "Μοσχαρίσια μπριζόλα",
      price: "18,9",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 597,
      image: "/menu/photo.jpg",
      title: "Μπριζόλα ριμπάι",
      price: "22,3",
      category: "Στα κάρβουνά μας",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 60,
      image: "/menu/fried_squid.jpg",
      title: "Τηγανιτό καλαμάρι",
      price: "8,2",
      category: "Θαλασσινά",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 61,
      image: "/menu/grilled_octopus.jpg",
      title: "Χταπόδι σχάρας",
      price: "13,8",
      category: "Θαλασσινά",
      ingredients: "με μηλόξυδο",
      sorting: "06",
    },
    {
      id: 62,
      image: "/menu/photo.jpg",
      title: "Φρέσκο καλαμάρι",
      price: "19",
      category: "Θαλασσινά",
      ingredients: "στη σχάρα",
      sorting: "06",
    },
    {
      id: 63,
      image: "/menu/photo.jpg",
      title: "Μύδια",
      price: "9",
      category: "Θαλασσινά",
      ingredients: "στον ατμό",
      sorting: "06",
    },
    {
      id: 64,
      image: "/menu/photo.jpg",
      title: "Τηγανιτά μύδια",
      price: "9",
      category: "Θαλασσινά",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 65,
      image: "/menu/photo.jpg",
      title: "Μύδια",
      price: "9",
      category: "Θαλασσινά",
      ingredients: "στο τηγάνι με σάλτσα ντομάτας και πιπεριές",
      sorting: "06",
    },
    {
      id: 66,
      image: "/menu/Shrimps.jpg",
      title: "Γαρίδες",
      price: "19,2",
      category: "Θαλασσινά",
      ingredients: "στο τηγάνι με σάλτσα ντομάτας και πιπεριές",
      sorting: "06",
    },
    {
      id: 67,
      image: "/menu/shrimps_fried.jpg",
      title: "Γαρίδες σχάρας/τηγανιτές",
      price: "19",
      category: "Θαλασσινά",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 68,
      image: "/menu/anchovies_fried.jpg",
      title: "Φρέσκες τηγανιτές αντζούγιες",
      price: "12",
      category: "Θαλασσινά",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 69,
      image: "/menu/koutsomoures.jpg",
      title: "Κουτσομούρες",
      price: "15",
      category: "Θαλασσινά",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 70,
      image: "/menu/exquiste_meat.jpg",
      title: "Εκλεκτή ποικιλία κρεάτων για 2 άτομα",
      price: "18",
      category: "Εκλεκτά κρέατα",
      ingredients:
        "1 μερίδα (χοιρινό σουβλάκι, κοτόπουλο σουβλάκι σουτζουκάκια, λουκάνικο, κεφτεδάκι) 2 μερίδες πανσέτα",
      sorting: "07",
    },
    {
      id: 71,
      image: "/menu/exquiste_meat.jpg",
      title: "Εκλεκτή ποικιλία κρεάτων για 4 άτομα",
      price: "34",
      category: "Εκλεκτά κρέατα",
      ingredients:
        "2 μερίδες (χοιρινό σουβλάκι, κοτόπουλο σουβλάκι σουτζουκάκια, λουκάνικο, κεφτεδάκι) 4 μερίδες πανσέτα",
      sorting: "07",
    },
    {
      id: 80,
      image: "/menu/coca_cola.jpg",
      title: "Coca cola",
      price: "2",
      category: "Αναψυκτικά",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 81,
      image: "/menu/coca_cola_zero.jpg",
      title: "Coca cola zero",
      price: "2",
      category: "Αναψυκτικά",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 82,
      image: "/menu/fanta.jpg",
      title: "Fanta",
      price: "2",
      category: "Αναψυκτικά",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 83,
      image: "/menu/sprite.jpg",
      title: "Sprite",
      price: "2",
      category: "Αναψυκτικά",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 84,
      image: "/menu/fanta_lemon.jpg",
      title: "Fanta Λεμόνι",
      price: "2",
      category: "Αναψυκτικά",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 85,
      image: "/menu/sparkling_juices.jpg",
      title: "Ανθρακούχο νερό Χυμοί",
      price: "2",
      category: "Αναψυκτικά",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 86,
      image: "/menu/water_1l.jpg",
      title: "Νερό 1,0L",
      price: "1,5",
      category: "Αναψυκτικά",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 90,
      image: "/menu/beer_mythos.jpg",
      title: "Μύθος",
      price: "4",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 91,
      image: "/menu/beer_fix.jpg",
      title: "Fix Ελλάς",
      price: "4",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 92,
      image: "/menu/beer_fix_dark.jpg",
      title: "Fix dark",
      price: "4",
      category: "Μπύρες",
      ingredients: "",
      vsorting: "09",
    },
    {
      id: 93,
      image: "/menu/beer_fix_0.jpg",
      title: "Fix χωρίς αλκοόλ",
      price: "4",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 94,
      image: "/menu/beer_kaiser.jpg",
      title: "Kaiser",
      price: "4,5",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 95,
      image: "/menu/beer_carlsberg.jpg",
      title: "Carlsberg",
      price: "4,5",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 96,
      image: "/menu/beer_mythos_radler.jpg",
      title: "Μύθος Radler",
      price: "4",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 97,
      image: "/menu/beer_nimfi.jpg",
      title: "Νύμφη",
      price: "4,5",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 98,
      image: "/menu/beer_draft.jpg",
      title: "Βαρέλι 400ml",
      price: "5",
      category: "Μπύρες",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 100,
      image: "/menu/retsina_45rounds.jpg",
      title: "45 Γύροι",
      price: "5",
      category: "Ρετσίνες",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 101,
      image: "/menu/retsina_georgiadi.jpg",
      title: "Γεωργιάδη",
      price: "4",
      category: "Ρετσίνες",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 102,
      image: "/menu/retsina_malamatina.jpg",
      title: "Μαλαματίνα",
      price: "4",
      category: "Ρετσίνες",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 103,
      image: "/menu/retsina_kexribari.jpg",
      title: "Κεξημπάρι",
      price: "6,5",
      category: "Ρετσίνες",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 104,
      image: "/menu/retsina_vasiliki.jpg",
      title: "Βασιλική",
      price: "5",
      category: "Ρετσίνες",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 110,
      image: "/menu/draft_wines.jpg",
      title: "Χύμα κρασιά Χαλκιδικής",
      price: "6",
      category: "Τα κρασιά μας",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 111,
      image: "/menu/glass_wine.jpg",
      title: "Ποτήρι κρασί",
      price: "5,5",
      category: "Τα κρασιά μας",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 112,
      image: "/menu/bottles_wine.jpg",
      title: "Μπουκάλια",
      price: "20",
      category: "Τα κρασιά μας",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 120,
      image: "/menu/ouzo.jpg",
      title: "Ούζο",
      price: "8",
      category: "Ούζο/Τσίπουρο",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 121,
      image: "/menu/tsipouro_with_anice.jpg",
      title: "Τσίπουρο με ανίθο",
      price: "9",
      category: "Ούζο/Τσίπουρο",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 122,
      image: "/menu/tsipouro_without_anise.jpg",
      title: "Τσίπουρο χωρίς ανίθο",
      price: "9",
      category: "Ούζο/Τσίπουρο",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 123,
      image: "/menu/draft_tsipouro_with_anise.jpg",
      title: "Χύμα τσίπουρο με ανίθο",
      price: "7",
      category: "Ούζο/Τσίπουρο",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 124,
      image: "/menu/draft_tsipouro_without_anise.jpg",
      title: "Χύμα τσίπουρο χωρίς ανίθο",
      price: "7",
      category: "Ούζο/Τσίπουρο",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 130,
      image: "/menu/konstantara_sauvignon_blanc.jpg",
      title: "Κτήμα Κωνστανταρά Σοβινιόν Μπλαν",
      price: "30",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 131,
      image: "/menu/konstantara_malagouzia.jpg",
      title: "Κτήμα Κωνστανταρά Μαλαγουζιά",
      price: "30",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 132,
      image: "/menu/marmaromenos_vasilias.jpg",
      title: "Μαρμαρωμένος Βασιλιάς",
      price: "20",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 133,
      image: "/menu/photo.jpg",
      title: " Κτήμα Λειβαδιώτη Μαλαγουζιά",
      price: "25",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 134,
      image: "/menu/photo.jpg",
      title: "Κτήμα Λειβαδιώτη Λευκό ξηρό",
      price: "25",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 135,
      image: "/menu/photo.jpg",
      title: "Κτήμα Iατρίδη Αμπελούργος Ασσυρτικο",
      price: "27",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 136,
      image: "/menu/photo.jpg",
      title: "Κτήμα Iατρίδη  λευκό κρασί",
      price: "25",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 137,
      image: "/menu/photo.jpg",
      title: "Κτήμα Κωνστανταρά Viognier Ασσυριακός",
      price: "27",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 138,
      image: "/menu/photo.jpg",
      title: "Κτήμα Λειβαδιώτη (ημίγλυκος)",
      price: "25",
      category: "Κάβα κρασιών",
      subCategory: "Λευκά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 140,
      image: "/menu/konstantara_merlot.jpg",
      title: " Κτήμα Κωνστανταρά Μέρλοτ",
      price: "25",
      category: "Κάβα κρασιών",
      subCategory: "Ερυθρά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 141,
      image: "/menu/iatridi_estate_syrah.jpg",
      title: " Κτήμα Ιατρίδη Σιράχ Μαυροτράγανο",
      price: "32",
      category: "Κάβα κρασιών",
      subCategory: "Ερυθρά ξηρά κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 150,
      image: "/menu/miraval.jpg",
      title: "Miraval",
      price: "28",
      category: "Κάβα κρασιών",
      subCategory: "Ροζέ κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 151,
      image: "/menu/photo.jpg",
      title: "Κτήμα Iατρίδη Ροζέ ξηρος",
      price: "28",
      category: "Κάβα κρασιών",
      subCategory: "Ροζέ κρασιά",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 152,
      image: "/menu/barafaka_roze.jpg",
      title: "Κτήμα Μπαραφάκα Ροζέ (ημίγλυκο)",
      price: "25",
      category: "Κάβα κρασιών",
      subCategory: "Ροζέ κρασιά",
      ingredients: "",
      sorting: "12",
    },
  ],
  ru: [
    {
      id: 10,
      image: "/menu/potatos_fried.jpg",
      title: "Жареный картофель",
      price: "4",
      category: "Закуски",
      ingredients: " ",
      sorting: "01",
    },
    {
      id: 11,
      image: "/menu/crispy_zucchini.jpg",
      title: "Хрустящий цуккини",
      price: "4,5",
      category: "Закуски",
      ingredients: "с дзадзики",
      sorting: "01",
    },
    {
      id: 12,
      image: "/menu/photo.jpg",
      title: "Сырные пончики",
      price: "5",
      category: "Закуски",
      ingredients: "с медом",
      sorting: "01",
    },
    {
      id: 13,
      image: "/menu/fried_feta.jpg",
      title: "Жареный сыр фета",
      price: "5",
      category: "Закуски",
      ingredients: "с острым соусом чили или медом",
      sorting: "01",
    },
    {
      id: 14,
      image: "/menu/photo.jpg",
      title: "Запеченный сыр фета",
      price: "5",
      category: "Закуски",
      ingredients: "на решетке с помидорами",
      sorting: "01",
    },
    {
      id: 15,
      image: "/menu/hallumi_cheese.jpg",
      title: "Сыр халлуми",
      price: "5,5",
      category: "Закуски",
      ingredients: "с клубничным джемом",
      sorting: "01",
    },
    {
      id: 16,
      image: "/menu/roasted_eggplant.jpg",
      title: "Запеченный баклажан",
      price: "5,6",
      category: "Закуски",
      ingredients: "с тертыми помидорами и сыром фета",
      sorting: "01",
    },
    {
      id: 17,
      image: "/menu/photo.jpg",
      title: "Острый перец",
      price: "9",
      category: "Закуски",
      ingredients: "на гриле",
      sorting: "01",
    },
    {
      id: 18,
      image: "/menu/photo.jpg",
      title: "Копченая скумбрия",
      price: "7",
      category: "Закуски",
      ingredients: "на гриле с лимоном и маслом",
      sorting: "01",
    },
    {
      id: 19,
      image: "/menu/photo.jpg",
      title: "Анчоусы",
      price: "6",
      category: "Закуски",
      ingredients: "с оливками",
      sorting: "01",
    },
    {
      id: 20,
      image: "/menu/tzatziki.jpg",
      title: " Дзадзики",
      price: "4,5",
      category: "Домашние салаты/Соусы",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 21,
      image: "/menu/russian_salad.jpg",
      title: "Русский салат",
      price: "4,5",
      category: "Домашние салаты/Соусы",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 22,
      image: "/menu/photo.jpg",
      title: "Сырный острый крем",
      price: "4,5",
      category: "Домашние салаты/Соусы",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 23,
      image: "/menu/photo.jpg",
      title: "Венгерский салат",
      price: "4,5",
      category: "Домашние салаты/Соусы",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 24,
      image: "/menu/photo.jpg",
      title: "Паприка",
      price: "4,5",
      category: "Домашние салаты/Соусы",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 25,
      image: "/menu/photo.jpg",
      title: "Куриный салат",
      price: "4,5",
      category: "Домашние салаты/Соусы",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 26,
      image: "/menu/photo.jpg",
      title: "Крабовый",
      price: "4,5",
      category: "Домашние салаты/Соусы",
      ingredients: " ",
      sorting: "02",
    },
    {
      id: 30,
      image: "/menu/salad_ara_zo.jpg",
      title: "Αρα...ζω",
      price: "7,9",
      category: "Свежие салаты",
      ingredients:
        "со шпинатом, листовым салатом, беконом, грибами, бальзамическим кремом и сыром фалагани",
      sorting: "03",
    },
    {
      id: 31,
      image: "/menu/cretan_salad.jpg",
      title: "Критский салат",
      price: "7,9",
      category: "Свежие салаты",
      ingredients:
        "с тертыми помидорами, яблочным уксусом, брускеттой, помидорами, кримато и греческим сыром фета",
      sorting: "03",
    },
    {
      id: 32,
      image: "/menu/photo.jpg",
      title: "Зеленый салат",
      price: "7,7",
      category: "Свежие салаты",
      ingredients: "со шпинатом, рукколой, изюмом, свеклой и сырным кремом",
      sorting: "03",
    },
    {
      id: 33,
      image: "/menu/cesar_salad.jpg",
      title: "Цезарь с курицей",
      price: "7,9",
      category: "Свежие салаты",
      ingredients:
        "с курицей гриль, пармезаном, гренками, беконом, заправкой с лимоном и майонезом",
      sorting: "03",
    },
    {
      id: 34,
      image: "/menu/photo.jpg",
      title: "Веганский салат",
      price: "7,7",
      category: "Свежие салаты",
      ingredients:
        "с разнообразным листовым салатом, киноа, манго, помидорами черри, карамелизированным грецким орехом и винегретом с гранатом",
      sorting: "03",
    },
    {
      id: 35,
      image: "/menu/photo.jpg",
      title: "Греческий салат",
      price: "7,9",
      category: "Свежие салаты",
      ingredients:
        "с помидорами, огурцом, луком, красным и зеленым перцем, сыром фета, петрушкой, оливками, оливковым маслом и каперсами",
      sorting: "03",
    },
    {
      id: 36,
      image: "/menu/photo.jpg",
      title: "Аггоуротомата",
      price: "4,9",
      category: "Свежие салаты",
      ingredients: "с помидорами, огурцом, луком и маслом",
      sorting: "03",
    },
    {
      id: 37,
      image: "/menu/salad_seasonal.jpg",
      title: "Сезонная зелень",
      price: "4,7",
      category: "Свежие салаты",
      ingredients: " ",
      sorting: "03",
    },
    {
      id: 40,
      image: "/menu/photo.jpg",
      title: "Грибы",
      price: "5,9",
      category: "На нашей сковороде",
      ingredients: "на сковороде",
      sorting: "04",
    },
    {
      id: 41,
      image: "/menu/shrimp_spaghetti.jpg",
      title: "Спагетти с креветками",
      price: "19,4",
      category: "На нашей сковороде",
      ingredients: "со свежим томатным соусом",
      sorting: "04",
    },
    {
      id: 50,
      image: "/menu/kebab_handmade.jpg",
      title: "Домашний кебаб",
      price: "10",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 51,
      image: "/menu/saslik.jpg",
      title: "Домашний шашлык",
      price: "11,9",
      category: "На наших углях",
      ingredients: "( kontosouvli) с курицей или свининой",
      sorting: "05",
    },
    {
      id: 52,
      image: "/menu/photo.jpg",
      title: "Ароматный кебаб",
      price: "7,6",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 53,
      image: "/menu/photo.jpg",
      title: "Свежие мясные шарики",
      price: "7,9",
      category: "На наших углях",
      ingredients: "на гриле с мятой",
      sorting: "05",
    },
    {
      id: 54,
      image: "/menu/photo.jpg",
      title: "Традиционная колбаса",
      price: "7,9",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 55,
      image: "/menu/grill_pancetta.jpg",
      title: "Гриль панчетта",
      price: "7,9",
      category: "На наших углях",
      ingredients: "с лимоном и горчицей",
      sorting: "05",
    },
    {
      id: 56,
      image: "/menu/greek_souvlaki.jpg",
      title: "Греческий сувлаки",
      price: "7,9",
      category: "На наших углях",
      ingredients: "свинина или курица (на шампуре)",
      sorting: "05",
    },
    {
      id: 57,
      image: "/menu/photo.jpg",
      title: "Стейк на гриле",
      price: "13,4",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 58,
      image: "/menu/photo.jpg",
      title: "Свиные ребрышки",
      price: "11,30",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 59,
      image: "/menu/lamb_ribs.jpg",
      title: "Бараньи ребрышки",
      price: "16,9",
      category: "На наших углях",
      ingredients: "с лимоном и орегано",
      sorting: "05",
    },
    {
      id: 591,
      image: "/menu/photo.jpg",
      title: "Куриные орешки или куриная грудка",
      price: "8,6",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 592,
      image: "/menu/Burger.jpg",
      title: "Бургер",
      price: "10",
      category: "На наших углях",
      ingredients:
        "говяжий фарш, айсберг, помидор, барбекю соус, чеддер и картофель фри",
      sorting: "05",
    },
    {
      id: 593,
      image: "/menu/photo.jpg",
      title: "Ти-Боун",
      price: "27",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 594,
      image: "/menu/photo.jpg",
      title: "Французский рибай",
      price: "29,3",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 595,
      image: "/menu/photo.jpg",
      title: "Баветт",
      price: "26",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 596,
      image: "/menu/photo.jpg",
      title: "Говяжий стейк",
      price: "18,9",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 597,
      image: "/menu/photo.jpg",
      title: "Стейк рибай",
      price: "22,3",
      category: "На наших углях",
      ingredients: "",
      sorting: "05",
    },
    {
      id: 60,
      image: "/menu/fried_squid.jpg",
      title: "Жареный кальмар",
      price: "8,2",
      category: "Морепродукты",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 61,
      image: "/menu/grilled_octopus.jpg",
      title: "Жареный осьминог",
      price: "13,8",
      category: "Морепродукты",
      ingredients: "с яблочным уксусом",
      sorting: "06",
    },
    {
      id: 62,
      image: "/menu/photo.jpg",
      title: "Свежий кальмар",
      price: "19",
      category: "Морепродукты",
      ingredients: "на гриле",
      sorting: "06",
    },
    {
      id: 63,
      image: "/menu/photo.jpg",
      title: "Мидии",
      price: "9",
      category: "Морепродукты",
      ingredients: "на пару",
      sorting: "06",
    },
    {
      id: 64,
      image: "/menu/photo.jpg",
      title: "Жареные мидии",
      price: "9",
      category: "Морепродукты",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 65,
      image: "/menu/photo.jpg",
      title: "Мидии",
      price: "9",
      category: "Морепродукты",
      ingredients: "на сковороде с томатным соусом и перцем",
      sorting: "06",
    },
    {
      id: 66,
      image: "/menu/Shrimps.jpg",
      title: "Креветки",
      price: "19,2",
      category: "Морепродукты",
      ingredients: "на сковороде с томатным соусом и перцем",
      sorting: "06",
    },
    {
      id: 67,
      image: "/menu/shrimps_fried.jpg",
      title: "Креветки гриль/жареные",
      price: "19",
      category: "Морепродукты",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 68,
      image: "/menu/anchovies_fried.jpg",
      title: "Свежие жареные анчоусы",
      price: "12",
      category: "Морепродукты",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 69,
      image: "/menu/koutsomoures.jpg",
      title: "Куцомурес",
      price: "15",
      category: "Морепродукты",
      ingredients: "",
      sorting: "06",
    },
    {
      id: 70,
      image: "/menu/exquiste_meat.jpg",
      title: "Изысканное мясное ассорти для 2 человек",
      price: "18",
      category: "Изысканное мясо",
      ingredients:
        "1 шт. (свиной сувлаки, куриный сувлаки soutzoukaki, колбаса, мясной шарик) 2 шт. панчетта",
      sorting: "07",
    },
    {
      id: 71,
      image: "/menu/exquiste_meat.jpg",
      title: "Изысканное мясное ассорти для 4 человек",
      price: "34",
      category: "Изысканное мясо",
      ingredients:
        "2 шт. (свиной сувлаки, куриный сувлаки soutzoukaki, колбаса, мясной шарик) 4 шт. панчетта",
      sorting: "07",
    },
    {
      id: 80,
      image: "/menu/coca_cola.jpg",
      title: "Кока-кола",
      price: "2",
      category: "Напитки",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 81,
      image: "/menu/coca_cola_zero.jpg",
      title: "Кока-кола zero",
      price: "2",
      category: "Напитки",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 82,
      image: "/menu/fanta.jpg",
      title: "Фанта",
      price: "2",
      category: "Напитки",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 83,
      image: "/menu/sprite.jpg",
      title: "Спрайт",
      price: "2",
      category: "Напитки",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 84,
      image: "/menu/fanta_lemon.jpg",
      title: "Фанта лимон",
      price: "2",
      category: "Напитки",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 85,
      image: "/menu/sparkling_juices.jpg",
      title: "Газированные соки",
      price: "2",
      category: "Напитки",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 86,
      image: "/menu/water_1l.jpg",
      title: "Вода 1,0Л",
      price: "1,5",
      category: "Напитки",
      ingredients: "",
      sorting: "08",
    },
    {
      id: 90,
      image: "/menu/beer_mythos.jpg",
      title: "Мифос",
      price: "4",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 91,
      image: "/menu/beer_fix.jpg",
      title: "Фикс Эллас",
      price: "4",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 92,
      image: "/menu/beer_fix_dark.jpg",
      title: "Фикс темное",
      price: "4",
      category: "Пиво",
      ingredients: "",
      vsorting: "09",
    },
    {
      id: 93,
      image: "/menu/beer_fix_0.jpg",
      title: "Фикс безалкогольное",
      price: "4",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 94,
      image: "/menu/beer_kaiser.jpg",
      title: "Кайзер",
      price: "4,5",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 95,
      image: "/menu/beer_carlsberg.jpg",
      title: "Карлсберг",
      price: "4,5",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 96,
      image: "/menu/beer_mythos_radler.jpg",
      title: "Мифос Радлер",
      price: "4",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 97,
      image: "/menu/beer_nimfi.jpg",
      title: "Нимфи",
      price: "4,5",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 98,
      image: "/menu/beer_draft.jpg",
      title: "Разливное 400мл",
      price: "5",
      category: "Пиво",
      ingredients: "",
      sorting: "09",
    },
    {
      id: 100,
      image: "/menu/retsina_45rounds.jpg",
      title: "45 Rounds",
      price: "5",
      category: "Рецина",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 101,
      image: "/menu/retsina_georgiadi.jpg",
      title: "Георгиади",
      price: "4",
      category: "Рецина",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 102,
      image: "/menu/retsina_malamatina.jpg",
      title: "Маламатина",
      price: "4",
      category: "Рецина",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 103,
      image: "/menu/retsina_kexribari.jpg",
      title: "Кексрибари",
      price: "6,5",
      category: "Рецина",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 104,
      image: "/menu/retsina_vasiliki.jpg",
      title: "Василики",
      price: "5",
      category: "Рецина",
      ingredients: "",
      sorting: "10",
    },
    {
      id: 110,
      image: "/menu/draft_wines.jpg",
      title: "Разливные вина Халкидики",
      price: "6",
      category: "Наши вина",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 111,
      image: "/menu/glass_wine.jpg",
      title: "Бокал вина",
      price: "5,5",
      category: "Наши вина",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 112,
      image: "/menu/bottles_wine.jpg",
      title: "Бутылка вина",
      price: "20",
      category: "Наши вина",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 120,
      image: "/menu/ouzo.jpg",
      title: "Узо",
      price: "8",
      category: "Узо/Ципуро",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 121,
      image: "/menu/tsipouro_with_anice.jpg",
      title: "Ципуро с анисом",
      price: "9",
      category: "Узо/Ципуро",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 122,
      image: "/menu/tsipouro_without_anise.jpg",
      title: "Ципуро без аниса",
      price: "9",
      category: "Узо/Ципуро",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 123,
      image: "/menu/draft_tsipouro_with_anise.jpg",
      title: "Разливное ципуро с анисом",
      price: "7",
      category: "Узо/Ципуро",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 124,
      image: "/menu/draft_tsipouro_without_anise.jpg",
      title: "Разливное ципуро без аниса",
      price: "7",
      category: "Узо/Ципуро",
      ingredients: "",
      sorting: "11",
    },
    {
      id: 130,
      image: "/menu/konstantara_sauvignon_blanc.jpg",
      title: "Константарас Эстейт Совиньон Блан",
      price: "30",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 131,
      image: "/menu/konstantara_malagouzia.jpg",
      title: "Константарас Эстейт Малагузия",
      price: "30",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 132,
      image: "/menu/marmaromenos_vasilias.jpg",
      title: "Мармароменос Василиас",
      price: "20",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 133,
      image: "/menu/photo.jpg",
      title: "Ливадиоти Эстейт Малагузия",
      price: "25",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 134,
      image: "/menu/photo.jpg",
      title: "Ливадиоти Эстейт сухое белое",
      price: "25",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 135,
      image: "/menu/photo.jpg",
      title: "Иатриди Эстейт Ампелургос Асиртико",
      price: "27",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 136,
      image: "/menu/photo.jpg",
      title: "Иатриди Эстейт белое вино",
      price: "25",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 137,
      image: "/menu/photo.jpg",
      title: "Константарас Эстейт Вионье Асиртико",
      price: "27",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 138,
      image: "/menu/photo.jpg",
      title: "Ктима Ливадиоти (полусладкое)",
      price: "25",
      category: "Винная карта",
      subCategory: "Сухие белые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 140,
      image: "/menu/konstantara_merlot.jpg",
      title: "Константарас Эстейт Мерло",
      price: "25",
      category: "Винная карта",
      subCategory: "Сухие красные вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 141,
      image: "/menu/iatridi_estate_syrah.jpg",
      title: "Иатриди Эстейт Сира - Мавротрагано",
      price: "32",
      category: "Винная карта",
      subCategory: "Сухие красные вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 150,
      image: "/menu/miraval.jpg",
      title: "Мираваль",
      price: "28",
      category: "Винная карта",
      subCategory: "Розовые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 151,
      image: "/menu/photo.jpg",
      title: "Иатриди Эстейт",
      price: "28",
      category: "Винная карта",
      subCategory: "Розовые вина",
      ingredients: "",
      sorting: "12",
    },
    {
      id: 152,
      image: "/menu/barafaka_roze.jpg",
      title: "Барафака Эстейт Розе (полусладкое)",
      price: "25",
      category: "Винная карта",
      subCategory: "Розовые вина",
      ingredients: "",
      sorting: "12",
    },
  ],
};
