export const enBloom = [
  {
    menuNumber: 1,
    image: "/menu/bloom/photo.png",
    title: "TORTILLA",
    price: "8.50",
    category: "FOOD",
    subCategory: null,
    ingredients:
      "chicken breast, gouda, bacon served with country fries and ceasar sauce",
  },
  {
    menuNumber: 2,
    image: "/menu/bloom/2.png",
    title: "CHICKEN NUGGETS",
    price: "7.50",
    category: "FOOD",
    subCategory: null,
    ingredients: "served with country fries and caesar sauce or sweet chilly",
  },
  {
    menuNumber: 3,
    image: "/menu/bloom/3.png",
    title: "CHEESE BURGER",
    price: "9.00",
    category: "FOOD",
    subCategory: null,
    ingredients:
      "letucce, tomato, bacon, cheddar, onions, mayonnaise served with country fries and ceaser sauce",
  },
  {
    menuNumber: 4,
    image: "/menu/bloom/4.png",
    title: "CHICKEN BURGER",
    price: "9.50",
    category: "FOOD",
    subCategory: null,
    ingredients:
      "letucce, nomato, bacon, onions, mayonnaise served with country fries and ceaser sauce",
  },
  {
    menuNumber: 5,
    image: "/menu/bloom/5.png",
    title: "CHICKEN CLUB",
    price: "9.00",
    category: "FOOD",
    subCategory: null,
    ingredients:
      "fluffy bread, mayonnaise, bacon, chicken, letucce gouda, tomato  served with country fries and ceasar sauce",
  },
  {
    menuNumber: 6,
    image: "/menu/bloom/6.png",
    title: "PIZZA SPECIAL 830gr",
    price: "11.00",
    category: "FOOD",
    subCategory: null,
    ingredients: "mozzarelle, tomato, sauce, green pepper, bacon",
  },
  {
    menuNumber: 7,
    image: "/menu/bloom/7.png",
    title: "PIZZA MARGARITA 730gr",
    price: "10.00",
    category: "FOOD",
    subCategory: null,
    ingredients: "tomato, sauce, gouda",
  },
  {
    menuNumber: 8,
    image: "/menu/bloom/8.png",
    title: "CAESAR SALAD",
    price: "8.00",
    category: "FOOD",
    subCategory: null,
    ingredients:
      "iceberg, cherry tomatoes, caesar sauce, chicken, parmesan, crouton",
  },
  {
    menuNumber: 9,
    image: "/menu/bloom/9.png",
    title: "FRUITSALAD",
    price: "8.00",
    category: "FOOD",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 10,
    image: "/menu/bloom/10.png",
    title: "TOAST CAESAR",
    price: "5.00",
    category: "FOOD",
    subCategory: null,
    ingredients: "gouda-ham with chips",
  },
  {
    menuNumber: 101,
    image: "/menu/bloom/10photo.png",
    title: "FREDDO ESPRESSO",
    price: "5.00",
    category: "COFFEE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 102,
    image: "/menu/bloom/12.png",
    title: "FREDDO CAPPUCHINO",
    price: "5.00",
    category: "COFFEE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 103,
    image: "/menu/bloom/13.png",
    title: "FRAPPE",
    price: "5.00",
    category: "COFFEE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 104,
    image: "/menu/bloom/14.png",
    title: "DECAFFEINE",
    price: "5.00",
    category: "COFFEE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 105,
    image: "/menu/bloom/15.png",
    title: "CHOCOLATE",
    price: "5.00",
    category: "COFFEE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 201,
    image: "/menu/bloom/16.png",
    title: "VIENNOIS",
    price: "5.50",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 202,
    image: "/menu/bloom/photo.png",
    title: "ESPRESSO",
    price: "4.50",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 203,
    image: "/menu/bloom/photo.png",
    title: "DOUBLE ESPRESSO",
    price: "5.00",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 204,
    image: "/menu/bloom/photo.png",
    title: "CAPPUCHINO",
    price: "5.00",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 205,
    image: "/menu/bloom/photo.png",
    title: "DOUBLE CAPPUCCINO",
    price: "5.50",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 206,
    image: "/menu/bloom/photo.png",
    title: "NESCAFE",
    price: "5.00",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 207,
    image: "/menu/bloom/photo.png",
    title: "GREEK COFFEE",
    price: "4.50",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 208,
    image: "/menu/bloom/photo.png",
    title: "DOUBLE GREEK COFFEE",
    price: "5.00",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 209,
    image: "/menu/bloom/photo.png",
    title: "AMERICANO",
    price: "4.50",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 210,
    image: "/menu/bloom/photo.png",
    title: "DOUBLE AMERICANO",
    price: "5.00",
    category: "CHOCOLATE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 301,
    image: "/menu/bloom/photo.png",
    title: "FRESH ORANGE JUICE",
    price: "5.50",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 302,
    image: "/menu/bloom/photo.png",
    title: "ORANGE JUICE",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 303,
    image: "/menu/bloom/photo.png",
    title: "CHERRY JUICE",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 304,
    image: "/menu/bloom/photo.png",
    title: "BANANA JUICE",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 305,
    image: "/menu/bloom/photo.png",
    title: "PINEAPPLE JUICE",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 306,
    image: "/menu/bloom/photo.png",
    title: "PEACH JUICE",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 307,
    image: "/menu/bloom/photo.png",
    title: "MIXED JUICE",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 308,
    image: "/menu/bloom/photo.png",
    title: "COLD TEA PEACH",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 309,
    image: "/menu/bloom/photo.png",
    title: "COLD TEA LEMON",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 310,
    image: "/menu/bloom/photo.png",
    title: "COLD TEA GREEN",
    price: "5.00",
    category: "JUCES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 401,
    image: "/menu/bloom/photo.png",
    title: "COCA COLA",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 402,
    image: "/menu/bloom/photo.png",
    title: "COCA COLA ZERO",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 403,
    image: "/menu/bloom/photo.png",
    title: "COCA COLA LIGHT",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 404,
    image: "/menu/bloom/photo.png",
    title: "LEMONADA",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 405,
    image: "/menu/bloom/photo.png",
    title: "PORTOKALA",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 406,
    image: "/menu/bloom/photo.png",
    title: "SPRITE",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 407,
    image: "/menu/bloom/photo.png",
    title: "PERRIER",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 408,
    image: "/menu/bloom/photo.png",
    title: "THREE CENTS PINK",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 409,
    image: "/menu/bloom/photo.png",
    title: "SOUROTI ",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "330ml",
  },
  {
    menuNumber: 409,
    image: "/menu/bloom/photo.png",
    title: "SOUROTI",
    price: "5.00",
    category: "REFRESHMENTS",
    subCategory: null,
    ingredients: "330ml",
  },
  {
    menuNumber: 501,
    image: "/menu/bloom/photo.png",
    title: "STRAWBERRY",
    price: "5.00",
    category: "GRANITE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 502,
    image: "/menu/bloom/photo.png",
    title: "LEMON",
    price: "5.00",
    category: "GRANITE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 503,
    image: "/menu/bloom/photo.png",
    title: "WATERLEMON",
    price: "5.00",
    category: "GRANITE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 601,
    image: "/menu/bloom/photo.png",
    title: "RED BULL",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 602,
    image: "/menu/bloom/photo.png",
    title: "SMIRNOFF ICE",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "275 ml",
  },
  {
    menuNumber: 603,
    image: "/menu/bloom/photo.png",
    title: "GORDON`S SPACE",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "275 ml ",
  },
  {
    menuNumber: 604,
    image: "/menu/bloom/photo.png",
    title: "BREEZER (LEMON/WATERLEMON) ",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 701,
    image: "/menu/bloom/photo.png",
    title: "FIX SMALL DRAUGHT BEER",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "330ml",
  },
  {
    menuNumber: 702,
    image: "/menu/bloom/photo.png",
    title: "FIX BIG DRAUGHT BEER",
    price: "6.00",
    category: "BEERS",
    subCategory: null,
    ingredients: "500ml",
  },
  {
    menuNumber: 703,
    image: "/menu/bloom/photo.png",
    title: "CORONA",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 704,
    image: "/menu/bloom/photo.png",
    title: "SOL",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 705,
    image: "/menu/bloom/photo.png",
    title: "MYTHOS",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 706,
    image: "/menu/bloom/photo.png",
    title: "ALPHA",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 707,
    image: "/menu/bloom/photo.png",
    title: "KAISER",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 708,
    image: "/menu/bloom/photo.png",
    title: "HEINEKEN",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 709,
    image: "/menu/bloom/photo.png",
    title: "HEINEKEN ZERO",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 801,
    image: "/menu/bloom/photo.png",
    title: "WHITE SEMI SWEET",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 802,
    image: "/menu/bloom/photo.png",
    title: "RED SEMI SWEET",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 803,
    image: "/menu/bloom/photo.png",
    title: "RED SANGRIA",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 804,
    image: "/menu/bloom/photo.png",
    title: "WHITE SANGRIA",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 805,
    image: "/menu/bloom/photo.png",
    title: "MALAGOUZIA",
    price: "40.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 806,
    image: "/menu/bloom/photo.png",
    title: "TECHNI ALEPIAS",
    price: "40.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 901,
    image: "/menu/bloom/photo.png",
    title: "PLOMARY",
    price: "8.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "200ml",
  },
  {
    menuNumber: 902,
    image: "/menu/bloom/photo.png",
    title: "IDONIKO WITHOUT",
    price: "9.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "200ml",
  },
  {
    menuNumber: 903,
    image: "/menu/bloom/photo.png",
    title: "SHOT",
    price: "3.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 904,
    image: "/menu/bloom/photo.png",
    title: "SUBMARINE",
    price: "4.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1001,
    image: "/menu/bloom/photo.png",
    title: "SMIRNOFF",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1002,
    image: "/menu/bloom/photo.png",
    title: "ABSOLUT",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1003,
    image: "/menu/bloom/photo.png",
    title: "SERKOVA",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1004,
    image: "/menu/bloom/photo.png",
    title: "STOLICHNAYA",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1005,
    image: "/menu/bloom/photo.png",
    title: "GREY GOOSE",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1006,
    image: "/menu/bloom/photo.png",
    title: "BELUGA",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1007,
    image: "/menu/bloom/photo.png",
    title: "BELVEDERE",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1008,
    image: "/menu/bloom/photo.png",
    title: "CIROC",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1101,
    image: "/menu/bloom/photo.png",
    title: "GORDONS",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1102,
    image: "/menu/bloom/photo.png",
    title: "GORDONS PINK",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1103,
    image: "/menu/bloom/photo.png",
    title: "TANGUERAY",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1104,
    image: "/menu/bloom/photo.png",
    title: "TANGUERAY",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1105,
    image: "/menu/bloom/photo.png",
    title: "BEEFEATER",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1106,
    image: "/menu/bloom/photo.png",
    title: "BOMBAY BLUE",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1107,
    image: "/menu/bloom/photo.png",
    title: "HENDRICKS",
    price: "10.00",
    price1: "100.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1201,
    image: "/menu/bloom/photo.png",
    title: "CUERVO SILVER",
    price: "8.00",
    price1: "80.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1202,
    image: "/menu/bloom/photo.png",
    title: "CUERVO REPASADO",
    price: "8.00",
    price1: "80.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1203,
    image: "/menu/bloom/photo.png",
    title: "DON JULIO REPASADO",
    price: "10.00",
    price1: "100.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1204,
    image: "/menu/bloom/photo.png",
    title: "DON JULIO BLANCO",
    price: "10.00",
    price1: "100.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1301,
    image: "/menu/bloom/photo.png",
    title: "JAMESON",
    price: "8.00",
    price1: "80.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1302,
    image: "/menu/bloom/photo.png",
    title: "JOHNNIE RED",
    price: "8.00",
    price1: "80.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1303,
    image: "/menu/bloom/photo.png",
    title: "JOHNNIE BLACK",
    price: "9.00",
    price1: "90.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1304,
    image: "/menu/bloom/photo.png",
    title: "CHIVAS 12",
    price: "9.00",
    price1: "90.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1305,
    image: "/menu/bloom/photo.png",
    title: "CARDHU",
    price: "9.00",
    price1: "90.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1306,
    image: "/menu/bloom/photo.png",
    title: "HAIG",
    price: "8.00",
    price1: "80.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1307,
    image: "/menu/bloom/photo.png",
    title: "JACK DANIELS",
    price: "9.00",
    price1: "90.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1308,
    image: "/menu/bloom/photo.png",
    title: "FAMOUS",
    price: "8.00",
    price1: "80.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1401,
    image: "/menu/bloom/photo.png",
    title: "BACARDI",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1402,
    image: "/menu/bloom/photo.png",
    title: "BACARDI BLACK",
    price: "9.00",
    price1: "90.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1403,
    image: "/menu/bloom/photo.png",
    title: "HAVANA 3*",
    price: "8.00",
    price1: "80.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1404,
    image: "/menu/bloom/photo.png",
    title: "HAVANA 7*",
    price: "9.00",
    price1: "90.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1405,
    image: "/menu/bloom/photo.png",
    title: "HAVANA BLACK",
    price: "9.00",
    price1: "90.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1406,
    image: "/menu/bloom/photo.png",
    title: "ZACAPA 23",
    price: "10.00",
    price1: "100.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1407,
    image: "/menu/bloom/photo.png",
    title: "CAPTAIN MORGAN",
    price: "8.00",
    price1: "80.00",
    category: "WHISKEY/RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1501,
    image: "/menu/bloom/photo.png",
    title: "MASTIHA",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1502,
    image: "/menu/bloom/photo.png",
    title: "COINTREAU",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1503,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1504,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1505,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1506,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1507,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1508,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1509,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1510,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1511,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1512,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1513,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1514,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1515,
    image: "/menu/bloom/photo.png",
    title: "Liquor",
    price: "8.00",
    price1: "80.00",
    category: "LIQUOR",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1601,
    image: "/menu/bloom/photo.png",
    title: "METAXA 3*",
    price: "8.00",
    price1: "80.00",
    category: "KONIAK",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1602,
    image: "/menu/bloom/photo.png",
    title: "METAXA 5*",
    price: "9.00",
    price1: "90.00",
    category: "KONIAK",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1603,
    image: "/menu/bloom/photo.png",
    title: "HENESSY",
    price: "9.00",
    price1: "90.00",
    category: "KONIAK",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1701,
    image: "/menu/bloom/photo.png",
    title: "MOSCHATO D'ASTI",
    price: "6.00",
    price1: "50.00",
    category: "SHAMPAGNE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1702,
    image: "/menu/bloom/photo.png",
    title: "MOSCHATO ROZE ASTI",
    price: "6.00",
    price1: "50.00",
    category: "SHAMPAGNE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1703,
    image: "/menu/bloom/photo.png",
    title: "MARTINI ASTIN",
    price: "6.00",
    price1: "50.00",
    category: "SHAMPAGNE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1704,
    image: "/menu/bloom/photo.png",
    title: "BOTTEGA PROSSECCO",
    price: "6.00",
    price1: "50.00",
    category: "SHAMPAGNE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1705,
    image: "/menu/bloom/photo.png",
    title: "MOET ICE",
    price: "150.00",
    price1: "",
    category: "SHAMPAGNE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1706,
    image: "/menu/bloom/photo.png",
    title: "MOET ROZE",
    price: "150.00",
    price1: "",
    category: "SHAMPAGNE",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1801,
    image: "/menu/bloom/photo.png",
    title: "SMALL BOTTLED WATER",
    price: "0.50",
    price1: "",
    category: "WATER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1802,
    image: "/menu/bloom/photo.png",
    title: "LARGE BOTTLED WATER",
    price: "0.50",
    price1: "",
    category: "WATER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1901,
    image: "/menu/bloom/photo.png",
    title: "MOJITO",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "with any flavour",
  },
  {
    menuNumber: 1902,
    image: "/menu/bloom/photo.png",
    title: "MARAGARITA",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1903,
    image: "/menu/bloom/photo.png",
    title: "DAIQUIRI",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "with any flavour",
  },
  {
    menuNumber: 1904,
    image: "/menu/bloom/photo.png",
    title: "SEX ON THE BEACH",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1905,
    image: "/menu/bloom/photo.png",
    title: "PORN STAR MARTINI",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1906,
    image: "/menu/bloom/photo.png",
    title: "ZOMBIE",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1907,
    image: "/menu/bloom/photo.png",
    title: "GIN BASIL SMASH",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1908,
    image: "/menu/bloom/photo.png",
    title: "OLD FASHIONED",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1909,
    image: "/menu/bloom/photo.png",
    title: "MAI TAI",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1910,
    image: "/menu/bloom/photo.png",
    title: "PINA COLADA",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1911,
    image: "/menu/bloom/photo.png",
    title: "TEQUILA SUNRISE",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1912,
    image: "/menu/bloom/photo.png",
    title: "APEROL SPRITZ",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1913,
    image: "/menu/bloom/photo.png",
    title: "COSMOPOLITAN",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1914,
    image: "/menu/bloom/photo.png",
    title: "CUBA LIBRE",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "CLASSIC COCKTAILS",
    ingredients: "",
  },
  {
    menuNumber: 1915,
    image: "/menu/bloom/photo.png",
    title: "BLOOM",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "SIGNATURE COCKTAILS",
    ingredients:
      "gin, passion puree, vanilla syrup, lime juice, ginger syrup, mantarine bitters, basil leaves",
  },
  {
    menuNumber: 1916,
    image: "/menu/bloom/photo.png",
    title: "LOST IN GREECE",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "SIGNATURE COCKTAILS",
    ingredients:
      "ouzo, pineapple juice, lime juice, mango puree, sugar syrup, bergamot bitters, grenadine, blue curacao",
  },
  {
    menuNumber: 1917,
    image: "/menu/bloom/photo.png",
    title: "BETTER TOGETHER",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "SIGNATURE COCKTAILS",
    ingredients:
      "brugal anejo, bacardi, orange juice, lime juice, strawberry puree, ginger syrup, vanilla cherry bitters",
  },
  {
    menuNumber: 1918,
    image: "/menu/bloom/photo.png",
    title: "ROMEO & JULIET",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "SIGNATURE COCKTAILS",
    ingredients:
      " vodka, dragon puree,lime juice, ginger syrup, orange bitters ",
  },
  {
    menuNumber: 1919,
    image: "/menu/bloom/photo.png",
    title: "THE GREEK KISS",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "SIGNATURE COCKTAILS",
    ingredients:
      "mastiha liquor, orange juice, pineapple juice, lime juice, mantarine itters, grenadine",
  },
  {
    menuNumber: 1920,
    image: "/menu/bloom/photo.png",
    title: "WELCOME TO PARADISE",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "SIGNATURE COCKTAILS",
    ingredients:
      "brugal anejo, pineapple juice, lime juice, caramela syrup, passion puree, chocolate bitters",
  },
  {
    menuNumber: 1921,
    image: "/menu/bloom/photo.png",
    title: "IT'S ALL GREEK TO ME",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "SIGNATURE COCKTAILS",
    ingredients:
      "gin, mastiha liquor, lime juice, agave syrup, bergamot bitters, lemonade",
  },
  {
    menuNumber: 1922,
    image: "/menu/bloom/photo.png",
    title: "YOU & ME",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILS",
    ingredients:
      "vanilla syrup, strawberry puree, passion puree, lime juice, spearmints leaves, pink soda",
  },
  {
    menuNumber: 1923,
    image: "/menu/bloom/photo.png",
    title: "SUMMER BLOOMER",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILS",
    ingredients:
      "pineapple juice, orange juice, peach juice, lime juice, coconut puree",
  },
  {
    menuNumber: 1924,
    image: "/menu/bloom/photo.png",
    title: "SWEET ON YOU",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILS",
    ingredients:
      "orange juice, lime juice, strawberry juice, sugar syrup grenadine",
  },
  {
    menuNumber: 1925,
    image: "/menu/bloom/photo.png",
    title: "NOJITO",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILS",
    ingredients:
      " fresh lime, brown sugar, lime juice sugar syrup, fresh spearmint leaves, soda ",
  },
  {
    menuNumber: 2001,
    image: "/menu/bloom/photo.png",
    title: " SMOOTHIES  01",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Strawberry, peach, banana",
  },
  {
    menuNumber: 2002,
    image: "/menu/bloom/photo.png",
    title: " SMOOTHIES  02",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Strawberry, mango, melon",
  },
  {
    menuNumber: 2003,
    image: "/menu/bloom/photo.png",
    title: " SMOOTHIES  03",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Pear, mango, pineapple",
  },
  {
    menuNumber: 2004,
    image: "/menu/bloom/photo.png",
    title: " SMOOTHIES  08",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Avocando, kale, lemon zest, banana",
  },
  {
    menuNumber: 2005,
    image: "/menu/bloom/photo.png",
    title: " SMOOTHIES  09",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Dragon fruit, lime, banana, mango",
  },
  {
    menuNumber: 2006,
    image: "/menu/bloom/photo.png",
    title: " SMOOTHIES  11",
    price: "6.00",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Biscuit, vegan cream",
  },
  {
    menuNumber: 2007,
    image: "/menu/bloom/photo.png",
    title: " SMOOTHIES  12",
    price: "6.00",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Ice cream, banana, strawberry",
  },
  {
    menuNumber: 2101,
    image: "/menu/bloom/photo.png",
    title: "AFRICA QUIN",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2102,
    image: "/menu/bloom/photo.png",
    title: "GREEN APPLE",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2103,
    image: "/menu/bloom/photo.png",
    title: "GPAPE MINT",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2104,
    image: "/menu/bloom/photo.png",
    title: "ICE CACTUS",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2105,
    image: "/menu/bloom/photo.png",
    title: "BUBBLEGUN",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2106,
    image: "/menu/bloom/photo.png",
    title: "WATERMELON",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2107,
    image: "/menu/bloom/photo.png",
    title: "BLUEBERRY",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2108,
    image: "/menu/bloom/photo.png",
    title: "MELON",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
];
