export const roBloom = [
  {
    menuNumber: 1,
    image: "",
    title: "TORTILLA",
    price: "8.50",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients:
      "piept de pui, gouda, bacon servit cu cartofi prăjiți și sos caesar",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2,
    image: "",
    title: "NUGGETS DE PUI",
    price: "7.50",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients: "servit cu cartofi prăjiți și sos caesar sau dulce-picant",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 3,
    image: "",
    title: "BURGER CU BR NZĂ",
    price: "9.00",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients:
      "salată, roșii, bacon, cheddar, ceapă, maioneză servit cu cartofi prăjiți și sos caesar",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 4,
    image: "",
    title: "BURGER CU PUI",
    price: "9.50",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients:
      "salată, roșii, bacon, ceapă, maioneză servit cu cartofi prăjiți și sos caesar",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 5,
    image: "",
    title: "CLUB SANDWICH CU PUI",
    price: "9.00",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients:
      "pâine pufoasă, maioneză, bacon, pui, salată, gouda, roșii servit cu cartofi prăjiți și sos caesar",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 6,
    image: "",
    title: "PIZZA SPECIALĂ 830gr",
    price: "11.00",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients: "mozzarella, sos de roșii, ardei gras, bacon",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 7,
    image: "",
    title: "PIZZA MARGHERITA 730gr",
    price: "10.00",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients: "sos de roșii, gouda",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 8,
    image: "",
    title: "SALATĂ CAESAR",
    price: "8.00",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients: "iceberg, roșii cherry, sos caesar, pui, parmezan, crutoane",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 9,
    image: "",
    title: "SALATĂ DE FRUCTE",
    price: "8.00",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 10,
    image: "",
    title: "TOAST CAESAR",
    price: "5.00",
    price1: null,
    category: "M NCARE",
    subCategory: null,
    ingredients: "gouda-șuncă cu chips-uri",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 101,
    image: "",
    title: "FREDDO ESPRESSO",
    price: "5.00",
    price1: null,
    category: "CAFEA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 102,
    image: "",
    title: "FREDDO CAPPUCCINO",
    price: "5.00",
    price1: null,
    category: "CAFEA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 103,
    image: "",
    title: "FRAPPE",
    price: "5.00",
    price1: null,
    category: "CAFEA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 104,
    image: "",
    title: "CAFEA DECOFEINIZATĂ",
    price: "5.00",
    price1: null,
    category: "CAFEA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 105,
    image: "",
    title: "CIOCOLATĂ",
    price: "5.00",
    price1: null,
    category: "CAFEA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 201,
    image: "",
    title: "VIENEZ",
    price: "5.50",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 202,
    image: "",
    title: "ESPRESSO",
    price: "4.50",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 203,
    image: "",
    title: "ESPRESSO DUBLU",
    price: "5.00",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 204,
    image: "",
    title: "CAPPUCCINO",
    price: "5.00",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 205,
    image: "",
    title: "CAPPUCCINO DUBLU",
    price: "5.50",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 206,
    image: "",
    title: "NESCAFE",
    price: "5.00",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 207,
    image: "",
    title: "CAFEA GRECEASCĂ",
    price: "4.50",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 208,
    image: "",
    title: "CAFEA GRECEASCĂ DUBLĂ",
    price: "5.00",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 209,
    image: "",
    title: "AMERICANO",
    price: "4.50",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 210,
    image: "",
    title: "AMERICANO DUBLU",
    price: "5.00",
    price1: null,
    category: "CIOCOLATĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 301,
    image: "",
    title: "SUC PROASPĂT DE PORTOCALE",
    price: "5.50",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 302,
    image: "",
    title: "SUC DE PORTOCALE",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 303,
    image: "",
    title: "SUC DE VIȘINE",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 304,
    image: "",
    title: "SUC DE BANANE",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 305,
    image: "",
    title: "SUC DE ANANAS",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 306,
    image: "",
    title: "SUC DE PIERSICI",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 307,
    image: "",
    title: "SUC MIXT",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 308,
    image: "",
    title: "CEAI RECE DE PIERSICI",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 309,
    image: "",
    title: "CEAI RECE DE LĂM IE",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 310,
    image: "",
    title: "CEAI VERDE RECE",
    price: "5.00",
    price1: null,
    category: "SUCURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 401,
    image: "",
    title: "COCA COLA",
    price: "5.00",
    price1: null,
    category: "RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 402,
    image: "",
    title: "COCA COLA ZERO",
    price: "5.00",
    price1: null,
    category: "RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 403,
    image: "",
    title: "COCA COLA LIGHT",
    price: "5.00",
    price1: null,
    category: "RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 404,
    image: "",
    title: "LIMONADĂ",
    price: "5.00",
    price1: null,
    category: "BĂUTURI RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 405,
    image: "",
    title: "SUC DE PORTOCALE",
    price: "5.00",
    price1: null,
    category: "BĂUTURI RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 406,
    image: "",
    title: "SPRITE",
    price: "5.00",
    price1: null,
    category: "BĂUTURI RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 407,
    image: "",
    title: "PERRIER",
    price: "5.00",
    price1: null,
    category: "BĂUTURI RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 408,
    image: "",
    title: "THREE CENTS PINK",
    price: "5.00",
    price1: null,
    category: "BĂUTURI RĂCORITOARE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 409,
    image: "",
    title: "SOUROTI ",
    price: "5.00",
    price1: null,
    category: "BĂUTURI RĂCORITOARE",
    subCategory: null,
    ingredients: "330ml",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 409500,
    image: "",
    title: "SOUROTI",
    price: "5.00",
    price1: null,
    category: "BĂUTURI RĂCORITOARE",
    subCategory: null,
    ingredients: "330ml",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 501,
    image: "",
    title: "CĂPȘUNI",
    price: "5.00",
    price1: null,
    category: "GRANITA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 502,
    image: "",
    title: "LĂM IE",
    price: "5.00",
    price1: null,
    category: "GRANITA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 503,
    image: "",
    title: "PEPENE VERDE",
    price: "5.00",
    price1: null,
    category: "GRANITA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 601,
    image: "",
    title: "RED BULL",
    price: "5.00",
    price1: null,
    category: "BĂUTURI GATA DE BĂUT",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 602,
    image: "",
    title: "SMIRNOFF ICE",
    price: "5.00",
    price1: null,
    category: "BĂUTURI GATA DE BĂUT",
    subCategory: null,
    ingredients: "275 ml",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 603,
    image: "",
    title: "GORDON`S SPACE",
    price: "5.00",
    price1: null,
    category: "BĂUTURI GATA DE BĂUT",
    subCategory: null,
    ingredients: "275 ml ",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 604,
    image: "",
    title: "BREEZER (LĂM IE/PEPENE VERDE) ",
    price: "5.00",
    price1: null,
    category: "BĂUTURI GATA DE BĂUT",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 701,
    image: "",
    title: "BERE FIX LA HALBĂ MICĂ",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "330ml",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 702,
    image: "",
    title: "BERE FIX LA HALBĂ MARE",
    price: "6.00",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "500ml",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 703,
    image: "",
    title: "CORONA",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 704,
    image: "",
    title: "SOL",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 705,
    image: "",
    title: "MYTHOS",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 706,
    image: "",
    title: "ALPHA",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 707,
    image: "",
    title: "KAISER",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 708,
    image: "",
    title: "HEINEKEN",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 709,
    image: "",
    title: "HEINEKEN ZERO",
    price: "5.50",
    price1: null,
    category: "BERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 801,
    image: "",
    title: "VIN ALB DEMIDULCE",
    price: "6.00",
    price1: null,
    category: "VINURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 802,
    image: "",
    title: "VIN ROȘU DEMIDULCE",
    price: "6.00",
    price1: null,
    category: "VINURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 803,
    image: "",
    title: "SANGRIA ROȘIE",
    price: "6.00",
    price1: null,
    category: "VINURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 804,
    image: "",
    title: "SANGRIA ALBĂ",
    price: "6.00",
    price1: null,
    category: "VINURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 805,
    image: "",
    title: "MALAGOUZIA",
    price: "40.00",
    price1: null,
    category: "VINURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 806,
    image: "",
    title: "TECHNI ALEPIAS",
    price: "40.00",
    price1: null,
    category: "VINURI",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 901,
    image: "",
    title: "PLOMARY",
    price: "8.00",
    price1: null,
    category: "APERITIV",
    subCategory: null,
    ingredients: "200ml",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 902,
    image: "",
    title: "IDONIKO FĂRĂ",
    price: "9.00",
    price1: null,
    category: "APERITIV",
    subCategory: null,
    ingredients: "200ml",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 903,
    image: "",
    title: "SHOT",
    price: "3.00",
    price1: null,
    category: "APERITIV",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 904,
    image: "",
    title: "SUBMARIN",
    price: "4.00",
    price1: null,
    category: "APERITIV",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1001,
    image: "",
    title: "SMIRNOFF",
    price: "8.00",
    price1: "80.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1002,
    image: "",
    title: "ABSOLUT",
    price: "8.00",
    price1: "80.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1003,
    image: "",
    title: "SERKOVA",
    price: "8.00",
    price1: "80.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1004,
    image: "",
    title: "STOLICHNAYA",
    price: "8.00",
    price1: "80.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1005,
    image: "",
    title: "GREY GOOSE",
    price: "10.00",
    price1: "100.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1006,
    image: "",
    title: "BELUGA",
    price: "10.00",
    price1: "100.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1007,
    image: "",
    title: "BELVEDERE",
    price: "10.00",
    price1: "100.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1008,
    image: "",
    title: "CIROC",
    price: "10.00",
    price1: "100.00",
    category: "VODCĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1101,
    image: "",
    title: "GORDONS",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1102,
    image: "",
    title: "GORDONS PINK",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1103,
    image: "",
    title: "TANGUERAY",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1104,
    image: "",
    title: "TANGUERAY",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1105,
    image: "",
    title: "BEEFEATER",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1106,
    image: "",
    title: "BOMBAY BLUE",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1107,
    image: "",
    title: "HENDRICKS",
    price: "10.00",
    price1: "100.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1201,
    image: "",
    title: "CUERVO SILVER",
    price: "8.00",
    price1: "80.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1202,
    image: "",
    title: "CUERVO REPASADO",
    price: "8.00",
    price1: "80.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1203,
    image: "",
    title: "DON JULIO REPASADO",
    price: "10.00",
    price1: "100.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1204,
    image: "",
    title: "DON JULIO BLANCO",
    price: "10.00",
    price1: "100.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1301,
    image: "",
    title: "JAMESON",
    price: "8.00",
    price1: "80.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1302,
    image: "",
    title: "JOHNNIE RED",
    price: "8.00",
    price1: "80.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1303,
    image: "",
    title: "JOHNNIE BLACK",
    price: "9.00",
    price1: "90.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1304,
    image: "",
    title: "CHIVAS 12",
    price: "9.00",
    price1: "90.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1305,
    image: "",
    title: "CARDHU",
    price: "9.00",
    price1: "90.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1306,
    image: "",
    title: "HAIG",
    price: "8.00",
    price1: "80.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1307,
    image: "",
    title: "JACK DANIELS",
    price: "9.00",
    price1: "90.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1308,
    image: "",
    title: "FAMOUS",
    price: "8.00",
    price1: "80.00",
    category: "WHISKY",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1401,
    image: "",
    title: "BACARDI",
    price: "8.00",
    price1: "80.00",
    category: "ROM",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1402,
    image: "",
    title: "BACARDI NEGRU",
    price: "9.00",
    price1: "90.00",
    category: "ROM",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1403,
    image: "",
    title: "HAVANA 3*",
    price: "8.00",
    price1: "80.00",
    category: "ROM",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1404,
    image: "",
    title: "HAVANA 7*",
    price: "9.00",
    price1: "90.00",
    category: "ROM",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1405,
    image: "",
    title: "HAVANA NEGRU",
    price: "9.00",
    price1: "90.00",
    category: "ROM",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1406,
    image: "",
    title: "ZACAPA 23",
    price: "10.00",
    price1: "100.00",
    category: "ROM",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1407,
    image: "",
    title: "CAPTAIN MORGAN",
    price: "8.00",
    price1: "80.00",
    category: "ROM",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1501,
    image: "",
    title: "MASTIHA",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1502,
    image: "",
    title: "COINTREAU",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1503,
    image: "",
    title: "CAMPARI",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1504,
    image: "",
    title: "APEROL",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1505,
    image: "",
    title: "BAILEYS",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1506,
    image: "",
    title: "KAHLUA",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1507,
    image: "",
    title: "JAGERMEISTER",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1508,
    image: "",
    title: "MARTINI BIANCO",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1509,
    image: "",
    title: "MARTINI EXTRA DRY",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1510,
    image: "",
    title: "MALIBU",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1511,
    image: "",
    title: "LIMONCELLO",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1512,
    image: "",
    title: "DRAMBUIE",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1513,
    image: "",
    title: "DISARRONO",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1514,
    image: "",
    title: "APPLE SOURZ",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1515,
    image: "",
    title: "SAMBUCA",
    price: "8.00",
    price1: "80.00",
    category: "LICHIOR",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1601,
    image: "",
    title: "METAXA 3*",
    price: "8.00",
    price1: "80.00",
    category: "CONIAC",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1602,
    image: "",
    title: "METAXA 5*",
    price: "9.00",
    price1: "90.00",
    category: "CONIAC",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1603,
    image: "",
    title: "HENNESSY",
    price: "9.00",
    price1: "90.00",
    category: "CONIAC",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1701,
    image: "",
    title: "MOSCATO D'ASTI",
    price: "6.00",
    price1: "50.00",
    category: "ȘAMPANIE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1702,
    image: "",
    title: "MOSCATO ROZE ASTI",
    price: "6.00",
    price1: "50.00",
    category: "ȘAMPANIE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1703,
    image: "",
    title: "MARTINI ASTI",
    price: "6.00",
    price1: "50.00",
    category: "ȘAMPANIE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1704,
    image: "",
    title: "BOTTEGA PROSECCO",
    price: "6.00",
    price1: "50.00",
    category: "ȘAMPANIE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1705,
    image: "",
    title: "MOET ICE",
    price: "150.00",
    price1: "",
    category: "ȘAMPANIE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1706,
    image: "",
    title: "MOET ROZE",
    price: "150.00",
    price1: "",
    category: "ȘAMPANIE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1801,
    image: "",
    title: "APĂ ÎMBUTELIATĂ MICĂ",
    price: "0.50",
    price1: "",
    category: "APĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1802,
    image: "",
    title: "APĂ ÎMBUTELIATĂ MARE",
    price: "1.00",
    price1: "",
    category: "APĂ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1901,
    image: "",
    title: "MOJITO",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "cu orice aromă",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1902,
    image: "",
    title: "MARGARITA",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1903,
    image: "",
    title: "DAIQUIRI",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "cu orice aromă",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1904,
    image: "",
    title: "SEX PE PLAJĂ",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1905,
    image: "",
    title: "PORN STAR MARTINI",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1906,
    image: "",
    title: "ZOMBIE",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1907,
    image: "",
    title: "GIN BASIL SMASH",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1908,
    image: "",
    title: "OLD FASHIONED",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1909,
    image: "",
    title: "MAI TAI",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1910,
    image: "",
    title: "PINA COLADA",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1911,
    image: "",
    title: "TEQUILA SUNRISE",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1912,
    image: "",
    title: "APEROL SPRITZ",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1913,
    image: "",
    title: "COSMOPOLITAN",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1914,
    image: "",
    title: "CUBA LIBRE",
    price: "10.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI CLASICE",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1915,
    image: "",
    title: "BLOOM",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI SEMNĂTURĂ",
    ingredients:
      "gin, piure de fructul pasiunii, sirop de vanilie, suc de lămâie, sirop de ghimbir, bitter de mandarină, frunze de busuioc",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1916,
    image: "",
    title: "PIERDUT ÎN GRECIA",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI SEMNĂTURĂ",
    ingredients:
      "ouzo, suc de ananas, suc de lămâie, piure de mango, sirop de zahăr, bitter de bergamotă, grenadină, blue curacao",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1917,
    image: "",
    title: "MAI BINE ÎMPREUNĂ",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI SEMNĂTURĂ",
    ingredients:
      "brugal anejo, bacardi, suc de portocale, suc de lămâie, piure de căpșuni, sirop de ghimbir, bitter de vanilie și cireșe",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1918,
    image: "",
    title: "ROMEO ȘI JULIETA",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI SEMNĂTURĂ",
    ingredients:
      "vodcă, piure de fructul dragonului, suc de lămâie, sirop de ghimbir, bitter de portocale",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1919,
    image: "",
    title: "SĂRUTUL GRECESC",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI SEMNĂTURĂ",
    ingredients:
      "lichior de mastiha, suc de portocale, suc de ananas, suc de lămâie, bitter de mandarină, grenadină",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1920,
    image: "",
    title: "BINE AȚI VENIT ÎN PARADIS",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI SEMNĂTURĂ",
    ingredients:
      "brugal anejo, suc de ananas, suc de lămâie, sirop de caramel, piure de fructul pasiunii, bitter de ciocolată",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1921,
    image: "",
    title: "E TOTUL GRECESC PENTRU MINE",
    price: "12.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "COCKTAILURI SEMNĂTURĂ",
    ingredients:
      "gin, lichior de mastiha, suc de lămâie, sirop de agave, bitter de bergamotă, limonadă",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1922,
    image: "",
    title: "TU ȘI EU",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILURI",
    ingredients:
      "sirop de vanilie, piure de căpșuni, piure de fructul pasiunii, suc de lămâie, frunze de mentă, soda roz",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1923,
    image: "",
    title: "ÎNFLORIRE DE VARĂ",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILURI",
    ingredients:
      "suc de ananas, suc de portocale, suc de piersici, suc de lămâie, piure de cocos",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1924,
    image: "",
    title: "DULCE PENTRU TINE",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILS",
    ingredients:
      "suc de portocale, suc de lime, suc de căpșuni, sirop de zahăr, grenadină",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1925,
    image: "",
    title: "NOJITO",
    price: "8.00",
    price1: "",
    category: "COCKTAIL",
    subCategory: "MOCKTAILS",
    ingredients:
      "lime proaspăt, zahăr brun, suc de lime, sirop de zahăr, frunze proaspete de mentă, soda",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2001,
    image: "",
    title: "SMOOTHIE 01",
    price: "5.50",
    price1: "",
    category: "SMOOTHIE",
    subCategory: null,
    ingredients: "Căpșuni, piersici, banane",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2002,
    image: "",
    title: "SMOOTHIE 02",
    price: "5.50",
    price1: "",
    category: "SMOOTHIE",
    subCategory: null,
    ingredients: "Căpșuni, mango, pepene galben",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2003,
    image: "",
    title: "SMOOTHIE 03",
    price: "5.50",
    price1: "",
    category: "SMOOTHIE",
    subCategory: null,
    ingredients: "Pere, mango, ananas",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2004,
    image: "",
    title: "SMOOTHIE 08",
    price: "5.50",
    price1: "",
    category: "SMOOTHIE",
    subCategory: null,
    ingredients: "Avocado, kale, coajă de lămâie, banane",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2005,
    image: "",
    title: "SMOOTHIE 09",
    price: "5.50",
    price1: "",
    category: "SMOOTHIE",
    subCategory: null,
    ingredients: "Fructul dragonului, lime, banane, mango",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2006,
    image: "",
    title: "SMOOTHIE 11",
    price: "6.00",
    price1: "",
    category: "SMOOTHIE",
    subCategory: null,
    ingredients: "Biscuiți, cremă vegană",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2007,
    image: "",
    title: "SMOOTHIE 12",
    price: "6.00",
    price1: "",
    category: "SMOOTHIE",
    subCategory: null,
    ingredients: "Înghețată, banane, căpșuni",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2101,
    image: "",
    title: "AFRICA QUIN",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2102,
    image: "",
    title: "MĂR VERDE",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2103,
    image: "",
    title: "MENTĂ CU STRUGURI",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2104,
    image: "",
    title: "CACTUS CU GHEAȚĂ",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2105,
    image: "",
    title: "GUMĂ DE MESTECAT",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2106,
    image: "",
    title: "PEPENE ROȘU",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2107,
    image: "",
    title: "PEPENE GALBEN",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2108,
    image: "",
    title: "PEPENE GALBEN",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REUMPLERE",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
];
