export const ruBloom = [
  {
    menuNumber: 1,
    image: "",
    title: "ТОРТИЛЬЯ",
    price: "8.50",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients:
      "куриная грудка, гауда, бекон, подается с картофелем по-деревенски и соусом цезарь",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2,
    image: "",
    title: "КУРИНЫЕ НАГГЕТСЫ",
    price: "7.50",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients:
      "подаются с картофелем по-деревенски и соусом цезарь или сладким чили",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 3,
    image: "",
    title: "ЧИЗБУРГЕР",
    price: "9.00",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients:
      "салат, помидор, бекон, чеддер, лук, майонез, подается с картофелем по-деревенски и соусом цезарь",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 4,
    image: "",
    title: "КУРИНЫЙ БУРГЕР",
    price: "9.50",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients:
      "салат, помидор, бекон, лук, майонез, подается с картофелем по-деревенски и соусом цезарь",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 5,
    image: "",
    title: "КЛАБ-СЭНДВИЧ С КУРИЦЕЙ",
    price: "9.00",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients:
      "пышный хлеб, майонез, бекон, курица, салат, гауда, помидор, подается с картофелем по-деревенски и соусом цезарь",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 6,
    image: "",
    title: "ПИЦЦА СПЕЦИАЛЬНАЯ 830гр",
    price: "11.00",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients: "моцарелла, томатный соус, зеленый перец, бекон",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 7,
    image: "",
    title: "ПИЦЦА МАРГАРИТА 730гр",
    price: "10.00",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients: "томатный соус, гауда",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 8,
    image: "",
    title: "САЛАТ ЦЕЗАРЬ",
    price: "8.00",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients:
      "айсберг, помидоры черри, соус цезарь, курица, пармезан, гренки",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 9,
    image: "",
    title: "ФРУКТОВЫЙ САЛАТ",
    price: "8.00",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 10,
    image: "",
    title: "ТОСТ ЦЕЗАРЬ",
    price: "5.00",
    price1: null,
    category: "ЕДА",
    subCategory: null,
    ingredients: "гауда-ветчина с чипсами",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 101,
    image: "",
    title: "ФРЕДО ЭСПРЕССО",
    price: "5.00",
    price1: null,
    category: "КОФЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 102,
    image: "",
    title: "ФРЕДО КАПУЧИНО",
    price: "5.00",
    price1: null,
    category: "КОФЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 103,
    image: "",
    title: "ФРАППЕ",
    price: "5.00",
    price1: null,
    category: "КОФЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 104,
    image: "",
    title: "ДЕКАФ",
    price: "5.00",
    price1: null,
    category: "КОФЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 105,
    image: "",
    title: "ШОКОЛАД",
    price: "5.00",
    price1: null,
    category: "КОФЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 201,
    image: "",
    title: "ПО-ВЕНСКИ",
    price: "5.50",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 202,
    image: "",
    title: "ЭСПРЕССО",
    price: "4.50",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 203,
    image: "",
    title: "ДВОЙНОЙ ЭСПРЕССО",
    price: "5.00",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 204,
    image: "",
    title: "КАПУЧИНО",
    price: "5.00",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 205,
    image: "",
    title: "ДВОЙНОЙ КАПУЧИНО",
    price: "5.50",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 206,
    image: "",
    title: "НЕСКАФЕ",
    price: "5.00",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 207,
    image: "",
    title: "ГРЕЧЕСКИЙ КОФЕ",
    price: "4.50",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 208,
    image: "",
    title: "ДВОЙНОЙ ГРЕЧЕСКИЙ КОФЕ",
    price: "5.00",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 209,
    image: "",
    title: "АМЕРИКАНО",
    price: "4.50",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 210,
    image: "",
    title: "ДВОЙНОЙ АМЕРИКАНО",
    price: "5.00",
    price1: null,
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 301,
    image: "",
    title: "СВЕЖЕВЫЖАТЫЙ АПЕЛЬСИНОВЫЙ СОК",
    price: "5.50",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 302,
    image: "",
    title: "АПЕЛЬСИНОВЫЙ СОК",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 303,
    image: "",
    title: "ВИШНЕВЫЙ СОК",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 304,
    image: "",
    title: "БАНАНОВЫЙ СОК",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 305,
    image: "",
    title: "АНАНАСОВЫЙ СОК",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 306,
    image: "",
    title: "ПЕРСИКОВЫЙ СОК",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 307,
    image: "",
    title: "МИКС СОКОВ",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 308,
    image: "",
    title: "ХОЛОДНЫЙ ПЕРСИКОВЫЙ ЧАЙ",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 309,
    image: "",
    title: "ХОЛОДНЫЙ ЛИМОННЫЙ ЧАЙ",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 310,
    image: "",
    title: "ХОЛОДНЫЙ ЗЕЛЕНЫЙ ЧАЙ",
    price: "5.00",
    price1: null,
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 401,
    image: "",
    title: "КОКА-КОЛА",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 402,
    image: "",
    title: "КОКА-КОЛА ЗЕРО",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 403,
    image: "",
    title: "КОКА-КОЛА ЛАЙТ",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 404,
    image: "",
    title: "ЛИМОНАД",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 405,
    image: "",
    title: "АПЕЛЬСИНОВЫЙ НАПИТОК",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 406,
    image: "",
    title: "СПРАЙТ",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 407,
    image: "",
    title: "ПЕРЬЕ",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 408,
    image: "",
    title: "ТРИ ЦЕНТА РОЗОВЫЙ",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 409,
    image: "",
    title: "СУРОТИ",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "330мл",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 409500,
    image: "",
    title: "СУРОТИ",
    price: "5.00",
    price1: null,
    category: "ПРОХЛАДИТЕЛЬНЫЕ НАПИТКИ",
    subCategory: null,
    ingredients: "330мл",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 501,
    image: "",
    title: "КЛУБНИЧНАЯ",
    price: "5.00",
    price1: null,
    category: "ГРАНИТА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 502,
    image: "",
    title: "ЛИМОННАЯ",
    price: "5.00",
    price1: null,
    category: "ГРАНИТА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 503,
    image: "",
    title: "АРБУЗНАЯ",
    price: "5.00",
    price1: null,
    category: "ГРАНИТА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 601,
    image: "",
    title: "РЭД БУЛЛ",
    price: "5.00",
    price1: null,
    category: "ЭНЕРГЕТИЧЕСКИЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 602,
    image: "",
    title: "СМИРНОФФ АЙС",
    price: "5.00",
    price1: null,
    category: "ЭНЕРГЕТИЧЕСКИЕ НАПИТКИ",
    subCategory: null,
    ingredients: "275 мл",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 603,
    image: "",
    title: "ГОРДОНС СПЕЙС",
    price: "5.00",
    price1: null,
    category: "ЭНЕРГЕТИЧЕСКИЕ НАПИТКИ",
    subCategory: null,
    ingredients: "275 мл ",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 604,
    image: "",
    title: "БРИЗЕР (ЛИМОН/АРБУЗ) ",
    price: "5.00",
    price1: null,
    category: "ЭНЕРГЕТИЧЕСКИЕ НАПИТКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 701,
    image: "",
    title: "ФИКС МАЛЕНЬКОЕ РАЗЛИВНОЕ ПИВО",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "330мл",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 702,
    image: "",
    title: "ФИКС БОЛЬШОЕ РАЗЛИВНОЕ ПИВО",
    price: "6.00",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "500мл",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 703,
    image: "",
    title: "КОРОНА",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 704,
    image: "",
    title: "СОЛЬ",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 705,
    image: "",
    title: "МИФОС",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 706,
    image: "",
    title: "АЛЬФА",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 707,
    image: "",
    title: "КАЙЗЕР",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 708,
    image: "",
    title: "ХАЙНЕКЕН",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 709,
    image: "",
    title: "ХАЙНЕКЕН БЕЗАЛКОГОЛЬНЫЙ",
    price: "5.50",
    price1: null,
    category: "ПИВО",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 801,
    image: "",
    title: "БЕЛОЕ ПОЛУСЛАДКОЕ",
    price: "6.00",
    price1: null,
    category: "ВИНА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 802,
    image: "",
    title: "КРАСНОЕ ПОЛУСЛАДКОЕ",
    price: "6.00",
    price1: null,
    category: "ВИНА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 803,
    image: "",
    title: "КРАСНАЯ САНГРИЯ",
    price: "6.00",
    price1: null,
    category: "ВИНА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 804,
    image: "",
    title: "БЕЛАЯ САНГРИЯ",
    price: "6.00",
    price1: null,
    category: "ВИНА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 805,
    image: "",
    title: "МАЛАГУЗИЯ",
    price: "40.00",
    price1: null,
    category: "ВИНА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 806,
    image: "",
    title: "ТЕХНИ АЛЕПИАС",
    price: "40.00",
    price1: null,
    category: "ВИНА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 901,
    image: "",
    title: "ПЛОМАРИ",
    price: "8.00",
    price1: null,
    category: "АПЕРИТИВ",
    subCategory: null,
    ingredients: "200мл",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 902,
    image: "",
    title: "ИДОНИКО БЕЗ",
    price: "9.00",
    price1: null,
    category: "АПЕРИТИВ",
    subCategory: null,
    ingredients: "200мл",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 903,
    image: "",
    title: "ШОТ",
    price: "3.00",
    price1: null,
    category: "АПЕРИТИВ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 904,
    image: "",
    title: "СУБМАРИНА",
    price: "4.00",
    price1: null,
    category: "АПЕРИТИВ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1001,
    image: "",
    title: "СМИРНОФФ",
    price: "8.00",
    price1: "80.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1002,
    image: "",
    title: "АБСОЛЮТ",
    price: "8.00",
    price1: "80.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1003,
    image: "",
    title: "СЕРКОВА",
    price: "8.00",
    price1: "80.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1004,
    image: "",
    title: "СТОЛИЧНАЯ",
    price: "8.00",
    price1: "80.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1005,
    image: "",
    title: "ГРЕЙ ГУС",
    price: "10.00",
    price1: "100.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1006,
    image: "",
    title: "БЕЛУГА",
    price: "10.00",
    price1: "100.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1007,
    image: "",
    title: "БЕЛЬВЕДЕР",
    price: "10.00",
    price1: "100.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1008,
    image: "",
    title: "СИРОК",
    price: "10.00",
    price1: "100.00",
    category: "ВОДКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1101,
    image: "",
    title: "ГОРДОНС",
    price: "8.00",
    price1: "80.00",
    category: "ДЖИН",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1102,
    image: "",
    title: "ГОРДОНС РОЗОВЫЙ",
    price: "9.00",
    price1: "90.00",
    category: "ДЖИН",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1103,
    image: "",
    title: "ТАНКЕРЕЙ",
    price: "8.00",
    price1: "80.00",
    category: "ДЖИН",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1104,
    image: "",
    title: "ТАНКЕРЕЙ",
    price: "9.00",
    price1: "90.00",
    category: "ДЖИН",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1105,
    image: "",
    title: "БИФИТЕР",
    price: "8.00",
    price1: "80.00",
    category: "ДЖИН",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1106,
    image: "",
    title: "БОМБЕЙ САПФИР",
    price: "9.00",
    price1: "90.00",
    category: "ДЖИН",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1107,
    image: "",
    title: "ХЕНДРИКС",
    price: "10.00",
    price1: "100.00",
    category: "ДЖИН",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1201,
    image: "",
    title: "КУЭРВО СИЛЬВЕР",
    price: "8.00",
    price1: "80.00",
    category: "ТЕКИЛА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1202,
    image: "",
    title: "КУЭРВО РЕПОСАДО",
    price: "8.00",
    price1: "80.00",
    category: "ТЕКИЛА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1203,
    image: "",
    title: "ДОН ХУЛИО РЕПОСАДО",
    price: "10.00",
    price1: "100.00",
    category: "ТЕКИЛА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1204,
    image: "",
    title: "ДОН ХУЛИО БЛАНКО",
    price: "10.00",
    price1: "100.00",
    category: "ТЕКИЛА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1301,
    image: "",
    title: "ДЖЕМЕСОН",
    price: "8.00",
    price1: "80.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1302,
    image: "",
    title: "ДЖОННИ УОКЕР РЭД",
    price: "8.00",
    price1: "80.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1303,
    image: "",
    title: "ДЖОННИ УОКЕР БЛЭК",
    price: "9.00",
    price1: "90.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1304,
    image: "",
    title: "ЧИВАС 12",
    price: "9.00",
    price1: "90.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1305,
    image: "",
    title: "КАРДУ",
    price: "9.00",
    price1: "90.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1306,
    image: "",
    title: "ХЕЙГ",
    price: "8.00",
    price1: "80.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1307,
    image: "",
    title: "ДЖЕК ДЭНИЕЛС",
    price: "9.00",
    price1: "90.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1308,
    image: "",
    title: "ФЕЙМОС",
    price: "8.00",
    price1: "80.00",
    category: "ВИСКИ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1401,
    image: "",
    title: "БАКАРДИ",
    price: "8.00",
    price1: "80.00",
    category: "РОМ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1402,
    image: "",
    title: "БАКАРДИ БЛЭК",
    price: "9.00",
    price1: "90.00",
    category: "РОМ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1403,
    image: "",
    title: "ГАВАНА 3*",
    price: "8.00",
    price1: "80.00",
    category: "РОМ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1404,
    image: "",
    title: "ГАВАНА 7*",
    price: "9.00",
    price1: "90.00",
    category: "РОМ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1405,
    image: "",
    title: "ГАВАНА БЛЭК",
    price: "9.00",
    price1: "90.00",
    category: "РОМ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1406,
    image: "",
    title: "САКАПА 23",
    price: "10.00",
    price1: "100.00",
    category: "РОМ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1407,
    image: "",
    title: "КАПИТАН МОРГАН",
    price: "8.00",
    price1: "80.00",
    category: "РОМ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1501,
    image: "",
    title: "МАСТИКА",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1502,
    image: "",
    title: "КУАНТРО",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1503,
    image: "",
    title: "КАМПАРИ",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1504,
    image: "",
    title: "АПЕРОЛЬ",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1505,
    image: "",
    title: "БЕЙЛИС",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1506,
    image: "",
    title: "КАЛУА",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1507,
    image: "",
    title: "ЕГЕРМЕЙСТЕР",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1508,
    image: "",
    title: "МАРТИНИ БЬЯНКО",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1509,
    image: "",
    title: "МАРТИНИ ЭКСТРА ДРАЙ",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1510,
    image: "",
    title: "МАЛИБУ",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1511,
    image: "",
    title: "ЛИМОНЧЕЛЛО",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1512,
    image: "",
    title: "ДРАМБУИ",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1513,
    image: "",
    title: "ДИСАРОННО",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1514,
    image: "",
    title: "ЯБЛОЧНЫЙ САУРЗ",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1515,
    image: "",
    title: "САМБУКА",
    price: "8.00",
    price1: "80.00",
    category: "ЛИКЁР",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1601,
    image: "",
    title: "МЕТАКСА 3*",
    price: "8.00",
    price1: "80.00",
    category: "КОНЬЯК",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1602,
    image: "",
    title: "МЕТАКСА 5*",
    price: "9.00",
    price1: "90.00",
    category: "КОНЬЯК",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1603,
    image: "",
    title: "ХЕННЕССИ",
    price: "9.00",
    price1: "90.00",
    category: "КОНЬЯК",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1701,
    image: "",
    title: "МОСКАТО Д'АСТИ",
    price: "6.00",
    price1: "50.00",
    category: "ШАМПАНСКОЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1702,
    image: "",
    title: "МОСКАТО РОЗЕ АСТИ",
    price: "6.00",
    price1: "50.00",
    category: "ШАМПАНСКОЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1703,
    image: "",
    title: "МАРТИНИ АСТИ",
    price: "6.00",
    price1: "50.00",
    category: "ШАМПАНСКОЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1704,
    image: "",
    title: "БОТТЕГА ПРОСЕККО",
    price: "6.00",
    price1: "50.00",
    category: "ШАМПАНСКОЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1705,
    image: "",
    title: "МОЕТ АЙС",
    price: "150.00",
    price1: "",
    category: "ШАМПАНСКОЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1706,
    image: "",
    title: "МОЕТ РОЗЕ",
    price: "150.00",
    price1: "",
    category: "ШАМПАНСКОЕ",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1801,
    image: "",
    title: "МАЛАЯ БУТИЛИРОВАННАЯ ВОДА",
    price: "0.50",
    price1: "",
    category: "ВОДА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1802,
    image: "",
    title: "БОЛЬШАЯ БУТИЛИРОВАННАЯ ВОДА",
    price: "1.00",
    price1: "",
    category: "ВОДА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1901,
    image: "",
    title: "МОХИТО",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "с любым вкусом",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1902,
    image: "",
    title: "МАРГАРИТА",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1903,
    image: "",
    title: "ДАЙКИРИ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "с любым вкусом",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1904,
    image: "",
    title: "СЕКС НА ПЛЯЖЕ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1905,
    image: "",
    title: "ПОРНОЗВЕЗДА МАРТИНИ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1906,
    image: "",
    title: "ЗОМБИ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1907,
    image: "",
    title: "ДЖИН БАЗИЛИК СМЭШ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1908,
    image: "",
    title: "СТАРОМОДНЫЙ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1909,
    image: "",
    title: "МАЙ ТАЙ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1910,
    image: "",
    title: "ПИНА КОЛАДА",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1911,
    image: "",
    title: "ТЕКИЛА САНРАЙЗ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1912,
    image: "",
    title: "АПЕРОЛЬ ШПРИЦ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1913,
    image: "",
    title: "КОСМОПОЛИТЕН",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1914,
    image: "",
    title: "КУБА ЛИБРЕ",
    price: "10.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "КЛАССИЧЕСКИЕ КОКТЕЙЛИ",
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1915,
    image: "",
    title: "БЛУМ",
    price: "12.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "ФИРМЕННЫЕ КОКТЕЙЛИ",
    ingredients:
      "джин, пюре маракуйи, ванильный сироп, сок лайма, имбирный сироп, мандариновый биттер, листья базилика",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1916,
    image: "",
    title: "ЗАТЕРЯННЫЙ В ГРЕЦИИ",
    price: "12.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "ФИРМЕННЫЕ КОКТЕЙЛИ",
    ingredients:
      "узо, ананасовый сок, сок лайма, пюре манго, сахарный сироп, бергамотовый биттер, гренадин, голубой кюрасао",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1917,
    image: "",
    title: "ЛУЧШЕ ВМЕСТЕ",
    price: "12.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "ФИРМЕННЫЕ КОКТЕЙЛИ",
    ingredients:
      "ром бругал аньехо, бакарди, апельсиновый сок, сок лайма, клубничное пюре, имбирный сироп, ванильно-вишневый биттер",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1918,
    image: "",
    title: "РОМЕО И ДЖУЛЬЕТТА",
    price: "12.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "ФИРМЕННЫЕ КОКТЕЙЛИ",
    ingredients:
      "водка, пюре питахайи, сок лайма, имбирный сироп, апельсиновый биттер",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1919,
    image: "",
    title: "ГРЕЧЕСКИЙ ПОЦЕЛУЙ",
    price: "12.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "ФИРМЕННЫЕ КОКТЕЙЛИ",
    ingredients:
      "ликер мастика, апельсиновый сок, ананасовый сок, сок лайма, мандариновый биттер, гренадин",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1920,
    image: "",
    title: "ДОБРО ПОЖАЛОВАТЬ В РАЙ",
    price: "12.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "ФИРМЕННЫЕ КОКТЕЙЛИ",
    ingredients:
      "ром бругал аньехо, ананасовый сок, сок лайма, карамельный сироп, пюре маракуйи, шоколадный биттер",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1921,
    image: "",
    title: "ЭТО ВСЕ ПО-ГРЕЧЕСКИ ДЛЯ МЕНЯ",
    price: "12.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "ФИРМЕННЫЕ КОКТЕЙЛИ",
    ingredients:
      "джин, ликер мастика, сок лайма, сироп агавы, бергамотовый биттер, лимонад",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1922,
    image: "",
    title: "ТЫ И Я",
    price: "8.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "БЕЗАЛКОГОЛЬНЫЕ КОКТЕЙЛИ",
    ingredients:
      "ванильный сироп, клубничное пюре, пюре маракуйи, сок лайма, листья мяты, розовая содовая",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1923,
    image: "",
    title: "ЛЕТНИЙ ЦВЕТОК",
    price: "8.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "БЕЗАЛКОГОЛЬНЫЕ КОКТЕЙЛИ",
    ingredients:
      "ананасовый сок, апельсиновый сок, персиковый сок, сок лайма, кокосовое пюре",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1924,
    image: "",
    title: "СЛАДКИЙ НА ТЕБЯ",
    price: "8.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "БЕЗАЛКОГОЛЬНЫЕ КОКТЕЙЛИ",
    ingredients:
      "апельсиновый сок, сок лайма, клубничный сок, сахарный сироп, гренадин",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 1925,
    image: "",
    title: "НОХИТО",
    price: "8.00",
    price1: "",
    category: "КОКТЕЙЛЬ",
    subCategory: "БЕЗАЛКОГОЛЬНЫЕ КОКТЕЙЛИ",
    ingredients:
      "свежий лайм, коричневый сахар, сок лайма, сахарный сироп, свежие листья мяты, содовая",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2001,
    image: "",
    title: "СМУЗИ 01",
    price: "5.50",
    price1: "",
    category: "СМУЗИ",
    subCategory: null,
    ingredients: "Клубника, персик, банан",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2002,
    image: "",
    title: "СМУЗИ 02",
    price: "5.50",
    price1: "",
    category: "СМУЗИ",
    subCategory: null,
    ingredients: "Клубника, манго, дыня",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2003,
    image: "",
    title: "СМУЗИ 03",
    price: "5.50",
    price1: "",
    category: "СМУЗИ",
    subCategory: null,
    ingredients: "Груша, манго, ананас",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2004,
    image: "",
    title: "СМУЗИ 08",
    price: "5.50",
    price1: "",
    category: "СМУЗИ",
    subCategory: null,
    ingredients: "Авокадо, капуста кейл, цедра лимона, банан",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2005,
    image: "",
    title: "СМУЗИ 09",
    price: "5.50",
    price1: "",
    category: "СМУЗИ",
    subCategory: null,
    ingredients: "Питахайя, лайм, банан, манго",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2006,
    image: "",
    title: "СМУЗИ 11",
    price: "6.00",
    price1: "",
    category: "СМУЗИ",
    subCategory: null,
    ingredients: "Печенье, веганские сливки",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2007,
    image: "",
    title: "СМУЗИ 12",
    price: "6.00",
    price1: "",
    category: "СМУЗИ",
    subCategory: null,
    ingredients: "Мороженое, банан, клубника",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2101,
    image: "",
    title: "АФРИКАНСКИЙ КВИН",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2102,
    image: "",
    title: "ЗЕЛЕНОЕ ЯБЛОКО",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2103,
    image: "",
    title: "ВИНОГРАД С МЯТОЙ",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2104,
    image: "",
    title: "ЛЕДЯНОЙ КАКТУС",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2105,
    image: "",
    title: "ЖВАЧКА",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2106,
    image: "",
    title: "АРБУЗ",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2107,
    image: "",
    title: "ЧЕРНИКА",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
  {
    menuNumber: 2108,
    image: "",
    title: "ДЫНЯ",
    price: "20.00",
    price1: "10.00",
    category: "КАЛЬЯН/ДОБИВКА",
    subCategory: null,
    ingredients: "",
    beachMenu: false,
    restaurantMenu: false,
    beachPrice: null,
  },
];
