export const seBloom = [
  {
    menuNumber: 1,
    image: "/menu/bloom/photo.jpg",
    title: "TORTILIJA",
    price: "8.50",
    category: "HRANA",
    subCategory: null,
    ingredients:
      "file pilećih grudi, goudа, slanina, servirana sa krompirovim pomfritom i ćesar sosom",
  },
  {
    menuNumber: 2,
    image: "/menu/bloom/photo.jpg",
    title: "PILEĆI NUGETI",
    price: "7.50",
    category: "HRANA",
    subCategory: null,
    ingredients:
      "servirani sa krompirovim pomfritom i ćesar sosom ili slatkim čili sosom",
  },
  {
    menuNumber: 3,
    image: "/menu/bloom/photo.jpg",
    title: "ČIZBURGER",
    price: "9.00",
    category: "HRANA",
    subCategory: null,
    ingredients:
      "zelena salata, paradajz, slanina, čedar sir, crni luk, majonez, serviran sa krompirovim pomfritom i ćesar sosom",
  },
  {
    menuNumber: 4,
    image: "/menu/bloom/photo.jpg",
    title: "PILEĆI BURGER",
    price: "9.50",
    category: "HRANA",
    subCategory: null,
    ingredients:
      "zelena salata, paradajz, slanina, crni luk, majonez, serviran sa krompirovim pomfritom i ćesar sosom",
  },
  {
    menuNumber: 5,
    image: "/menu/bloom/photo.jpg",
    title: "PILEĆI KLUB SENDVIČ",
    price: "9.00",
    category: "HRANA",
    subCategory: null,
    ingredients:
      "mek hleb, majonez, slanina, pileće meso, zelena salata, gouda sir, paradajz, serviran sa krompirovim pomfritom i ćesar sosom",
  },
  {
    menuNumber: 6,
    image: "/menu/bloom/photo.jpg",
    title: "SPECIJALNA PICA 830gr",
    price: "11.00",
    category: "HRANA",
    subCategory: null,
    ingredients: "mocarela, paradajz sos, zelena paprika, slanina",
  },
  {
    menuNumber: 7,
    image: "/menu/bloom/photo.jpg",
    title: "MARGARITA PICA 730gr",
    price: "10.00",
    category: "HRANA",
    subCategory: null,
    ingredients: "paradajz sos, gouda sir",
  },
  {
    menuNumber: 8,
    image: "/menu/bloom/photo.jpg",
    title: "ĆEZAR SALATA",
    price: "8.00",
    category: "HRANA",
    subCategory: null,
    ingredients:
      "zelena salata, čeri paradajz, ćezar sos, pileće meso, parmezаn, krutoni",
  },
  {
    menuNumber: 9,
    image: "/menu/bloom/photo.jpg",
    title: "VOĆNA SALATA",
    price: "8.00",
    category: "HRANA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 10,
    image: "/menu/bloom/photo.jpg",
    title: "TOSТ ĆEZAR",
    price: "5.00",
    category: "HRANA",
    subCategory: null,
    ingredients: "gouda-šunka sa čipsevima",
  },
  {
    menuNumber: 101,
    image: "/menu/bloom/photo.jpg",
    title: "FREDO ESPRESO",
    price: "5.00",
    category: "KAFA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 102,
    image: "/menu/bloom/photo.jpg",
    title: "FREDO KAPUĆINO",
    price: "5.00",
    category: "KAFA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 103,
    image: "/menu/bloom/photo.jpg",
    title: "FRAPE",
    price: "5.00",
    category: "KAFA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 104,
    image: "/menu/bloom/photo.jpg",
    title: "DEKAFE",
    price: "5.00",
    category: "KAFA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 105,
    image: "/menu/bloom/photo.jpg",
    title: "ČOKOLADA",
    price: "5.00",
    category: "KAFA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 201,
    image: "/menu/bloom/photo.jpg",
    title: "BEČKI KOLAČ",
    price: "5.50",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 202,
    image: "/menu/bloom/photo.jpg",
    title: "ESPRESO",
    price: "4.50",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 203,
    image: "/menu/bloom/photo.jpg",
    title: "DUPLI ESPRESO",
    price: "5.00",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 204,
    image: "/menu/bloom/photo.jpg",
    title: "KAPUĆINO",
    price: "5.00",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 205,
    image: "/menu/bloom/photo.jpg",
    title: "DUPLI KAPUĆINO",
    price: "5.50",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 206,
    image: "/menu/bloom/photo.jpg",
    title: "NESKAFE",
    price: "5.00",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 207,
    image: "/menu/bloom/photo.jpg",
    title: "GRČKA KAFA",
    price: "4.50",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 208,
    image: "/menu/bloom/photo.jpg",
    title: "DUPLA GRČKA KAFA",
    price: "5.00",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 209,
    image: "/menu/bloom/photo.jpg",
    title: "AMERIKANO",
    price: "4.50",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 210,
    image: "/menu/bloom/photo.jpg",
    title: "DUPLI AMERIKANO",
    price: "5.00",
    category: "ČOKOLADA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 301,
    image: "/menu/bloom/photo.jpg",
    title: "SVEŽE CEĐEN SOKOD POMORANDŽE",
    price: "5.50",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 302,
    image: "/menu/bloom/photo.jpg",
    title: "SOK OD POMORANDŽE",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 303,
    image: "/menu/bloom/photo.jpg",
    title: "VIŠNJA SOK",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 304,
    image: "/menu/bloom/photo.jpg",
    title: "BANANA SOK",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 305,
    image: "/menu/bloom/photo.jpg",
    title: "ANANAS SOK",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 306,
    image: "/menu/bloom/photo.jpg",
    title: "BRESKVA SOK",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 307,
    image: "/menu/bloom/photo.jpg",
    title: "MEŠANI SOK",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 308,
    image: "/menu/bloom/photo.jpg",
    title: "HLADNI ČAJ BRESKVA",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 309,
    image: "/menu/bloom/photo.jpg",
    title: "HLADNI ČAJ LIMUN",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 310,
    image: "/menu/bloom/photo.jpg",
    title: "HLADNI ZELENI ČAJ",
    price: "5.00",
    category: "SOKOVI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 401,
    image: "/menu/bloom/photo.jpg",
    title: "KOKA KOLA",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 402,
    image: "/menu/bloom/photo.jpg",
    title: "KOKA KOLA ZERO",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 403,
    image: "/menu/bloom/photo.jpg",
    title: "KOKA KOLA LAJNA",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 404,
    image: "/menu/bloom/photo.jpg",
    title: "LIMONADA",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 405,
    image: "/menu/bloom/photo.jpg",
    title: "POMORANDŽA",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 406,
    image: "/menu/bloom/photo.jpg",
    title: "SPRAJT",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 407,
    image: "/menu/bloom/photo.jpg",
    title: "PERIJER",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 408,
    image: "/menu/bloom/photo.jpg",
    title: "TRI CENTA PINK",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 409,
    image: "/menu/bloom/photo.jpg",
    title: "SOUROTI",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "330ml",
  },
  {
    menuNumber: 409500,
    image: "/menu/bloom/photo.jpg",
    title: "SOUROTI",
    price: "5.00",
    category: "OSVEŽAVAJUĆA PIĆA",
    subCategory: null,
    ingredients: "330ml",
  },
  {
    menuNumber: 501,
    image: "/menu/bloom/photo.jpg",
    title: "JAGODA",
    price: "5.00",
    category: "GRANITA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 502,
    image: "/menu/bloom/photo.jpg",
    title: "LIMUN",
    price: "5.00",
    category: "GRANITA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 503,
    image: "/menu/bloom/photo.jpg",
    title: "LUBENICA LIMUN",
    price: "5.00",
    category: "GRANITA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 601,
    image: "/menu/bloom/photo.jpg",
    title: "RED BULI",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 602,
    image: "/menu/bloom/photo.jpg",
    title: "SMIRНOV AJS",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "275 ml",
  },
  {
    menuNumber: 603,
    image: "/menu/bloom/photo.jpg",
    title: "GORDON'S SPEJS",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "275 ml",
  },
  {
    menuNumber: 604,
    image: "/menu/bloom/photo.jpg",
    title: "BRIZ (LIMUN/LUBENICA LIMUN)",
    price: "5.00",
    category: "RTD",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 701,
    image: "/menu/bloom/photo.jpg",
    title: "MALA TOČENA PIVA",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "330ml",
  },
  {
    menuNumber: 702,
    image: "/menu/bloom/photo.jpg",
    title: "VELIKA TOČENA PIVA",
    price: "6.00",
    category: "PIVA",
    subCategory: null,
    ingredients: "500ml",
  },
  {
    menuNumber: 703,
    image: "/menu/bloom/photo.jpg",
    title: "KORONA",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 704,
    image: "/menu/bloom/photo.jpg",
    title: "SOL",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 705,
    image: "/menu/bloom/photo.jpg",
    title: "MITOS",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 706,
    image: "/menu/bloom/photo.jpg",
    title: "ALFA",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 707,
    image: "/menu/bloom/photo.jpg",
    title: "KAJZER",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 708,
    image: "/menu/bloom/photo.jpg",
    title: "HAJNEKEN",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 709,
    image: "/menu/bloom/photo.jpg",
    title: "HAJNEKEN ZERO",
    price: "5.50",
    category: "PIVA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 801,
    image: "/menu/bloom/photo.jpg",
    title: "BELO POLUSLАТKO",
    price: "6.00",
    category: "VINA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 802,
    image: "/menu/bloom/photo.jpg",
    title: "CRVENO POLUSLАТKO",
    price: "6.00",
    category: "VINA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 803,
    image: "/menu/bloom/photo.jpg",
    title: "CRVENA SANGRIJA",
    price: "6.00",
    category: "VINA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 804,
    image: "/menu/bloom/photo.jpg",
    title: "BELA SANGRIJA",
    price: "6.00",
    category: "VINA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 805,
    image: "/menu/bloom/photo.jpg",
    title: "MALAGUZIJA",
    price: "40.00",
    category: "VINA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 806,
    image: "/menu/bloom/photo.jpg",
    title: "TEHNI ALEPIJAS",
    price: "40.00",
    category: "VINA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 901,
    image: "/menu/bloom/photo.jpg",
    title: "PLOMARI",
    price: "8.00",
    category: "APERITIV",
    subCategory: null,
    ingredients: "200ml",
  },
  {
    menuNumber: 902,
    image: "/menu/bloom/photo.jpg",
    title: "IDONIKO BEZ",
    price: "9.00",
    category: "APERITIV",
    subCategory: null,
    ingredients: "200ml",
  },
  {
    menuNumber: 903,
    image: "/menu/bloom/photo.jpg",
    title: "ŠОT",
    price: "3.00",
    category: "APERITIV",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 904,
    image: "/menu/bloom/photo.jpg",
    title: "PODMORNICA",
    price: "4.00",
    category: "APERITIV",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1001,
    image: "/menu/bloom/photo.jpg",
    title: "SMIRNOFF",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1002,
    image: "/menu/bloom/photo.jpg",
    title: "ABSOLUT",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1003,
    image: "/menu/bloom/photo.jpg",
    title: "SERKOVA",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1004,
    image: "/menu/bloom/photo.jpg",
    title: "STOLICHNAYA",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1005,
    image: "/menu/bloom/photo.jpg",
    title: "GREY GUSKA",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1006,
    image: "/menu/bloom/photo.jpg",
    title: "BELUGA",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1007,
    image: "/menu/bloom/photo.jpg",
    title: "BELVEDERE",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1008,
    image: "/menu/bloom/photo.jpg",
    title: "CIROC",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1101,
    image: "/menu/bloom/photo.jpg",
    title: "GORDONS",
    price: "8.00",
    price1: "80.00",
    category: "ĐINIĆ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1102,
    image: "/menu/bloom/photo.jpg",
    title: "GORDONS RUŽIČASTI",
    price: "9.00",
    price1: "90.00",
    category: "ĐINIĆ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1103,
    image: "/menu/bloom/photo.jpg",
    title: "TANGUERAY",
    price: "8.00",
    price1: "80.00",
    category: "ĐINIĆ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1104,
    image: "/menu/bloom/photo.jpg",
    title: "TANGUERAY",
    price: "9.00",
    price1: "90.00",
    category: "ĐINIĆ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1105,
    image: "/menu/bloom/photo.jpg",
    title: "BEEFEATER",
    price: "8.00",
    price1: "80.00",
    category: "ĐINIĆ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1106,
    image: "/menu/bloom/photo.jpg",
    title: "BOMBAY PLAVI",
    price: "9.00",
    price1: "90.00",
    category: "ĐINIĆ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1107,
    image: "/menu/bloom/photo.jpg",
    title: "HENDRICKS",
    price: "10.00",
    price1: "100.00",
    category: "ĐINIĆ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1201,
    image: "/menu/bloom/photo.jpg",
    title: "CUERVO SREBRNI",
    price: "8.00",
    price1: "80.00",
    category: "TEKILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1202,
    image: "/menu/bloom/photo.jpg",
    title: "CUERVO REPASADO",
    price: "8.00",
    price1: "80.00",
    category: "TEKILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1203,
    image: "/menu/bloom/photo.jpg",
    title: "DON JULIO REPASADO",
    price: "10.00",
    price1: "100.00",
    category: "TEKILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1204,
    image: "/menu/bloom/photo.jpg",
    title: "DON JULIO BELI",
    price: "10.00",
    price1: "100.00",
    category: "TEKILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1301,
    image: "/menu/bloom/photo.jpg",
    title: "JAMESON",
    price: "8.00",
    price1: "80.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1302,
    image: "/menu/bloom/photo.jpg",
    title: "JOHNNIE CRVENI",
    price: "8.00",
    price1: "80.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1303,
    image: "/menu/bloom/photo.jpg",
    title: "JOHNNIE CRNI",
    price: "9.00",
    price1: "90.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1304,
    image: "/menu/bloom/photo.jpg",
    title: "CHIVAS 12",
    price: "9.00",
    price1: "90.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1305,
    image: "/menu/bloom/photo.jpg",
    title: "KARDHU",
    price: "9.00",
    price1: "90.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1306,
    image: "/menu/bloom/photo.jpg",
    title: "HEJG",
    price: "8.00",
    price1: "80.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1307,
    image: "/menu/bloom/photo.jpg",
    title: "DŽEK DENIELS",
    price: "9.00",
    price1: "90.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1308,
    image: "/menu/bloom/photo.jpg",
    title: "FEJMUS",
    price: "8.00",
    price1: "80.00",
    category: "VISKI",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1401,
    image: "/menu/bloom/photo.jpg",
    title: "BAKARDI",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1402,
    image: "/menu/bloom/photo.jpg",
    title: "BAKARDI CRNI",
    price: "9.00",
    price1: "90.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1403,
    image: "/menu/bloom/photo.jpg",
    title: "HAVANA 3*",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1404,
    image: "/menu/bloom/photo.jpg",
    title: "HAVANA 7*",
    price: "9.00",
    price1: "90.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1405,
    image: "/menu/bloom/photo.jpg",
    title: "HAVANA CRNI",
    price: "9.00",
    price1: "90.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1406,
    image: "/menu/bloom/photo.jpg",
    title: "ZAKAPA 23",
    price: "10.00",
    price1: "100.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1407,
    image: "/menu/bloom/photo.jpg",
    title: "KAPETAN MORGAN",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1501,
    image: "/menu/bloom/photo.jpg",
    title: "MASTIKA",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1502,
    image: "/menu/bloom/photo.jpg",
    title: "KOINTRO",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1503,
    image: "/menu/bloom/photo.jpg",
    title: "KAMPARI",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1504,
    image: "/menu/bloom/photo.jpg",
    title: "APEROL",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1505,
    image: "/menu/bloom/photo.jpg",
    title: "BEJLIZ",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1506,
    image: "/menu/bloom/photo.jpg",
    title: "KALUA",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1507,
    image: "/menu/bloom/photo.jpg",
    title: "JEGERMAЈSTER",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1508,
    image: "/menu/bloom/photo.jpg",
    title: "MARTINI BIJANCO",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1509,
    image: "/menu/bloom/photo.jpg",
    title: "MARTINI EKSTRA SUVI",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1510,
    image: "/menu/bloom/photo.jpg",
    title: "MALIBJU",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1511,
    image: "/menu/bloom/photo.jpg",
    title: "LIMONĆELO",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1512,
    image: "/menu/bloom/photo.jpg",
    title: "DRAMBUI",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1513,
    image: "/menu/bloom/photo.jpg",
    title: "DISARONO",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1514,
    image: "/menu/bloom/photo.jpg",
    title: "JABUČNI SOURS",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1515,
    image: "/menu/bloom/photo.jpg",
    title: "SAMBUKA",
    price: "8.00",
    price1: "80.00",
    category: "LIKER",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1601,
    image: "/menu/bloom/photo.jpg",
    title: "METAKSA 3*",
    price: "8.00",
    price1: "80.00",
    category: "KONЈAK",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1602,
    image: "/menu/bloom/photo.jpg",
    title: "METAKSA 5*",
    price: "9.00",
    price1: "90.00",
    category: "KONЈAK",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1603,
    image: "/menu/bloom/photo.jpg",
    title: "HENESI",
    price: "9.00",
    price1: "90.00",
    category: "KONЈAK",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1701,
    image: "/menu/bloom/photo.jpg",
    title: "MOSCHATO D'ASTI",
    price: "6.00",
    price1: "50.00",
    category: "ŠAMPANJAC",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1702,
    image: "/menu/bloom/photo.jpg",
    title: "MOSCHATO ROZE ASTI",
    price: "6.00",
    price1: "50.00",
    category: "ŠAMPANJAC",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1703,
    image: "/menu/bloom/photo.jpg",
    title: "MARTINI ASTIN",
    price: "6.00",
    price1: "50.00",
    category: "ŠAMPANJAC",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1704,
    image: "/menu/bloom/photo.jpg",
    title: "BOTEGA PROSEKO",
    price: "6.00",
    price1: "50.00",
    category: "ŠAMPANJAC",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1705,
    image: "/menu/bloom/photo.jpg",
    title: "MOET LED",
    price: "150.00",
    price1: "",
    category: "ŠAMPANJAC",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1706,
    image: "/menu/bloom/photo.jpg",
    title: "MOET ROZE",
    price: "150.00",
    price1: "",
    category: "ŠAMPANJAC",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1801,
    image: "/menu/bloom/photo.jpg",
    title: "MALA FLAŠA VODE",
    price: "0.50",
    price1: "",
    category: "VODA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1802,
    image: "/menu/bloom/photo.jpg",
    title: "VELIKA FLAŠA VODE",
    price: "0.50",
    price1: "",
    category: "VODA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1901,
    image: "/menu/bloom/photo.jpg",
    title: "MOHITO",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "KLASIČNI KOKTELI",
    ingredients: "sa bilo kojim ukusom",
  },
  {
    menuNumber: 1902,
    image: "/menu/bloom/photo.jpg",
    title: "MARGARITA",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "KLASIČNI KOKTELI",
    ingredients: "",
  },
  {
    menuNumber: 1903,
    image: "/menu/bloom/photo.jpg",
    title: "DAJKIRI",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "KLASIČNI KOKTELI",
    ingredients: "sa bilo kojim ukusom",
  },
  {
    menuNumber: 1904,
    image: "/menu/bloom/photo.jpg",
    title: "SEKS NA PLAŽI",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "KLASIČNI KOKTELI",
    ingredients: "",
  },
  {
    menuNumber: 1905,
    image: "/menu/bloom/photo.jpg",
    title: "PORN STAR MARTINI",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "KLASIČNI KOKTELI",
    ingredients: "",
  },
  {
    menuNumber: 1906,
    image: "/menu/bloom/photo.jpg",
    title: "ZOMBI",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "KLASIČNI KOKTELI",
    ingredients: "",
  },
  {
    menuNumber: 1907,
    image: "/menu/bloom/photo.jpg",
    title: "ĐINĐIN BASILSMASH",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "KLASIČNI KOKTELI",
    ingredients: "",
  },
  {
    menuNumber: 1908,
    image: "/menu/bloom/photo.jpg",
    title: "OLD FASHIONED",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients: "",
  },
  {
    menuNumber: 1909,
    image: "/menu/bloom/photo.jpg",
    title: "MAI TAI",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients: "",
  },
  {
    menuNumber: 1910,
    image: "/menu/bloom/photo.jpg",
    title: "PINA COLADA",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients: "",
  },
  {
    menuNumber: 1911,
    image: "/menu/bloom/photo.jpg",
    title: "TEQUILA SUNRISE",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients: "",
  },
  {
    menuNumber: 1912,
    image: "/menu/bloom/photo.jpg",
    title: "APEROL SPRITZ",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients: "",
  },
  {
    menuNumber: 1913,
    image: "/menu/bloom/photo.jpg",
    title: "COSMOPOLITAN",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients: "",
  },
  {
    menuNumber: 1914,
    image: "/menu/bloom/photo.jpg",
    title: "CUBA LIBRE",
    price: "10.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients: "",
  },
  {
    menuNumber: 1915,
    image: "/menu/bloom/photo.jpg",
    title: "BLOOM",
    price: "12.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients:
      "gin, passion puree, vanilla syrup, lime juice, ginger syrup, mantarine bitters, basil leaves",
  },
  {
    menuNumber: 1916,
    image: "/menu/bloom/photo.jpg",
    title: "LOST IN GREECE",
    price: "12.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients:
      "ouzo, pineapple juice, lime juice, mango puree, sugar syrup, bergamot bitters, grenadine, blue curacao",
  },
  {
    menuNumber: 1917,
    image: "/menu/bloom/photo.jpg",
    title: "BETTER TOGETHER",
    price: "12.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients:
      "brugal anejo, bacardi, orange juice, lime juice, strawberry puree, ginger syrup, vanilla cherry bitters",
  },
  {
    menuNumber: 1918,
    image: "/menu/bloom/photo.jpg",
    title: "ROMEO & JULIET",
    price: "12.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients:
      " vodka, dragon puree,lime juice, ginger syrup, orange bitters ",
  },
  {
    menuNumber: 1919,
    image: "/menu/bloom/photo.jpg",
    title: "THE GREEK KISS",
    price: "12.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients:
      "mastiha liquor, orange juice, pineapple juice, lime juice, mantarine itters, grenadine",
  },
  {
    menuNumber: 1920,
    image: "/menu/bloom/photo.jpg",
    title: "WELCOME TO PARADISE",
    price: "12.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients:
      "brugal anejo, pineapple juice, lime juice, caramela syrup, passion puree, chocolate bitters",
  },
  {
    menuNumber: 1921,
    image: "/menu/bloom/photo.jpg",
    title: "IT'S ALL GREEK TO ME",
    price: "12.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "",
    ingredients:
      "gin, mastiha liquor, lime juice, agave syrup, bergamot bitters, lemonade",
  },
  {
    menuNumber: 1922,
    image: "/menu/bloom/photo.jpg",
    title: "YOU & ME",
    price: "8.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "MOCKTAILS",
    ingredients:
      "vanilla syrup, strawberry puree, passion puree, lime juice, spearmints leaves, pink soda",
  },
  {
    menuNumber: 1923,
    image: "/menu/bloom/photo.jpg",
    title: "SUMMER BLOOMER",
    price: "8.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "MOCKTAILS",
    ingredients:
      "pineapple juice, orange juice, peach juice, lime juice, coconut puree",
  },
  {
    menuNumber: 1924,
    image: "/menu/bloom/photo.jpg",
    title: "SWEET ON YOU",
    price: "8.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "MOCKTAILS",
    ingredients:
      "orange juice, lime juice, strawberry juice, sugar syrup grenadine",
  },
  {
    menuNumber: 1925,
    image: "/menu/bloom/photo.jpg",
    title: "NOJITO",
    price: "8.00",
    price1: "",
    category: "KOKTEL",
    subCategory: "MOCKTAILS",
    ingredients:
      " fresh lime, brown sugar, lime juice sugar syrup, fresh spearmint leaves, soda ",
  },
  {
    menuNumber: 2001,
    image: "/menu/bloom/photo.jpg",
    title: " SMOOTHIES  01",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Strawberry, peach, banana",
  },
  {
    menuNumber: 2002,
    image: "/menu/bloom/photo.jpg",
    title: " SMOOTHIES  02",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Strawberry, mango, melon",
  },
  {
    menuNumber: 2003,
    image: "/menu/bloom/photo.jpg",
    title: " SMOOTHIES  03",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Pear, mango, pineapple",
  },
  {
    menuNumber: 2004,
    image: "/menu/bloom/photo.jpg",
    title: " SMOOTHIES  08",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Avocando, kale, lemon zest, banana",
  },
  {
    menuNumber: 2005,
    image: "/menu/bloom/photo.jpg",
    title: " SMOOTHIES  09",
    price: "5.50",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Dragon fruit, lime, banana, mango",
  },
  {
    menuNumber: 2006,
    image: "/menu/bloom/photo.jpg",
    title: " SMOOTHIES  11",
    price: "6.00",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Biscuit, vegan cream",
  },
  {
    menuNumber: 2007,
    image: "/menu/bloom/photo.jpg",
    title: " SMOOTHIES  12",
    price: "6.00",
    price1: "",
    category: "SMOOTHIES",
    subCategory: null,
    ingredients: "Ice cream, banana, strawberry",
  },
  {
    menuNumber: 2101,
    image: "/menu/bloom/photo.jpg",
    title: "AFRICA QUIN",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2102,
    image: "/menu/bloom/photo.jpg",
    title: "GREEN APPLE",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2103,
    image: "/menu/bloom/photo.jpg",
    title: "GPAPE MINT",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2104,
    image: "/menu/bloom/photo.jpg",
    title: "ICE CACTUS",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2105,
    image: "/menu/bloom/photo.jpg",
    title: "BUBBLEGUN",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2106,
    image: "/menu/bloom/photo.jpg",
    title: "WATERMELON",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2107,
    image: "/menu/bloom/photo.jpg",
    title: "BLUEBERRY",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 2108,
    image: "/menu/bloom/photo.jpg",
    title: "MELON",
    price: "20.00",
    price1: "10.00",
    category: "SHISHA/REFILL",
    subCategory: null,
    ingredients: "",
  },
];
