export const uaBloom = [
  {
    menuNumber: 1,
    image: "",
    title: "ТОРТІЛЬЯ",
    price: "8.50",
    category: "ЇЖА",
    subCategory: null,
    ingredients:
      "куряча грудка, гауда, бекон подається з картоплею по-селянськи та соусом Цезар",
  },
  {
    menuNumber: 2,
    image: "",
    title: "КУРЯЧІ НАГЕТСИ",
    price: "7.50",
    category: "ЇЖА",
    subCategory: null,
    ingredients:
      "подається з картоплею по-селянськи та соусом Цезар або солодким чилі",
  },
  {
    menuNumber: 3,
    image: "",
    title: "СИРНИЙ БУРГЕР",
    price: "9.00",
    category: "ЇЖА",
    subCategory: null,
    ingredients:
      "салат, томат, бекон, чеддер, цибуля, майонез подається з картоплею по-селянськи та соусом Цезар",
  },
  {
    menuNumber: 4,
    image: "",
    title: "КУРЯЧИЙ БУРГЕР",
    price: "9.50",
    category: "ЇЖА",
    subCategory: null,
    ingredients:
      "салат, томат, бекон, цибуля, майонез подається з картоплею по-селянськи та соусом Цезар",
  },
  {
    menuNumber: 5,
    image: "",
    title: "КУРЯЧИЙ КЛУБ",
    price: "9.00",
    category: "ЇЖА",
    subCategory: null,
    ingredients:
      "пухкий хліб, майонез, бекон, курка, салат, гауда, томат подається з картоплею по-селянськи та соусом Цезар",
  },
  {
    menuNumber: 6,
    image: "",
    title: "ПІЦА СПЕЦІАЛЬНА 830г",
    price: "11.00",
    category: "ЇЖА",
    subCategory: null,
    ingredients: "моцарела, томат, соус, зелений перець, бекон",
  },
  {
    menuNumber: 7,
    image: "",
    title: "ПІЦА МАРГАРИТА 730г",
    price: "10.00",
    category: "ЇЖА",
    subCategory: null,
    ingredients: "томат, соус, гауда",
  },
  {
    menuNumber: 8,
    image: "",
    title: "САЛАТ ЦЕЗАР",
    price: "8.00",
    category: "ЇЖА",
    subCategory: null,
    ingredients: "айсберг, черрі, соус Цезар, курка, пармезан, сухарики",
  },
  {
    menuNumber: 9,
    image: "",
    title: "ФРУКТОВИЙ САЛАТ",
    price: "8.00",
    category: "ЇЖА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 10,
    image: "",
    title: "ТОСТ ЦЕЗАР",
    price: "5.00",
    category: "ЇЖА",
    subCategory: null,
    ingredients: "гауда-шинка з чіпсами",
  },
  {
    menuNumber: 101,
    image: "",
    title: "ФРЕДО ЕСПРЕСО",
    price: "5.00",
    category: "КАВА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 102,
    image: "",
    title: "ФРЕДО КАПУЧИНО",
    price: "5.00",
    category: "КАВА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 103,
    image: "",
    title: "ФРАППЕ",
    price: "5.00",
    category: "КАВА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 104,
    image: "",
    title: "ДЕКАФЕЇН",
    price: "5.00",
    category: "КАВА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 105,
    image: "",
    title: "ГАРЯЧИЙ ШОКОЛАД",
    price: "5.00",
    category: "КАВА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 201,
    image: "",
    title: "ВІЄНСЬКИЙ ШОКОЛАД",
    price: "5.50",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 202,
    image: "",
    title: "ЕСПРЕСО",
    price: "4.50",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 203,
    image: "",
    title: "ПОДВІЙНИЙ ЕСПРЕСО",
    price: "5.00",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 204,
    image: "",
    title: "КАПУЧИНО",
    price: "5.00",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 205,
    image: "",
    title: "ПОДВІЙНИЙ КАПУЧИНО",
    price: "5.50",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 206,
    image: "",
    title: "НЕСКАФЕ",
    price: "5.00",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 207,
    image: "",
    title: "ГРЕЦЬКА КАВА",
    price: "4.50",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 208,
    image: "",
    title: "ПОДВІЙНА ГРЕЦЬКА КАВА",
    price: "5.00",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 209,
    image: "",
    title: "АМЕРИКАНО",
    price: "4.50",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 210,
    image: "",
    title: "ПОДВІЙНЕ АМЕРИКАНО",
    price: "5.00",
    category: "ШОКОЛАД",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 301,
    image: "",
    title: "СВІЖОВИТИСНУТИЙ АПЕЛЬСИНОВИЙ СІК",
    price: "5.50",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 302,
    image: "",
    title: "АПЕЛЬСИНОВИЙ СІК",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 303,
    image: "",
    title: "ВИШНЕВИЙ СІК",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 304,
    image: "",
    title: "БАНАНОВИЙ СІК",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 305,
    image: "",
    title: "АНАНАСОВИЙ СІК",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 306,
    image: "",
    title: "ПЕРСИКОВИЙ СІК",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 307,
    image: "",
    title: "МІКСОВАНИЙ СІК",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 308,
    image: "",
    title: "ХОЛОДНИЙ ЧАЙ З ПЕРСИКОМ",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 309,
    image: "",
    title: "ХОЛОДНИЙ ЧАЙ З ЛИМОНОМ",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 310,
    image: "",
    title: "ХОЛОДНИЙ ЗЕЛЕНИЙ ЧАЙ",
    price: "5.00",
    category: "СОКИ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 401,
    image: "",
    title: "КОКА-КОЛА",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 402,
    image: "",
    title: "КОКА-КОЛА ЗЕРО",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 403,
    image: "",
    title: "КОКА-КОЛА ЛАЙТ",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 404,
    image: "",
    title: "ЛИМОНАД",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 405,
    image: "",
    title: "ПОРТОКАЛА",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 406,
    image: "",
    title: "СПРАЙТ",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 407,
    image: "",
    title: "ПЕР'Є",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 408,
    image: "",
    title: "THREE CENTS PINK",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 409,
    image: "",
    title: "СУРОТІ",
    price: "5.00",
    category: "НАПОЇ",
    subCategory: null,
    ingredients: "330мл",
  },
  {
    menuNumber: 501,
    image: "",
    title: "ПОЛУНИЧНА ГРАНІТА",
    price: "5.00",
    category: "ГРАНІТА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 502,
    image: "",
    title: "ЛИМОННА ГРАНІТА",
    price: "5.00",
    category: "ГРАНІТА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 503,
    image: "",
    title: "КАВУННА ГРАНІТА",
    price: "5.00",
    category: "ГРАНІТА",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 601,
    image: "",
    title: "РЕД БУЛ",
    price: "5.00",
    category: "ГОТОВІ НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 602,
    image: "",
    title: "СМІРНОФФ АЙС",
    price: "5.00",
    category: "ГОТОВІ НАПОЇ",
    subCategory: null,
    ingredients: "275 мл",
  },
  {
    menuNumber: 603,
    image: "",
    title: "GORDON'S SPACE",
    price: "5.00",
    category: "ГОТОВІ НАПОЇ",
    subCategory: null,
    ingredients: "275 мл",
  },
  {
    menuNumber: 604,
    image: "",
    title: "BREEZER (ЛИМОН/КАВУН)",
    price: "5.00",
    category: "ГОТОВІ НАПОЇ",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 701,
    image: "",
    title: "FIX SMALL DRAUGHT BEER",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "330ml",
  },
  {
    menuNumber: 702,
    image: "",
    title: "FIX BIG DRAUGHT BEER",
    price: "6.00",
    category: "BEERS",
    subCategory: null,
    ingredients: "500ml",
  },
  {
    menuNumber: 703,
    image: "",
    title: "CORONA",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 704,
    image: "",
    title: "SOL",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 705,
    image: "",
    title: "MYTHOS",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 706,
    image: "",
    title: "ALPHA",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 707,
    image: "",
    title: "KAISER",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 708,
    image: "",
    title: "HEINEKEN",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 709,
    image: "",
    title: "HEINEKEN ZERO",
    price: "5.50",
    category: "BEERS",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 801,
    image: "",
    title: "WHITE SEMI SWEET",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 802,
    image: "",
    title: "RED SEMI SWEET",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 803,
    image: "",
    title: "RED SANGRIA",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 804,
    image: "",
    title: "WHITE SANGRIA",
    price: "6.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 805,
    image: "",
    title: "MALAGOUZIA",
    price: "40.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 806,
    image: "",
    title: "TECHNI ALEPIAS",
    price: "40.00",
    category: "WINES",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 901,
    image: "",
    title: "PLOMARY",
    price: "8.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "200ml",
  },
  {
    menuNumber: 902,
    image: "",
    title: "IDONIKO WITHOUT",
    price: "9.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "200ml",
  },
  {
    menuNumber: 903,
    image: "",
    title: "SHOT",
    price: "3.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 904,
    image: "",
    title: "SUBMARINE",
    price: "4.00",
    category: "APERITIF",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1001,
    image: "",
    title: "SMIRNOFF",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1002,
    image: "",
    title: "ABSOLUT",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1003,
    image: "",
    title: "SERKOVA",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1004,
    image: "",
    title: "STOLICHNAYA",
    price: "8.00",
    price1: "80.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1005,
    image: "",
    title: "GREY GOOSE",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1006,
    image: "",
    title: "BELUGA",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1007,
    image: "",
    title: "BELVEDERE",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1008,
    image: "",
    title: "CIROC",
    price: "10.00",
    price1: "100.00",
    category: "VODKA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1101,
    image: "",
    title: "GORDONS",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1102,
    image: "",
    title: "GORDONS PINK",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1103,
    image: "",
    title: "TANGUERAY",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1104,
    image: "",
    title: "TANGUERAY",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1105,
    image: "",
    title: "BEEFEATER",
    price: "8.00",
    price1: "80.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1106,
    image: "",
    title: "BOMBAY BLUE",
    price: "9.00",
    price1: "90.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1107,
    image: "",
    title: "HENDRICKS",
    price: "10.00",
    price1: "100.00",
    category: "GIN",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1201,
    image: "",
    title: "CUERVO",
    price: "8.00",
    price1: "80.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1202,
    image: "",
    title: "ESPECIAL",
    price: "8.00",
    price1: "80.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1203,
    image: "",
    title: "PATRON",
    price: "9.00",
    price1: "90.00",
    category: "TEQUILA",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1301,
    image: "",
    title: "BACARDI",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1302,
    image: "",
    title: "HAVANA",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1303,
    image: "",
    title: "HAVANA 7 YEARS",
    price: "9.00",
    price1: "90.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1304,
    image: "",
    title: "MYERS",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1305,
    image: "",
    title: "SAILOR JERRY",
    price: "9.00",
    price1: "90.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
  {
    menuNumber: 1306,
    image: "",
    title: "CAPTAIN MORGAN",
    price: "8.00",
    price1: "80.00",
    category: "RUM",
    subCategory: null,
    ingredients: "",
  },
];
